#set ( CPACK_CMAKE_GENERATOR "Unix Makefiles" )

set ( CPACK_PACKAGE_NAME "Drawpile" )

set ( CPACK_PACKAGE_VERSION_MAJOR "0" )
set ( CPACK_PACKAGE_VERSION_MINOR "5" )
set ( CPACK_PACKAGE_VERSION_PATCH "0" )

set ( CPACK_PACKAGE_DESCRIPTION_SUMMARY "" )

set ( CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}" )
set ( CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}" )

set ( CPACK_GENERATOR "TBZ2;NSIS" )

set ( CPACK_SOURCE_GENERATOR "TBZ2" )
set ( CPACK_SOURCE_PACKAGE_FILE_NAME "drawpile-{$CPACK_PACKAGE_VERSION}-src")

set ( CPACK_SOURCE_IGNORE_FILES "/\\.svn/;\\.swp$;mui_*;ui_*" )

set ( CPACK_INSTALL_CMAKE_PROJECTS ".;Drawpile;ALL;/" )
set ( CPACK_PACKAGE_INSTALL_DIRECTORY "Drawpile" )
set ( CPACK_INSTALL_REGISTRY_KEY "Drawpile" )

set ( CPACK_STRIP_FILES "bin/drawpile;bin/drawpile-srv" )
