if ( WIN32 )
	find_file ( STRIP_CMD strip.exe )
else ( WIN32 )
	find_file ( STRIP_CMD strip )
endif ( WIN32 )

macro ( strip_exe target )
	if ( STRIP_CMD )
		add_custom_command(
			TARGET ${target}
			POST_BUILD
			COMMAND ${STRIP_CMD} ${target}
		)
	endif ( STRIP_CMD )
endmacro ( strip_exe target )

macro ( dump_resource ResourceFile )
	if ( WIN32 )
		file ( WRITE ${ResourceFile} "#include <winver.h>\n\n" )
		file ( APPEND ${ResourceFile} "VS_VERSION_INFO VERSIONINFO\n" )
		file ( APPEND ${ResourceFile} "\tFILEVERSION ${VERSION_MAJOR},${VERSION_MINOR},${VERSION_BUG},0\n" )
		file ( APPEND ${ResourceFile} "\tPRODUCTVERSION ${VERSION_MAJOR},${VERSION_MINOR},${VERSION_BUG},0\n" )
		file ( APPEND ${ResourceFile} "\tFILEFLAGSMASK VS_FFI_FILEFLAGSMASK\n" )
		file ( APPEND ${ResourceFile} "\t#ifdef _DEBUG\n\tFILEFLAGS VS_FF_DEBUG\n\t#else\n\tFILEFLAGS 0\n\t#endif\n" )
		file ( APPEND ${ResourceFile} "\tFILEOS VOS_NT\n" )
		if ( IsSharedLib )
			file ( APPEND ${ResourceFile} "\tFILETYPE VFT_DLL\n" )
		else ( IsSharedLib )
			file ( APPEND ${ResourceFile} "\tFILETYPE VFT_APP\n" )
		endif ( IsSharedLib )
		file ( APPEND ${ResourceFile} "\tFILESUBTYPE 0\n" )
		file ( APPEND ${ResourceFile} "BEGIN\n\tBLOCK \"StringFileInfo\"\n\tBEGIN\n" )
		file ( APPEND ${ResourceFile} "\t\tBLOCK \"040904E4\"\n\t\tBEGIN\n" )
		file ( APPEND ${ResourceFile} "\t\t\tVALUE \"Comments\", \"${COMMENT}\\0\"\n" )
		file ( APPEND ${ResourceFile} "\t\t\tVALUE \"FileDescription\", \"${DESCRIPTION}\\0\"\n" )
		file ( APPEND ${ResourceFile} "\t\t\tVALUE \"FileVersion\", \"${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_BUG}\\0\"\n" )
		file ( APPEND ${ResourceFile} "\t\t\tVALUE \"InternalName\", \"${INTERNALNAME}\\0\"\n" )
		file ( APPEND ${ResourceFile} "\t\t\tVALUE \"LegalCopyright\", \"${COPYRIGHT}\\0\"\n" )
		file ( APPEND ${ResourceFile} "\t\t\tVALUE \"OriginalFilename\", \"${ORIGFILENAME}\\0\"\n" )
		file ( APPEND ${ResourceFile} "\t\t\tVALUE \"ProductName\", \"${FULLNAME}\\0\"\n" )
		file ( APPEND ${ResourceFile} "\t\t\tVALUE \"ProductVersion\", \"${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_BUG}\\0\"\n" )
		file ( APPEND ${ResourceFile} "\t\tEND\n\tEND\n" )
		file ( APPEND ${ResourceFile} "\tBLOCK \"VarFileInfo\"\n\tBEGIN\n" )
		file ( APPEND ${ResourceFile} "\t\tVALUE \"Translation\", 0x409, 1252\n" )
		file ( APPEND ${ResourceFile} "\tEND\nEND\n" )
	endif ( WIN32 )
endmacro ( dump_resource ResourceFile )
