// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef DPENGINE_LOAD_ENUMS_H
#define DPENGINE_LOAD_ENUMS_H

typedef enum DP_LoadResult {
    DP_LOAD_RESULT_SUCCESS,
    DP_LOAD_RESULT_BAD_ARGUMENTS,
    DP_LOAD_RESULT_UNKNOWN_FORMAT,
    DP_LOAD_RESULT_OPEN_ERROR,
    DP_LOAD_RESULT_READ_ERROR,
    DP_LOAD_RESULT_BAD_MIMETYPE,
    DP_LOAD_RESULT_RECORDING_INCOMPATIBLE,
    DP_LOAD_RESULT_UNSUPPORTED_PSD_BITS_PER_CHANNEL,
    DP_LOAD_RESULT_UNSUPPORTED_PSD_COLOR_MODE,
    DP_LOAD_RESULT_BAD_DIMENSIONS,
    DP_LOAD_RESULT_INTERNAL_ERROR,
} DP_LoadResult;

#endif
