// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef DPENGINE_SAVE_ENUMS_H
#define DPENGINE_SAVE_ENUMS_H

typedef enum DP_SaveImageType {
    DP_SAVE_IMAGE_UNKNOWN,
    DP_SAVE_IMAGE_ORA,
    DP_SAVE_IMAGE_PNG,
    DP_SAVE_IMAGE_JPEG,
    DP_SAVE_IMAGE_PSD,
    DP_SAVE_IMAGE_WEBP,
    DP_SAVE_IMAGE_PROJECT_CANVAS,
} DP_SaveImageType;

typedef enum DP_SaveResult {
    DP_SAVE_RESULT_SUCCESS,
    DP_SAVE_RESULT_BAD_ARGUMENTS,
    DP_SAVE_RESULT_BAD_DIMENSIONS,
    DP_SAVE_RESULT_UNKNOWN_FORMAT,
    DP_SAVE_RESULT_FLATTEN_ERROR,
    DP_SAVE_RESULT_OPEN_ERROR,
    DP_SAVE_RESULT_WRITE_ERROR,
    DP_SAVE_RESULT_INTERNAL_ERROR,
    DP_SAVE_RESULT_CANCEL,
} DP_SaveResult;

#endif
