#!/bin/bash

# Build Drawpile server stable branch AppImage
# Run inside a CentOS 6 docker image.
# This script is partially based on https://github.com/probonopd/AppImages/blob/master/recipes/subsurface/Recipe

set -e
set -x


export LD_LIBRARY_PATH=/opt/rh/devtoolset-2/root/usr/lib:$LD_LIBRARY_PATH # Needed for bundling the libraries into AppDir below
export PATH=/opt/rh/devtoolset-2/root/usr/bin/:$CMAKE_PATH:$PATH # Needed at compile time to find Qt and cmake

SRCDIR=/Drawpile
WORKDIR=/work
BUILDDIR=/build
APPDIR=/Drawpile.AppDir
APPIMGKIT=/AppImageKit-master

# Copy source code to work dir and apply appimage specific patches
mkdir -p $WORKDIR
cp -r ${SRCDIR}/* $WORKDIR
cd $WORKDIR
git apply pkg/appimage/appimage.patch

# Build server
mkdir -p $BUILDDIR
mkdir -p $APPDIR
cd $BUILDDIR
cmake3 $WORKDIR -DSERVER=ON -DCLIENT=OFF -DSERVERGUI=OFF -DINSTALL_DOC=OFF -DCMAKE_INSTALL_PREFIX=$APPDIR/usr
make -j5

# Install only the required server parts
mkdir -p $APPDIR/usr/bin
cp bin/drawpile-srv $APPDIR/usr/bin
mkdir -p $APPDIR/usr/share/drawpile-srv

# Construct AppDir bundle
cd $APPDIR

cp $APPIMGKIT/AppRun .
chmod a+x AppRun


# Copy libraries
mkdir -p usr/lib

ldd usr/bin/drawpile-srv | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -vL '{}' ./usr/lib/ || true
#ldd usr/lib/qt5/plugins/platforms/libqxcb.so | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -vL '{}' ./usr/lib || true


cd usr/ ; find . -type f -exec sed -i -e 's|/usr/lib|././/lib|g' {} \; ; cd ..

# Remove blacklisted libs
BLACKLISTED_FILES=$(wget -q https://github.com/probonopd/AppImages/raw/master/excludelist -O - | sed '/^\s*$/d' | sed '/^#.*$/d')
for FILE in $BLACKLISTED_FILES ; do
	FOUND=$(find . -type f -name "${FILE}" 2>/dev/null)
	if [ ! -z "$FOUND" ] ; then
		echo "Deleting blacklisted ${FOUND}"
		rm -f "${FOUND}"
	fi
done


# Copy desktop stuff
cat <<END > drawpile-srv.desktop
[Desktop Entry]
Version=1.0
Name=Drawpile Server

GenericName=Dedicated server for Drawpile

Exec=drawpile-srv
Type=Application
Icon=drawpile
Categories=Network;
Terminal=true

END

cp $SRCDIR/desktop/drawpile-64x64.png drawpile.png

# Build Appimage

cd /Drawpile
VERSION=$(ls $APPDIR/usr/bin/drawpile-* | cut -d - -f 2-)
APPIMAGE="Drawpile-$VERSION.AppImage"

rm -f /out/$APPIMAGE
$APPIMGKIT/AppImageAssistant.AppDir/package $APPDIR /out/$APPIMAGE

