// SPDX-License-Identifier: GPL-3.0-or-later
// This file is auto-generated by configen.py, do not edit it manually.
#ifndef LIBCLIENT_CONFIG_CONFIG_H
#define LIBCLIENT_CONFIG_CONFIG_H
#include <QByteArray>
#include <QColor>
#include <QCoreApplication>
#include <QMap>
#include <QObject>
#include <QRect>
#include <QString>
#include <QStringList>
#include <QVariantHash>
#include <QVariantList>
#include <QVariantMap>
#include <QVector>
#ifdef Q_OS_ANDROID
#	include <QScreen>
#endif

#if !defined(NATIVE_DIALOGS_SETTING_AVAILABLE) && defined(Q_OS_WIN)
#	define NATIVE_DIALOGS_SETTING_AVAILABLE 1
#endif

// Call a setter member function when the setting changes.
#define CFG_BIND_SET(CFG, SETTING, SUBJECT, SETTER)                            \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		auto *_subject = (SUBJECT);                                            \
		_subject->SETTER(_cfg->get##SETTING());                                \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject, &SETTER);      \
	} while(0)

// Like CFG_BIND_SET, but the setter is a lambda.
#define CFG_BIND_SET_FN(CFG, SETTING, SUBJECT, FN)                             \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		auto *_subject = (SUBJECT);                                            \
		auto _fn = FN;                                                         \
		std::invoke(_fn, _cfg->get##SETTING());                                \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject,                \
			std::move(_fn));                                                   \
	} while(0)

// Like CFG_BIND_SET, but the "setter" takes no arguments.
#define CFG_BIND_NOTIFY(CFG, SETTING, SUBJECT, NOTIFIER)                       \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		auto *_subject = (SUBJECT);                                            \
		_subject->NOTIFIER();                                                  \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject, &NOTIFIER);    \
	} while(0)

// Like CFG_BIND_SET_FN, but the "setter" takes no arguments.
#define CFG_BIND_NOTIFY_FN(CFG, SETTING, SUBJECT, FN)                          \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		auto *_subject = (SUBJECT);                                            \
		auto _fn = FN;                                                         \
		std::invoke(_fn);                                                      \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject,                \
			std::move(_fn));                                                   \
	} while(0)

// Synchronize and object with the configuration using the given setter to set
// the value in the object and the given signal to update the configuration.
#define CFG_BIND_OBJECT(CFG, SETTING, SUBJECT, SETTER, SIGNAL)                 \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		auto *_subject = (SUBJECT);                                            \
		std::invoke(SETTER, _subject, _cfg->get##SETTING());                   \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject, SETTER);       \
		::QObject::connect(                                                    \
			_subject, SIGNAL, _cfg, &::config::Config::set##SETTING);          \
	} while(0)

// Like CFG_BIND_OBJECT, but the setter is a lambda.
#define CFG_BIND_OBJECT_FN(CFG, SETTING, SUBJECT, FN, SIGNAL)                  \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		auto *_subject = (SUBJECT);                                            \
		auto _fn = FN;                                                         \
		std::invoke(_fn, _cfg->get##SETTING());                                \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject,                \
			std::move(_fn));                                                   \
		::QObject::connect(                                                    \
			_subject, SIGNAL, _cfg, &::config::Config::set##SETTING);          \
	} while(0)

#define CFG_BIND_ACTION(CFG, SETTING, SUBJECT)                                 \
	CFG_BIND_OBJECT(                                                           \
		CFG, SETTING, SUBJECT, &::QAction::setChecked, &::QAction::toggled)

#define CFG_BIND_BUTTONGROUP_TYPE(CFG, SETTING, SUBJECT, TYPE)                 \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		::QButtonGroup *_subject = (SUBJECT);                                  \
		auto _setter = [_subject](TYPE _value) {                               \
			::QAbstractButton *_button = _subject->button(int(_value));        \
			if(_button) {                                                      \
				_button->setChecked(true);                                     \
			} else {                                                           \
				qWarning() << "Bound invalid value" << _value << "to setting"  \
						   << #SETTING << "on QButtonGroup" << #SUBJECT;       \
			}                                                                  \
		};                                                                     \
		std::invoke(_setter, _cfg->get##SETTING());                            \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject,                \
			std::move(_setter));                                               \
		::QObject::connect(                                                    \
			_subject, &QButtonGroup::idToggled, _cfg,                          \
			[_cfg](int _id, bool _checked) {                                   \
				if(_checked) {                                                 \
					_cfg->set##SETTING(TYPE(_id));                             \
				}                                                              \
			});                                                                \
	} while(0)

#define CFG_BIND_BUTTONGROUP(CFG, SETTING, SUBJECT)                            \
	CFG_BIND_BUTTONGROUP_TYPE(CFG, SETTING, SUBJECT, int)

#define CFG_BIND_CHECKBOX(CFG, SETTING, SUBJECT)                               \
	CFG_BIND_OBJECT(                                                           \
		CFG, SETTING, SUBJECT, &::QCheckBox::setChecked,                       \
		&::QCheckBox::toggled)

#define CFG_BIND_COMBOBOX_INDEX(CFG, SETTING, SUBJECT)                         \
	CFG_BIND_OBJECT(                                                           \
		CFG, SETTING, SUBJECT, &::QComboBox::setCurrentIndex,                  \
		::QOverload<int>::of(&::QComboBox::currentIndexChanged))

#define CFG_BIND_COMBOBOX_VALUE_ROLE(                                          \
	CFG, SETTING, SUBJECT, TYPE_ARG, TO_TYPE, ROLE)                            \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		::QComboBox *_subject = (SUBJECT);                                     \
		int _role = (ROLE);                                                    \
		auto _setter = [_subject, _role](TYPE_ARG _value) {                    \
			::QVariant _variant = ::QVariant::fromValue(_value);               \
			int _index = _subject->findData(_variant, _role);                  \
			if(_index == -1) {                                                 \
				qWarning() << "Bound invalid value" << _variant                \
						   << "to setting" << #SETTING << "on QComboBox"       \
						   << #SUBJECT;                                        \
			} else {                                                           \
				_subject->setCurrentIndex(_index);                             \
			}                                                                  \
		};                                                                     \
		std::invoke(_setter, _cfg->get##SETTING());                            \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject,                \
			std::move(_setter));                                               \
		::QObject::connect(                                                    \
			_subject, QOverload<int>::of(&QComboBox::currentIndexChanged),     \
			_cfg, [_cfg, _subject, _role](int _index) {                        \
				_cfg->set##SETTING(                                            \
					_subject->itemData(_index, _role).TO_TYPE());              \
			});                                                                \
	} while(0)

#define CFG_BIND_COMBOBOX_USER_INT(CFG, SETTING, SUBJECT)                      \
	CFG_BIND_COMBOBOX_VALUE_ROLE(                                              \
		CFG, SETTING, SUBJECT, int, toInt, Qt::UserRole)

#define CFG_BIND_COMBOBOX_USER_STRING(CFG, SETTING, SUBJECT)                   \
	CFG_BIND_COMBOBOX_VALUE_ROLE(                                              \
		CFG, SETTING, SUBJECT, const QString &, toString, Qt::UserRole)

#define CFG_BIND_DOUBLESPINBOX(CFG, SETTING, SUBJECT)                          \
	CFG_BIND_OBJECT(                                                           \
		CFG, SETTING, SUBJECT, &::QDoubleSpinBox::setValue,                    \
		::QOverload<double>::of(&::QDoubleSpinBox::valueChanged))

#define CFG_BIND_LINEEDIT(CFG, SETTING, SUBJECT)                               \
	CFG_BIND_OBJECT(                                                           \
		CFG, SETTING, SUBJECT, &::QLineEdit::setText,                          \
		&::QLineEdit::textChanged)

#define CFG_BIND_PLAINTEXTEDIT(CFG, SETTING, SUBJECT)                          \
	do {                                                                       \
		::config::Config *_cfg = (CFG);                                        \
		::QPlainTextEdit *_subject = (SUBJECT);                                \
		_subject->setPlainText(_cfg->get##SETTING());                          \
		::QObject::connect(                                                    \
			_cfg, &::config::Config::change##SETTING, _subject,                \
			[_subject](const QString &_text) {                                 \
				/* Setting the text moves the caret back to the beginning and  \
				 * purges the edit history, so we only set if necessary. */    \
				if(_subject->toPlainText() != _text) {                         \
					_subject->setPlainText(_text);                             \
				}                                                              \
			});                                                                \
		::QObject::connect(                                                    \
			_subject, &::QPlainTextEdit::textChanged, _cfg, [_cfg, _subject] { \
				_cfg->set##SETTING(_subject->toPlainText());                   \
			});                                                                \
	} while(0)

#define CFG_BIND_SLIDERSPINBOX(CFG, SETTING, SUBJECT)                          \
	CFG_BIND_OBJECT(                                                           \
		CFG, SETTING, SUBJECT, &::KisSliderSpinBox::setValue,                  \
		::QOverload<int>::of(&::KisSliderSpinBox::valueChanged))

#define CFG_BIND_SPINBOX(CFG, SETTING, SUBJECT)                                \
	CFG_BIND_OBJECT(                                                           \
		CFG, SETTING, SUBJECT, &::QSpinBox::setValue,                          \
		::QOverload<int>::of(&::QSpinBox::valueChanged))

namespace config {

class Config : public QObject {
	Q_OBJECT
public:
	explicit Config(QObject *parent = nullptr);

	virtual QString path() const = 0;

	virtual bool submit() = 0;
	void trySubmit();


	virtual int getActionBar() const = 0;
	virtual void setActionBar(int value) = 0;
	static int defaultActionBar();

	virtual int getActionBarLocation() const = 0;
	virtual void setActionBarLocation(int value) = 0;
	static int defaultActionBarLocation();

	virtual int getAlphaLockCursor() const = 0;
	virtual void setAlphaLockCursor(int value) = 0;
	static int defaultAlphaLockCursor();

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	virtual bool getAndroidScalingAskOnStartup() const = 0;
	virtual void setAndroidScalingAskOnStartup(bool value) = 0;
	static bool defaultAndroidScalingAskOnStartup();
#endif

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	virtual double getAndroidScalingLastInitialScale() const = 0;
	virtual void setAndroidScalingLastInitialScale(double value) = 0;
	static double defaultAndroidScalingLastInitialScale();
#endif

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	virtual double getAndroidScalingTargetScale() const = 0;
	virtual void setAndroidScalingTargetScale(double value) = 0;
	static double defaultAndroidScalingTargetScale();
#endif

#if defined(KRITA_QATTRIBUTE_ANDROID_EMULATE_MOUSE_BUTTONS_FOR_PAGE_UP_DOWN)
	virtual bool
	getAndroidWorkaroundEmulateMouseButtonsForPageUpDown() const = 0;
	virtual void
	setAndroidWorkaroundEmulateMouseButtonsForPageUpDown(bool value) = 0;
	static bool defaultAndroidWorkaroundEmulateMouseButtonsForPageUpDown();
#endif

#if defined(KRITA_QATTRIBUTE_ANDROID_IGNORE_HISTORIC_TABLET_EVENTS)
	virtual bool getAndroidWorkaroundIgnoreHistoricTabletEvents() const = 0;
	virtual void setAndroidWorkaroundIgnoreHistoricTabletEvents(bool value) = 0;
	static bool defaultAndroidWorkaroundIgnoreHistoricTabletEvents();
#endif

	virtual int getAnimationExportFormat() const = 0;
	virtual void setAnimationExportFormat(int value) = 0;
	static int defaultAnimationExportFormat();

	virtual bool getAutoRecordHost() const = 0;
	virtual void setAutoRecordHost(bool value) = 0;
	static bool defaultAutoRecordHost();

	virtual bool getAutoRecordJoin() const = 0;
	virtual void setAutoRecordJoin(bool value) = 0;
	static bool defaultAutoRecordJoin();

	virtual int getAutoRecordMetadataIntervalMinutes() const = 0;
	virtual void setAutoRecordMetadataIntervalMinutes(int value) = 0;
	static int defaultAutoRecordMetadataIntervalMinutes();

	virtual int getAutoRecordSnapshotIntervalMinutes() const = 0;
	virtual void setAutoRecordSnapshotIntervalMinutes(int value) = 0;
	static int defaultAutoRecordSnapshotIntervalMinutes();

	virtual int getAutomaticAlphaPreserve() const = 0;
	virtual void setAutomaticAlphaPreserve(int value) = 0;
	static int defaultAutomaticAlphaPreserve();

	virtual int getBrushCursor() const = 0;
	virtual void setBrushCursor(int value) = 0;
	static int defaultBrushCursor();

	virtual double getBrushOutlineWidth() const = 0;
	virtual void setBrushOutlineWidth(double value) = 0;
	static double defaultBrushOutlineWidth();

	virtual bool getBrushPresetsAttach() const = 0;
	virtual void setBrushPresetsAttach(bool value) = 0;
	static bool defaultBrushPresetsAttach();

	virtual int getBrushSlotCount() const = 0;
	virtual void setBrushSlotCount(int value) = 0;
	static int defaultBrushSlotCount();

	virtual bool getCancelDeselects() const = 0;
	virtual void setCancelDeselects(bool value) = 0;
	static bool defaultCancelDeselects();

	virtual bool getCanvasScrollBars() const = 0;
	virtual void setCanvasScrollBars(bool value) = 0;
	static bool defaultCanvasScrollBars();

	virtual QVariantMap getCanvasShortcuts() const = 0;
	virtual void setCanvasShortcuts(const QVariantMap &value) = 0;
	static QVariantMap defaultCanvasShortcuts();

	virtual QColor getCanvasViewBackgroundColor() const = 0;
	virtual void setCanvasViewBackgroundColor(const QColor &value) = 0;
	static QColor defaultCanvasViewBackgroundColor();

#if defined(Q_OS_ANDROID)
	virtual bool getCaptureVolumeRocker() const = 0;
	virtual void setCaptureVolumeRocker(bool value) = 0;
	static bool defaultCaptureVolumeRocker();
#endif

	virtual QColor getCheckerColor1() const = 0;
	virtual void setCheckerColor1(const QColor &value) = 0;
	static QColor defaultCheckerColor1();

	virtual QColor getCheckerColor2() const = 0;
	virtual void setCheckerColor2(const QColor &value) = 0;
	static QColor defaultCheckerColor2();

	virtual int getColorCircleGamutMaskAngle() const = 0;
	virtual void setColorCircleGamutMaskAngle(int value) = 0;
	static int defaultColorCircleGamutMaskAngle();

	virtual double getColorCircleGamutMaskOpacity() const = 0;
	virtual void setColorCircleGamutMaskOpacity(double value) = 0;
	static double defaultColorCircleGamutMaskOpacity();

	virtual QString getColorCircleGamutMaskPath() const = 0;
	virtual void setColorCircleGamutMaskPath(const QString &value) = 0;
	static QString defaultColorCircleGamutMaskPath();

	virtual int getColorCircleHueAngle() const = 0;
	virtual void setColorCircleHueAngle(int value) = 0;
	static int defaultColorCircleHueAngle();

	virtual int getColorCircleHueCount() const = 0;
	virtual void setColorCircleHueCount(int value) = 0;
	static int defaultColorCircleHueCount();

	virtual bool getColorCircleHueLimit() const = 0;
	virtual void setColorCircleHueLimit(bool value) = 0;
	static bool defaultColorCircleHueLimit();

	virtual int getColorCircleSaturationCount() const = 0;
	virtual void setColorCircleSaturationCount(int value) = 0;
	static int defaultColorCircleSaturationCount();

	virtual bool getColorCircleSaturationLimit() const = 0;
	virtual void setColorCircleSaturationLimit(bool value) = 0;
	static bool defaultColorCircleSaturationLimit();

	virtual int getColorCircleValueCount() const = 0;
	virtual void setColorCircleValueCount(int value) = 0;
	static int defaultColorCircleValueCount();

	virtual bool getColorCircleValueLimit() const = 0;
	virtual void setColorCircleValueLimit(bool value) = 0;
	static bool defaultColorCircleValueLimit();

	virtual int getColorShadesBorderThickness() const = 0;
	virtual void setColorShadesBorderThickness(int value) = 0;
	static int defaultColorShadesBorderThickness();

	virtual int getColorShadesColumnCount() const = 0;
	virtual void setColorShadesColumnCount(int value) = 0;
	static int defaultColorShadesColumnCount();

	virtual QVariantList getColorShadesConfig() const = 0;
	virtual void setColorShadesConfig(const QVariantList &value) = 0;
	static QVariantList defaultColorShadesConfig();

	virtual bool getColorShadesEnabled() const = 0;
	virtual void setColorShadesEnabled(bool value) = 0;
	static bool defaultColorShadesEnabled();

	virtual int getColorShadesRowHeight() const = 0;
	virtual void setColorShadesRowHeight(int value) = 0;
	static int defaultColorShadesRowHeight();

	virtual int getColorSlidersMode() const = 0;
	virtual void setColorSlidersMode(int value) = 0;
	static int defaultColorSlidersMode();

	virtual bool getColorSlidersShowAll() const = 0;
	virtual void setColorSlidersShowAll(bool value) = 0;
	static bool defaultColorSlidersShowAll();

	virtual bool getColorSlidersShowInput() const = 0;
	virtual void setColorSlidersShowInput(bool value) = 0;
	static bool defaultColorSlidersShowInput();

	virtual int getColorSwatchFlags() const = 0;
	virtual void setColorSwatchFlags(int value) = 0;
	static int defaultColorSwatchFlags();

	virtual int getColorWheelAlign() const = 0;
	virtual void setColorWheelAlign(int value) = 0;
	static int defaultColorWheelAlign();

	virtual int getColorWheelAngle() const = 0;
	virtual void setColorWheelAngle(int value) = 0;
	static int defaultColorWheelAngle();

	virtual bool getColorWheelMirror() const = 0;
	virtual void setColorWheelMirror(bool value) = 0;
	static bool defaultColorWheelMirror();

	virtual int getColorWheelPreview() const = 0;
	virtual void setColorWheelPreview(int value) = 0;
	static int defaultColorWheelPreview();

	virtual int getColorWheelShape() const = 0;
	virtual void setColorWheelShape(int value) = 0;
	static int defaultColorWheelShape();

	virtual int getColorWheelSpace() const = 0;
	virtual void setColorWheelSpace(int value) = 0;
	static int defaultColorWheelSpace();

	virtual bool getCompactChat() const = 0;
	virtual void setCompactChat(bool value) = 0;
	static bool defaultCompactChat();

	virtual bool getConfirmLayerDelete() const = 0;
	virtual void setConfirmLayerDelete(bool value) = 0;
	static bool defaultConfirmLayerDelete();

#if defined(Q_OS_ANDROID) && defined(DRAWPILE_USE_CONNECT_SERVICE)
	virtual bool getConnectionNotification() const = 0;
	virtual void setConnectionNotification(bool value) = 0;
	static bool defaultConnectionNotification();
#endif

	virtual QVector<QVariantMap> getCurvesPresets() const = 0;
	virtual void setCurvesPresets(const QVector<QVariantMap> &value) = 0;
	static QVector<QVariantMap> defaultCurvesPresets();

	virtual int getDebounceDelayMs() const = 0;
	virtual void setDebounceDelayMs(int value) = 0;
	static int defaultDebounceDelayMs();

	virtual bool getDonationLinksEnabled() const = 0;
	virtual void setDonationLinksEnabled(bool value) = 0;
	static bool defaultDonationLinksEnabled();

	virtual bool getDoubleTapAltToFocusCanvas() const = 0;
	virtual void setDoubleTapAltToFocusCanvas(bool value) = 0;
	static bool defaultDoubleTapAltToFocusCanvas();

	virtual int getEngineFrameRate() const = 0;
	virtual void setEngineFrameRate(int value) = 0;
	static int defaultEngineFrameRate();

	virtual int getEngineSnapshotCount() const = 0;
	virtual void setEngineSnapshotCount(int value) = 0;
	static int defaultEngineSnapshotCount();

	virtual int getEngineSnapshotInterval() const = 0;
	virtual void setEngineSnapshotInterval(int value) = 0;
	static int defaultEngineSnapshotInterval();

	virtual int getEngineUndoDepth() const = 0;
	virtual void setEngineUndoDepth(int value) = 0;
	static int defaultEngineUndoDepth();

	virtual int getEraseCursor() const = 0;
	virtual void setEraseCursor(int value) = 0;
	static int defaultEraseCursor();

	virtual QString getFfmpegPath() const = 0;
	virtual void setFfmpegPath(const QString &value) = 0;
	static QString defaultFfmpegPath();

	virtual bool getFilterClosed() const = 0;
	virtual void setFilterClosed(bool value) = 0;
	static bool defaultFilterClosed();

	virtual bool getFilterDuplicates() const = 0;
	virtual void setFilterDuplicates(bool value) = 0;
	static bool defaultFilterDuplicates();

	virtual bool getFilterInactive() const = 0;
	virtual void setFilterInactive(bool value) = 0;
	static bool defaultFilterInactive();

	virtual bool getFilterLocked() const = 0;
	virtual void setFilterLocked(bool value) = 0;
	static bool defaultFilterLocked();

	virtual bool getFilterNsfm() const = 0;
	virtual void setFilterNsfm(bool value) = 0;
	static bool defaultFilterNsfm();

	virtual bool getFlipbookUpscaling() const = 0;
	virtual void setFlipbookUpscaling(bool value) = 0;
	static bool defaultFlipbookUpscaling();

	virtual QRect getFlipbookWindow() const = 0;
	virtual void setFlipbookWindow(const QRect &value) = 0;
	static QRect defaultFlipbookWindow();

	virtual int getFontSize() const = 0;
	virtual void setFontSize(int value) = 0;
	static int defaultFontSize();

	virtual int getFourFingerTap() const = 0;
	virtual void setFourFingerTap(int value) = 0;
	static int defaultFourFingerTap();

	virtual QString getGlobalPressureCurve() const = 0;
	virtual void setGlobalPressureCurve(const QString &value) = 0;
	static QString defaultGlobalPressureCurve();

	virtual QString getGlobalPressureCurveEraser() const = 0;
	virtual void setGlobalPressureCurveEraser(const QString &value) = 0;
	static QString defaultGlobalPressureCurveEraser();

	virtual int getGlobalPressureCurveMode() const = 0;
	virtual void setGlobalPressureCurveMode(int value) = 0;
	static int defaultGlobalPressureCurveMode();

	virtual bool getHostEnableAdvanced() const = 0;
	virtual void setHostEnableAdvanced(bool value) = 0;
	static bool defaultHostEnableAdvanced();

	virtual bool getIgnoreCarrierGradeNat() const = 0;
	virtual void setIgnoreCarrierGradeNat(bool value) = 0;
	static bool defaultIgnoreCarrierGradeNat();

	virtual QVector<QVariantMap> getInputPresets() const = 0;
	virtual void setInputPresets(const QVector<QVariantMap> &value) = 0;
	static QVector<QVariantMap> defaultInputPresets();

	virtual bool getInsecurePasswordStorage() const = 0;
	virtual void setInsecurePasswordStorage(bool value) = 0;
	static bool defaultInsecurePasswordStorage();

	virtual int getInterfaceMode() const = 0;
	virtual void setInterfaceMode(int value) = 0;
	static int defaultInterfaceMode();

	virtual bool getInterpolateInputs() const = 0;
	virtual void setInterpolateInputs(bool value) = 0;
	static bool defaultInterpolateInputs();

	virtual bool getInviteIncludePassword() const = 0;
	virtual void setInviteIncludePassword(bool value) = 0;
	static bool defaultInviteIncludePassword();

	virtual int getKineticScrollGesture() const = 0;
	virtual void setKineticScrollGesture(int value) = 0;
	static int defaultKineticScrollGesture();

	virtual bool getKineticScrollHideBars() const = 0;
	virtual void setKineticScrollHideBars(bool value) = 0;
	static bool defaultKineticScrollHideBars();

	virtual int getKineticScrollThreshold() const = 0;
	virtual void setKineticScrollThreshold(int value) = 0;
	static int defaultKineticScrollThreshold();

	virtual QString getLanguage() const = 0;
	virtual void setLanguage(const QString &value) = 0;
	static QString defaultLanguage();

	virtual bool getLastAnnounce() const = 0;
	virtual void setLastAnnounce(bool value) = 0;
	static bool defaultLastAnnounce();

	virtual QString getLastAvatar() const = 0;
	virtual void setLastAvatar(const QString &value) = 0;
	static QString defaultLastAvatar();

	virtual int getLastBrowseSortColumn() const = 0;
	virtual void setLastBrowseSortColumn(int value) = 0;
	static int defaultLastBrowseSortColumn();

	virtual int getLastBrowseSortDirection() const = 0;
	virtual void setLastBrowseSortDirection(int value) = 0;
	static int defaultLastBrowseSortDirection();

	virtual QString getLastFileOpenPath() const = 0;
	virtual void setLastFileOpenPath(const QString &value) = 0;
	static QString defaultLastFileOpenPath();

	virtual QVariantMap getLastFileOpenPaths() const = 0;
	virtual void setLastFileOpenPaths(const QVariantMap &value) = 0;
	static QVariantMap defaultLastFileOpenPaths();

	virtual int getLastHostServer() const = 0;
	virtual void setLastHostServer(int value) = 0;
	static int defaultLastHostServer();

	virtual int getLastHostType() const = 0;
	virtual void setLastHostType(int value) = 0;
	static int defaultLastHostType();

	virtual QString getLastIdAlias() const = 0;
	virtual void setLastIdAlias(const QString &value) = 0;
	static QString defaultLastIdAlias();

	virtual QString getLastJoinAddress() const = 0;
	virtual void setLastJoinAddress(const QString &value) = 0;
	static QString defaultLastJoinAddress();

	virtual bool getLastKeepChat() const = 0;
	virtual void setLastKeepChat(bool value) = 0;
	static bool defaultLastKeepChat();

	virtual QStringList getLastListingUrls() const = 0;
	virtual void setLastListingUrls(const QStringList &value) = 0;
	static QStringList defaultLastListingUrls();

	virtual bool getLastNsfm() const = 0;
	virtual void setLastNsfm(bool value) = 0;
	static bool defaultLastNsfm();

	virtual int getLastPalette() const = 0;
	virtual void setLastPalette(int value) = 0;
	static int defaultLastPalette();

	virtual QByteArray getLastSessionAuthList() const = 0;
	virtual void setLastSessionAuthList(const QByteArray &value) = 0;
	static QByteArray defaultLastSessionAuthList();

	virtual bool getLastSessionAutomatic() const = 0;
	virtual void setLastSessionAutomatic(bool value) = 0;
	static bool defaultLastSessionAutomatic();

	virtual QByteArray getLastSessionBanList() const = 0;
	virtual void setLastSessionBanList(const QByteArray &value) = 0;
	static QByteArray defaultLastSessionBanList();

	virtual QString getLastSessionOpPassword() const = 0;
	virtual void setLastSessionOpPassword(const QString &value) = 0;
	static QString defaultLastSessionOpPassword();

	virtual QString getLastSessionPassword() const = 0;
	virtual void setLastSessionPassword(const QString &value) = 0;
	static QString defaultLastSessionPassword();

	virtual QVariantMap getLastSessionPermissions() const = 0;
	virtual void setLastSessionPermissions(const QVariantMap &value) = 0;
	static QVariantMap defaultLastSessionPermissions();

	virtual QString getLastSessionTitle() const = 0;
	virtual void setLastSessionTitle(const QString &value) = 0;
	static QString defaultLastSessionTitle();

	virtual int getLastSessionUndoDepth() const = 0;
	virtual void setLastSessionUndoDepth(int value) = 0;
	static int defaultLastSessionUndoDepth();

	virtual QString getLastStartDialogDateTime() const = 0;
	virtual void setLastStartDialogDateTime(const QString &value) = 0;
	static QString defaultLastStartDialogDateTime();

	virtual int getLastStartDialogPage() const = 0;
	virtual void setLastStartDialogPage(int value) = 0;
	static int defaultLastStartDialogPage();

	virtual QSize getLastStartDialogSize() const = 0;
	virtual void setLastStartDialogSize(const QSize &value) = 0;
	static QSize defaultLastStartDialogSize();

	virtual int getLastTool() const = 0;
	virtual void setLastTool(int value) = 0;
	static int defaultLastTool();

	virtual QColor getLastToolBackgroundColor() const = 0;
	virtual void setLastToolBackgroundColor(const QColor &value) = 0;
	static QColor defaultLastToolBackgroundColor();

	virtual QColor getLastToolColor() const = 0;
	virtual void setLastToolColor(const QColor &value) = 0;
	static QColor defaultLastToolColor();

	virtual QString getLastUsername() const = 0;
	virtual void setLastUsername(const QString &value) = 0;
	static QString defaultLastUsername();

	virtual QMap<QString, bool> getLastWindowActions() const = 0;
	virtual void setLastWindowActions(const QMap<QString, bool> &value) = 0;
	static QMap<QString, bool> defaultLastWindowActions();

	virtual QVariantMap getLastWindowDocks() const = 0;
	virtual void setLastWindowDocks(const QVariantMap &value) = 0;
	static QVariantMap defaultLastWindowDocks();

	virtual bool getLastWindowMaximized() const = 0;
	virtual void setLastWindowMaximized(bool value) = 0;
	static bool defaultLastWindowMaximized();

	virtual QPoint getLastWindowPosition() const = 0;
	virtual void setLastWindowPosition(const QPoint &value) = 0;
	static QPoint defaultLastWindowPosition();

	virtual QSize getLastWindowSize() const = 0;
	virtual void setLastWindowSize(const QSize &value) = 0;
	static QSize defaultLastWindowSize();

	virtual QByteArray getLastWindowState() const = 0;
	virtual void setLastWindowState(const QByteArray &value) = 0;
	static QByteArray defaultLastWindowState();

	virtual QByteArray getLastWindowViewState() const = 0;
	virtual void setLastWindowViewState(const QByteArray &value) = 0;
	static QByteArray defaultLastWindowViewState();

	virtual int getLayerSketchOpacityPercent() const = 0;
	virtual void setLayerSketchOpacityPercent(int value) = 0;
	static int defaultLayerSketchOpacityPercent();

	virtual QColor getLayerSketchTint() const = 0;
	virtual void setLayerSketchTint(const QColor &value) = 0;
	static QColor defaultLayerSketchTint();

	virtual QVector<QVariantMap> getLayouts() const = 0;
	virtual void setLayouts(const QVector<QVariantMap> &value) = 0;
	static QVector<QVariantMap> defaultLayouts();

	virtual int getLayoutsVersion() const = 0;
	virtual void setLayoutsVersion(int value) = 0;
	static int defaultLayoutsVersion();

	virtual bool getLeftyMode() const = 0;
	virtual void setLeftyMode(bool value) = 0;
	static bool defaultLeftyMode();

	virtual QVector<QVariantMap> getListServers() const = 0;
	virtual void setListServers(const QVector<QVariantMap> &value) = 0;
	static QVector<QVariantMap> defaultListServers();

	virtual bool getLongPressEnabled() const = 0;
	virtual void setLongPressEnabled(bool value) = 0;
	static bool defaultLongPressEnabled();

	virtual bool getMentionEnabled() const = 0;
	virtual void setMentionEnabled(bool value) = 0;
	static bool defaultMentionEnabled();

	virtual QString getMentionTriggerList() const = 0;
	virtual void setMentionTriggerList(const QString &value) = 0;
	static QString defaultMentionTriggerList();

	virtual int getMessageQueueDrainRate() const = 0;
	virtual void setMessageQueueDrainRate(int value) = 0;
	static int defaultMessageQueueDrainRate();

	virtual bool getMouseSmoothing() const = 0;
	virtual void setMouseSmoothing(bool value) = 0;
	static bool defaultMouseSmoothing();

#if defined(NATIVE_DIALOGS_SETTING_AVAILABLE)
	virtual bool getNativeDialogs() const = 0;
	virtual void setNativeDialogs(bool value) = 0;
	static bool defaultNativeDialogs();
#endif

	virtual bool getNavigatorRealtime() const = 0;
	virtual void setNavigatorRealtime(bool value) = 0;
	static bool defaultNavigatorRealtime();

	virtual bool getNavigatorShowCursors() const = 0;
	virtual void setNavigatorShowCursors(bool value) = 0;
	static bool defaultNavigatorShowCursors();

	virtual int getNetworkProxyMode() const = 0;
	virtual void setNetworkProxyMode(int value) = 0;
	static int defaultNetworkProxyMode();

	virtual QColor getNewCanvasBackColor() const = 0;
	virtual void setNewCanvasBackColor(const QColor &value) = 0;
	static QColor defaultNewCanvasBackColor();

	virtual QSize getNewCanvasSize() const = 0;
	virtual void setNewCanvasSize(const QSize &value) = 0;
	static QSize defaultNewCanvasSize();

	virtual bool getNotifFlashChat() const = 0;
	virtual void setNotifFlashChat(bool value) = 0;
	static bool defaultNotifFlashChat();

	virtual bool getNotifFlashDisconnect() const = 0;
	virtual void setNotifFlashDisconnect(bool value) = 0;
	static bool defaultNotifFlashDisconnect();

	virtual bool getNotifFlashLock() const = 0;
	virtual void setNotifFlashLock(bool value) = 0;
	static bool defaultNotifFlashLock();

	virtual bool getNotifFlashLogin() const = 0;
	virtual void setNotifFlashLogin(bool value) = 0;
	static bool defaultNotifFlashLogin();

	virtual bool getNotifFlashLogout() const = 0;
	virtual void setNotifFlashLogout(bool value) = 0;
	static bool defaultNotifFlashLogout();

	virtual bool getNotifFlashPrivateChat() const = 0;
	virtual void setNotifFlashPrivateChat(bool value) = 0;
	static bool defaultNotifFlashPrivateChat();

	virtual bool getNotifFlashUnlock() const = 0;
	virtual void setNotifFlashUnlock(bool value) = 0;
	static bool defaultNotifFlashUnlock();

	virtual bool getNotifPopupChat() const = 0;
	virtual void setNotifPopupChat(bool value) = 0;
	static bool defaultNotifPopupChat();

	virtual bool getNotifPopupDisconnect() const = 0;
	virtual void setNotifPopupDisconnect(bool value) = 0;
	static bool defaultNotifPopupDisconnect();

	virtual bool getNotifPopupLock() const = 0;
	virtual void setNotifPopupLock(bool value) = 0;
	static bool defaultNotifPopupLock();

	virtual bool getNotifPopupLogin() const = 0;
	virtual void setNotifPopupLogin(bool value) = 0;
	static bool defaultNotifPopupLogin();

	virtual bool getNotifPopupLogout() const = 0;
	virtual void setNotifPopupLogout(bool value) = 0;
	static bool defaultNotifPopupLogout();

	virtual bool getNotifPopupPrivateChat() const = 0;
	virtual void setNotifPopupPrivateChat(bool value) = 0;
	static bool defaultNotifPopupPrivateChat();

	virtual bool getNotifPopupUnlock() const = 0;
	virtual void setNotifPopupUnlock(bool value) = 0;
	static bool defaultNotifPopupUnlock();

	virtual bool getNotifSoundChat() const = 0;
	virtual void setNotifSoundChat(bool value) = 0;
	static bool defaultNotifSoundChat();

	virtual bool getNotifSoundDisconnect() const = 0;
	virtual void setNotifSoundDisconnect(bool value) = 0;
	static bool defaultNotifSoundDisconnect();

	virtual bool getNotifSoundLock() const = 0;
	virtual void setNotifSoundLock(bool value) = 0;
	static bool defaultNotifSoundLock();

	virtual bool getNotifSoundLogin() const = 0;
	virtual void setNotifSoundLogin(bool value) = 0;
	static bool defaultNotifSoundLogin();

	virtual bool getNotifSoundLogout() const = 0;
	virtual void setNotifSoundLogout(bool value) = 0;
	static bool defaultNotifSoundLogout();

	virtual bool getNotifSoundPrivateChat() const = 0;
	virtual void setNotifSoundPrivateChat(bool value) = 0;
	static bool defaultNotifSoundPrivateChat();

	virtual bool getNotifSoundUnlock() const = 0;
	virtual void setNotifSoundUnlock(bool value) = 0;
	static bool defaultNotifSoundUnlock();

	virtual int getOneFingerTap() const = 0;
	virtual void setOneFingerTap(int value) = 0;
	static int defaultOneFingerTap();

	virtual int getOneFingerTapAndHold() const = 0;
	virtual void setOneFingerTapAndHold(int value) = 0;
	static int defaultOneFingerTapAndHold();

	virtual int getOneFingerTouch() const = 0;
	virtual void setOneFingerTouch(int value) = 0;
	static int defaultOneFingerTouch();

	virtual int getOnionSkinsFrameCount() const = 0;
	virtual void setOnionSkinsFrameCount(int value) = 0;
	static int defaultOnionSkinsFrameCount();

	virtual QMap<int, int> getOnionSkinsFrames() const = 0;
	virtual void setOnionSkinsFrames(const QMap<int, int> &value) = 0;
	static QMap<int, int> defaultOnionSkinsFrames();

	virtual QColor getOnionSkinsTintAbove() const = 0;
	virtual void setOnionSkinsTintAbove(const QColor &value) = 0;
	static QColor defaultOnionSkinsTintAbove();

	virtual QColor getOnionSkinsTintBelow() const = 0;
	virtual void setOnionSkinsTintBelow(const QColor &value) = 0;
	static QColor defaultOnionSkinsTintBelow();

	virtual bool getOnionSkinsWrap() const = 0;
	virtual void setOnionSkinsWrap(bool value) = 0;
	static bool defaultOnionSkinsWrap();

	virtual bool getOverrideFontSize() const = 0;
	virtual void setOverrideFontSize(bool value) = 0;
	static bool defaultOverrideFontSize();

	virtual bool getParentalControlsAutoTag() const = 0;
	virtual void setParentalControlsAutoTag(bool value) = 0;
	static bool defaultParentalControlsAutoTag();

	virtual bool getParentalControlsForceCensor() const = 0;
	virtual void setParentalControlsForceCensor(bool value) = 0;
	static bool defaultParentalControlsForceCensor();

	virtual bool getParentalControlsHideLocked() const = 0;
	virtual void setParentalControlsHideLocked(bool value) = 0;
	static bool defaultParentalControlsHideLocked();

	virtual int getParentalControlsLevel() const = 0;
	virtual void setParentalControlsLevel(int value) = 0;
	static int defaultParentalControlsLevel();

	virtual QByteArray getParentalControlsLocked() const = 0;
	virtual void setParentalControlsLocked(const QByteArray &value) = 0;
	static QByteArray defaultParentalControlsLocked();

	virtual QString getParentalControlsTags() const = 0;
	virtual void setParentalControlsTags(const QString &value) = 0;
	static QString defaultParentalControlsTags();

	virtual QString getPreferredExportFormat() const = 0;
	virtual void setPreferredExportFormat(const QString &value) = 0;
	static QString defaultPreferredExportFormat();

	virtual QString getPreferredSaveFormat() const = 0;
	virtual void setPreferredSaveFormat(const QString &value) = 0;
	static QString defaultPreferredSaveFormat();

	virtual bool getPromptLayerCreate() const = 0;
	virtual void setPromptLayerCreate(bool value) = 0;
	static bool defaultPromptLayerCreate();

#if defined(Q_OS_MACOS)
	virtual bool getQuitOnLastWindowClosed() const = 0;
	virtual void setQuitOnLastWindowClosed(bool value) = 0;
	static bool defaultQuitOnLastWindowClosed();
#endif

	virtual QStringList getRecentFiles() const = 0;
	virtual void setRecentFiles(const QStringList &value) = 0;
	static QStringList defaultRecentFiles();

	virtual QStringList getRecentHosts() const = 0;
	virtual void setRecentHosts(const QStringList &value) = 0;
	static QStringList defaultRecentHosts();

	virtual QStringList getRecentRemoteHosts() const = 0;
	virtual void setRecentRemoteHosts(const QStringList &value) = 0;
	static QStringList defaultRecentRemoteHosts();

	virtual int getRenderCanvas() const = 0;
	virtual void setRenderCanvas(int value) = 0;
	static int defaultRenderCanvas();

	virtual bool getRenderSmooth() const = 0;
	virtual void setRenderSmooth(bool value) = 0;
	static bool defaultRenderSmooth();

	virtual bool getRenderUpdateFull() const = 0;
	virtual void setRenderUpdateFull(bool value) = 0;
	static bool defaultRenderUpdateFull();

	virtual int getSamplingRingVisibility() const = 0;
	virtual void setSamplingRingVisibility(int value) = 0;
	static int defaultSamplingRingVisibility();

	virtual QColor getSelectionColor() const = 0;
	virtual void setSelectionColor(const QColor &value) = 0;
	static QColor defaultSelectionColor();

	virtual bool getServerAutoReset() const = 0;
	virtual void setServerAutoReset(bool value) = 0;
	static bool defaultServerAutoReset();

	virtual bool getServerHideIp() const = 0;
	virtual void setServerHideIp(bool value) = 0;
	static bool defaultServerHideIp();

	virtual int getServerPort() const = 0;
	virtual void setServerPort(int value) = 0;
	static int defaultServerPort();

	virtual int getServerTimeout() const = 0;
	virtual void setServerTimeout(int value) = 0;
	static int defaultServerTimeout();

	virtual bool getShareBrushSlotColor() const = 0;
	virtual void setShareBrushSlotColor(bool value) = 0;
	static bool defaultShareBrushSlotColor();

	virtual QVariantMap getShortcuts() const = 0;
	virtual void setShortcuts(const QVariantMap &value) = 0;
	static QVariantMap defaultShortcuts();

	virtual bool getShowInviteDialogOnHost() const = 0;
	virtual void setShowInviteDialogOnHost(bool value) = 0;
	static bool defaultShowInviteDialogOnHost();

	virtual bool getShowNsfmWarningOnJoin() const = 0;
	virtual void setShowNsfmWarningOnJoin(bool value) = 0;
	static bool defaultShowNsfmWarningOnJoin();

	virtual bool getShowTransformNotices() const = 0;
	virtual void setShowTransformNotices(bool value) = 0;
	static bool defaultShowTransformNotices();

	virtual bool getShowTrayIcon() const = 0;
	virtual void setShowTrayIcon(bool value) = 0;
	static bool defaultShowTrayIcon();

	virtual bool getShowViewModeNotices() const = 0;
	virtual void setShowViewModeNotices(bool value) = 0;
	static bool defaultShowViewModeNotices();

	virtual int getSmoothing() const = 0;
	virtual void setSmoothing(int value) = 0;
	static int defaultSmoothing();

	virtual int getSoundVolume() const = 0;
	virtual void setSoundVolume(int value) = 0;
	static int defaultSoundVolume();

	virtual int getTabletDriver() const = 0;
	virtual void setTabletDriver(int value) = 0;
	static int defaultTabletDriver();

	virtual int getTabletEraserAction() const = 0;
	virtual void setTabletEraserAction(int value) = 0;
	static int defaultTabletEraserAction();

	virtual bool getTabletEvents() const = 0;
	virtual void setTabletEvents(bool value) = 0;
	static bool defaultTabletEvents();

	virtual int getTabletPressTimerDelay() const = 0;
	virtual void setTabletPressTimerDelay(int value) = 0;
	static int defaultTabletPressTimerDelay();

	virtual bool getTemporaryToolSwitch() const = 0;
	virtual void setTemporaryToolSwitch(bool value) = 0;
	static bool defaultTemporaryToolSwitch();

	virtual int getTemporaryToolSwitchMs() const = 0;
	virtual void setTemporaryToolSwitchMs(int value) = 0;
	static int defaultTemporaryToolSwitchMs();

	virtual QString getThemePalette() const = 0;
	virtual void setThemePalette(const QString &value) = 0;
	static QString defaultThemePalette();

	virtual QString getThemeStyle() const = 0;
	virtual void setThemeStyle(const QString &value) = 0;
	static QString defaultThemeStyle();

	virtual int getThreeFingerTap() const = 0;
	virtual void setThreeFingerTap(int value) = 0;
	static int defaultThreeFingerTap();

	virtual QColor getTimelapseBackdropColor() const = 0;
	virtual void setTimelapseBackdropColor(const QColor &value) = 0;
	static QColor defaultTimelapseBackdropColor();

	virtual int getTimelapseDurationSeconds() const = 0;
	virtual void setTimelapseDurationSeconds(int value) = 0;
	static int defaultTimelapseDurationSeconds();

	virtual int getTimelapseExportFormat() const = 0;
	virtual void setTimelapseExportFormat(int value) = 0;
	static int defaultTimelapseExportFormat();

	virtual QColor getTimelapseFlashColor() const = 0;
	virtual void setTimelapseFlashColor(const QColor &value) = 0;
	static QColor defaultTimelapseFlashColor();

	virtual int getTimelapseFlashSeconds() const = 0;
	virtual void setTimelapseFlashSeconds(int value) = 0;
	static int defaultTimelapseFlashSeconds();

	virtual double getTimelapseFramerate() const = 0;
	virtual void setTimelapseFramerate(double value) = 0;
	static double defaultTimelapseFramerate();

	virtual int getTimelapseInterpolation() const = 0;
	virtual void setTimelapseInterpolation(int value) = 0;
	static int defaultTimelapseInterpolation();

	virtual int getTimelapseLingerAfterLoops() const = 0;
	virtual void setTimelapseLingerAfterLoops(int value) = 0;
	static int defaultTimelapseLingerAfterLoops();

	virtual int getTimelapseLingerAfterSeconds() const = 0;
	virtual void setTimelapseLingerAfterSeconds(int value) = 0;
	static int defaultTimelapseLingerAfterSeconds();

	virtual int getTimelapseLingerBeforeLoops() const = 0;
	virtual void setTimelapseLingerBeforeLoops(int value) = 0;
	static int defaultTimelapseLingerBeforeLoops();

	virtual int getTimelapseLingerBeforeSeconds() const = 0;
	virtual void setTimelapseLingerBeforeSeconds(int value) = 0;
	static int defaultTimelapseLingerBeforeSeconds();

	virtual int getTimelapseLogoLocation() const = 0;
	virtual void setTimelapseLogoLocation(int value) = 0;
	static int defaultTimelapseLogoLocation();

	virtual double getTimelapseLogoOffset() const = 0;
	virtual void setTimelapseLogoOffset(double value) = 0;
	static double defaultTimelapseLogoOffset();

	virtual int getTimelapseLogoOpacity() const = 0;
	virtual void setTimelapseLogoOpacity(int value) = 0;
	static int defaultTimelapseLogoOpacity();

	virtual double getTimelapseLogoScale() const = 0;
	virtual void setTimelapseLogoScale(double value) = 0;
	static double defaultTimelapseLogoScale();

	virtual double getTimelapseMaxDeltaSeconds() const = 0;
	virtual void setTimelapseMaxDeltaSeconds(double value) = 0;
	static double defaultTimelapseMaxDeltaSeconds();

	virtual int getTimelapseMaxQueueEntries() const = 0;
	virtual void setTimelapseMaxQueueEntries(int value) = 0;
	static int defaultTimelapseMaxQueueEntries();

	virtual bool getTimelapsePreferFfmpeg() const = 0;
	virtual void setTimelapsePreferFfmpeg(bool value) = 0;
	static bool defaultTimelapsePreferFfmpeg();

	virtual bool getTimelapseShowAdvanced() const = 0;
	virtual void setTimelapseShowAdvanced(bool value) = 0;
	static bool defaultTimelapseShowAdvanced();

	virtual bool getTimelapseTimeOwnOnly() const = 0;
	virtual void setTimelapseTimeOwnOnly(bool value) = 0;
	static bool defaultTimelapseTimeOwnOnly();

	virtual QVariantHash getToolBarConfig() const = 0;
	virtual void setToolBarConfig(const QVariantHash &value) = 0;
	static QVariantHash defaultToolBarConfig();

	virtual bool getToolToggle() const = 0;
	virtual void setToolToggle(bool value) = 0;
	static bool defaultToolToggle();

	virtual QMap<QString, QVariantHash> getToolset() const = 0;
	virtual void setToolset(const QMap<QString, QVariantHash> &value) = 0;
	static QMap<QString, QVariantHash> defaultToolset();

	virtual bool getTouchDrawPressure() const = 0;
	virtual void setTouchDrawPressure(bool value) = 0;
	static bool defaultTouchDrawPressure();

	virtual bool getTouchGestures() const = 0;
	virtual void setTouchGestures(bool value) = 0;
	static bool defaultTouchGestures();

	virtual int getTouchSmoothing() const = 0;
	virtual void setTouchSmoothing(int value) = 0;
	static int defaultTouchSmoothing();

	virtual int getTwoFingerPinch() const = 0;
	virtual void setTwoFingerPinch(int value) = 0;
	static int defaultTwoFingerPinch();

	virtual int getTwoFingerTap() const = 0;
	virtual void setTwoFingerTap(int value) = 0;
	static int defaultTwoFingerTap();

	virtual int getTwoFingerTwist() const = 0;
	virtual void setTwoFingerTwist(int value) = 0;
	static int defaultTwoFingerTwist();

	virtual bool getUpdateCheckEnabled() const = 0;
	virtual void setUpdateCheckEnabled(bool value) = 0;
	static bool defaultUpdateCheckEnabled();

	virtual bool getUseMipmaps() const = 0;
	virtual void setUseMipmaps(bool value) = 0;
	static bool defaultUseMipmaps();

	virtual int getUserMarkerPersistence() const = 0;
	virtual void setUserMarkerPersistence(int value) = 0;
	static int defaultUserMarkerPersistence();

	virtual QString getVideoExportCustomFfmpeg() const = 0;
	virtual void setVideoExportCustomFfmpeg(const QString &value) = 0;
	static QString defaultVideoExportCustomFfmpeg();

	virtual QString getVideoExportFfmpegPath() const = 0;
	virtual void setVideoExportFfmpegPath(const QString &value) = 0;
	static QString defaultVideoExportFfmpegPath();

	virtual int getVideoExportFormat() const = 0;
	virtual void setVideoExportFormat(int value) = 0;
	static int defaultVideoExportFormat();

	virtual int getVideoExportFrameHeight() const = 0;
	virtual void setVideoExportFrameHeight(int value) = 0;
	static int defaultVideoExportFrameHeight();

	virtual int getVideoExportFrameRate() const = 0;
	virtual void setVideoExportFrameRate(int value) = 0;
	static int defaultVideoExportFrameRate();

	virtual int getVideoExportFrameWidth() const = 0;
	virtual void setVideoExportFrameWidth(int value) = 0;
	static int defaultVideoExportFrameWidth();

	virtual int getVideoExportSizeChoice() const = 0;
	virtual void setVideoExportSizeChoice(int value) = 0;
	static int defaultVideoExportSizeChoice();

	virtual bool getWelcomePageShown() const = 0;
	virtual void setWelcomePageShown(bool value) = 0;
	static bool defaultWelcomePageShown();

	virtual bool getWriteLogFile() const = 0;
	virtual void setWriteLogFile(bool value) = 0;
	static bool defaultWriteLogFile();

Q_SIGNALS:
	void changeActionBar(int value);
	void changeActionBarLocation(int value);
	void changeAlphaLockCursor(int value);
#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	void changeAndroidScalingAskOnStartup(bool value);
#endif
#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	void changeAndroidScalingLastInitialScale(double value);
#endif
#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	void changeAndroidScalingTargetScale(double value);
#endif
#if defined(KRITA_QATTRIBUTE_ANDROID_EMULATE_MOUSE_BUTTONS_FOR_PAGE_UP_DOWN)
	void changeAndroidWorkaroundEmulateMouseButtonsForPageUpDown(bool value);
#endif
#if defined(KRITA_QATTRIBUTE_ANDROID_IGNORE_HISTORIC_TABLET_EVENTS)
	void changeAndroidWorkaroundIgnoreHistoricTabletEvents(bool value);
#endif
	void changeAnimationExportFormat(int value);
	void changeAutoRecordHost(bool value);
	void changeAutoRecordJoin(bool value);
	void changeAutoRecordMetadataIntervalMinutes(int value);
	void changeAutoRecordSnapshotIntervalMinutes(int value);
	void changeAutomaticAlphaPreserve(int value);
	void changeBrushCursor(int value);
	void changeBrushOutlineWidth(double value);
	void changeBrushPresetsAttach(bool value);
	void changeBrushSlotCount(int value);
	void changeCancelDeselects(bool value);
	void changeCanvasScrollBars(bool value);
	void changeCanvasShortcuts(const QVariantMap &value);
	void changeCanvasViewBackgroundColor(const QColor &value);
#if defined(Q_OS_ANDROID)
	void changeCaptureVolumeRocker(bool value);
#endif
	void changeCheckerColor1(const QColor &value);
	void changeCheckerColor2(const QColor &value);
	void changeColorCircleGamutMaskAngle(int value);
	void changeColorCircleGamutMaskOpacity(double value);
	void changeColorCircleGamutMaskPath(const QString &value);
	void changeColorCircleHueAngle(int value);
	void changeColorCircleHueCount(int value);
	void changeColorCircleHueLimit(bool value);
	void changeColorCircleSaturationCount(int value);
	void changeColorCircleSaturationLimit(bool value);
	void changeColorCircleValueCount(int value);
	void changeColorCircleValueLimit(bool value);
	void changeColorShadesBorderThickness(int value);
	void changeColorShadesColumnCount(int value);
	void changeColorShadesConfig(const QVariantList &value);
	void changeColorShadesEnabled(bool value);
	void changeColorShadesRowHeight(int value);
	void changeColorSlidersMode(int value);
	void changeColorSlidersShowAll(bool value);
	void changeColorSlidersShowInput(bool value);
	void changeColorSwatchFlags(int value);
	void changeColorWheelAlign(int value);
	void changeColorWheelAngle(int value);
	void changeColorWheelMirror(bool value);
	void changeColorWheelPreview(int value);
	void changeColorWheelShape(int value);
	void changeColorWheelSpace(int value);
	void changeCompactChat(bool value);
	void changeConfirmLayerDelete(bool value);
#if defined(Q_OS_ANDROID) && defined(DRAWPILE_USE_CONNECT_SERVICE)
	void changeConnectionNotification(bool value);
#endif
	void changeCurvesPresets(const QVector<QVariantMap> &value);
	void changeDebounceDelayMs(int value);
	void changeDonationLinksEnabled(bool value);
	void changeDoubleTapAltToFocusCanvas(bool value);
	void changeEngineFrameRate(int value);
	void changeEngineSnapshotCount(int value);
	void changeEngineSnapshotInterval(int value);
	void changeEngineUndoDepth(int value);
	void changeEraseCursor(int value);
	void changeFfmpegPath(const QString &value);
	void changeFilterClosed(bool value);
	void changeFilterDuplicates(bool value);
	void changeFilterInactive(bool value);
	void changeFilterLocked(bool value);
	void changeFilterNsfm(bool value);
	void changeFlipbookUpscaling(bool value);
	void changeFlipbookWindow(const QRect &value);
	void changeFontSize(int value);
	void changeFourFingerTap(int value);
	void changeGlobalPressureCurve(const QString &value);
	void changeGlobalPressureCurveEraser(const QString &value);
	void changeGlobalPressureCurveMode(int value);
	void changeHostEnableAdvanced(bool value);
	void changeIgnoreCarrierGradeNat(bool value);
	void changeInputPresets(const QVector<QVariantMap> &value);
	void changeInsecurePasswordStorage(bool value);
	void changeInterfaceMode(int value);
	void changeInterpolateInputs(bool value);
	void changeInviteIncludePassword(bool value);
	void changeKineticScrollGesture(int value);
	void changeKineticScrollHideBars(bool value);
	void changeKineticScrollThreshold(int value);
	void changeLanguage(const QString &value);
	void changeLastAnnounce(bool value);
	void changeLastAvatar(const QString &value);
	void changeLastBrowseSortColumn(int value);
	void changeLastBrowseSortDirection(int value);
	void changeLastFileOpenPath(const QString &value);
	void changeLastFileOpenPaths(const QVariantMap &value);
	void changeLastHostServer(int value);
	void changeLastHostType(int value);
	void changeLastIdAlias(const QString &value);
	void changeLastJoinAddress(const QString &value);
	void changeLastKeepChat(bool value);
	void changeLastListingUrls(const QStringList &value);
	void changeLastNsfm(bool value);
	void changeLastPalette(int value);
	void changeLastSessionAuthList(const QByteArray &value);
	void changeLastSessionAutomatic(bool value);
	void changeLastSessionBanList(const QByteArray &value);
	void changeLastSessionOpPassword(const QString &value);
	void changeLastSessionPassword(const QString &value);
	void changeLastSessionPermissions(const QVariantMap &value);
	void changeLastSessionTitle(const QString &value);
	void changeLastSessionUndoDepth(int value);
	void changeLastStartDialogDateTime(const QString &value);
	void changeLastStartDialogPage(int value);
	void changeLastStartDialogSize(const QSize &value);
	void changeLastTool(int value);
	void changeLastToolBackgroundColor(const QColor &value);
	void changeLastToolColor(const QColor &value);
	void changeLastUsername(const QString &value);
	void changeLastWindowActions(const QMap<QString, bool> &value);
	void changeLastWindowDocks(const QVariantMap &value);
	void changeLastWindowMaximized(bool value);
	void changeLastWindowPosition(const QPoint &value);
	void changeLastWindowSize(const QSize &value);
	void changeLastWindowState(const QByteArray &value);
	void changeLastWindowViewState(const QByteArray &value);
	void changeLayerSketchOpacityPercent(int value);
	void changeLayerSketchTint(const QColor &value);
	void changeLayouts(const QVector<QVariantMap> &value);
	void changeLayoutsVersion(int value);
	void changeLeftyMode(bool value);
	void changeListServers(const QVector<QVariantMap> &value);
	void changeLongPressEnabled(bool value);
	void changeMentionEnabled(bool value);
	void changeMentionTriggerList(const QString &value);
	void changeMessageQueueDrainRate(int value);
	void changeMouseSmoothing(bool value);
#if defined(NATIVE_DIALOGS_SETTING_AVAILABLE)
	void changeNativeDialogs(bool value);
#endif
	void changeNavigatorRealtime(bool value);
	void changeNavigatorShowCursors(bool value);
	void changeNetworkProxyMode(int value);
	void changeNewCanvasBackColor(const QColor &value);
	void changeNewCanvasSize(const QSize &value);
	void changeNotifFlashChat(bool value);
	void changeNotifFlashDisconnect(bool value);
	void changeNotifFlashLock(bool value);
	void changeNotifFlashLogin(bool value);
	void changeNotifFlashLogout(bool value);
	void changeNotifFlashPrivateChat(bool value);
	void changeNotifFlashUnlock(bool value);
	void changeNotifPopupChat(bool value);
	void changeNotifPopupDisconnect(bool value);
	void changeNotifPopupLock(bool value);
	void changeNotifPopupLogin(bool value);
	void changeNotifPopupLogout(bool value);
	void changeNotifPopupPrivateChat(bool value);
	void changeNotifPopupUnlock(bool value);
	void changeNotifSoundChat(bool value);
	void changeNotifSoundDisconnect(bool value);
	void changeNotifSoundLock(bool value);
	void changeNotifSoundLogin(bool value);
	void changeNotifSoundLogout(bool value);
	void changeNotifSoundPrivateChat(bool value);
	void changeNotifSoundUnlock(bool value);
	void changeOneFingerTap(int value);
	void changeOneFingerTapAndHold(int value);
	void changeOneFingerTouch(int value);
	void changeOnionSkinsFrameCount(int value);
	void changeOnionSkinsFrames(const QMap<int, int> &value);
	void changeOnionSkinsTintAbove(const QColor &value);
	void changeOnionSkinsTintBelow(const QColor &value);
	void changeOnionSkinsWrap(bool value);
	void changeOverrideFontSize(bool value);
	void changeParentalControlsAutoTag(bool value);
	void changeParentalControlsForceCensor(bool value);
	void changeParentalControlsHideLocked(bool value);
	void changeParentalControlsLevel(int value);
	void changeParentalControlsLocked(const QByteArray &value);
	void changeParentalControlsTags(const QString &value);
	void changePreferredExportFormat(const QString &value);
	void changePreferredSaveFormat(const QString &value);
	void changePromptLayerCreate(bool value);
#if defined(Q_OS_MACOS)
	void changeQuitOnLastWindowClosed(bool value);
#endif
	void changeRecentFiles(const QStringList &value);
	void changeRecentHosts(const QStringList &value);
	void changeRecentRemoteHosts(const QStringList &value);
	void changeRenderCanvas(int value);
	void changeRenderSmooth(bool value);
	void changeRenderUpdateFull(bool value);
	void changeSamplingRingVisibility(int value);
	void changeSelectionColor(const QColor &value);
	void changeServerAutoReset(bool value);
	void changeServerHideIp(bool value);
	void changeServerPort(int value);
	void changeServerTimeout(int value);
	void changeShareBrushSlotColor(bool value);
	void changeShortcuts(const QVariantMap &value);
	void changeShowInviteDialogOnHost(bool value);
	void changeShowNsfmWarningOnJoin(bool value);
	void changeShowTransformNotices(bool value);
	void changeShowTrayIcon(bool value);
	void changeShowViewModeNotices(bool value);
	void changeSmoothing(int value);
	void changeSoundVolume(int value);
	void changeTabletDriver(int value);
	void changeTabletEraserAction(int value);
	void changeTabletEvents(bool value);
	void changeTabletPressTimerDelay(int value);
	void changeTemporaryToolSwitch(bool value);
	void changeTemporaryToolSwitchMs(int value);
	void changeThemePalette(const QString &value);
	void changeThemeStyle(const QString &value);
	void changeThreeFingerTap(int value);
	void changeTimelapseBackdropColor(const QColor &value);
	void changeTimelapseDurationSeconds(int value);
	void changeTimelapseExportFormat(int value);
	void changeTimelapseFlashColor(const QColor &value);
	void changeTimelapseFlashSeconds(int value);
	void changeTimelapseFramerate(double value);
	void changeTimelapseInterpolation(int value);
	void changeTimelapseLingerAfterLoops(int value);
	void changeTimelapseLingerAfterSeconds(int value);
	void changeTimelapseLingerBeforeLoops(int value);
	void changeTimelapseLingerBeforeSeconds(int value);
	void changeTimelapseLogoLocation(int value);
	void changeTimelapseLogoOffset(double value);
	void changeTimelapseLogoOpacity(int value);
	void changeTimelapseLogoScale(double value);
	void changeTimelapseMaxDeltaSeconds(double value);
	void changeTimelapseMaxQueueEntries(int value);
	void changeTimelapsePreferFfmpeg(bool value);
	void changeTimelapseShowAdvanced(bool value);
	void changeTimelapseTimeOwnOnly(bool value);
	void changeToolBarConfig(const QVariantHash &value);
	void changeToolToggle(bool value);
	void changeToolset(const QMap<QString, QVariantHash> &value);
	void changeTouchDrawPressure(bool value);
	void changeTouchGestures(bool value);
	void changeTouchSmoothing(int value);
	void changeTwoFingerPinch(int value);
	void changeTwoFingerTap(int value);
	void changeTwoFingerTwist(int value);
	void changeUpdateCheckEnabled(bool value);
	void changeUseMipmaps(bool value);
	void changeUserMarkerPersistence(int value);
	void changeVideoExportCustomFfmpeg(const QString &value);
	void changeVideoExportFfmpegPath(const QString &value);
	void changeVideoExportFormat(int value);
	void changeVideoExportFrameHeight(int value);
	void changeVideoExportFrameRate(int value);
	void changeVideoExportFrameWidth(int value);
	void changeVideoExportSizeChoice(int value);
	void changeWelcomePageShown(bool value);
	void changeWriteLogFile(bool value);
};

}

#endif
