// SPDX-License-Identifier: GPL-3.0-or-later
// This file is auto-generated by configen.py, do not edit it manually.
extern "C" {
#include <dpengine/image.h>
}
#include "cmake-config/config.h"
#include "libclient/config/config.h"
#include "libclient/parentalcontrols/parentalcontrols.h"
#include "libclient/settings.h"
#include "libclient/tools/toolcontroller.h"
#include "libshared/net/messagequeue.h"
#ifdef Q_OS_ANDROID
#	include "libshared/util/androidutils.h"
#endif

namespace config {

Config::Config(QObject *parent)
	: QObject(parent)
{
}

void Config::trySubmit()
{
	if(!submit()) {
		qWarning("Error submitting config");
	}
}

int Config::defaultActionBar()
{
	return 1;
}

int Config::defaultActionBarLocation()
{
	return 3;
}

int Config::defaultAlphaLockCursor()
{
	return int(view::Cursor::SameAsBrush);
}

#if defined(KRITA_QATTRIBUTE_ANDROID_EMULATE_MOUSE_BUTTONS_FOR_PAGE_UP_DOWN)
bool Config::defaultAndroidWorkaroundEmulateMouseButtonsForPageUpDown()
{
#	if defined(Q_OS_ANDROID)
	return utils::androidLooksLikeXiaomiDevice();
#	else
	return false;
#	endif
}
#endif

#if defined(KRITA_QATTRIBUTE_ANDROID_IGNORE_HISTORIC_TABLET_EVENTS)
bool Config::defaultAndroidWorkaroundIgnoreHistoricTabletEvents()
{
#	if defined(Q_OS_ANDROID)
	return utils::androidLooksLikeXiaomiDevice();
#	else
	return false;
#	endif
}
#endif

int Config::defaultAnimationExportFormat()
{
	return -1;
}

bool Config::defaultAutoRecordHost()
{
	return false;
}

bool Config::defaultAutoRecordJoin()
{
	return false;
}

int Config::defaultAutoRecordMetadataIntervalMinutes()
{
	return 4;
}

int Config::defaultAutoRecordSnapshotIntervalMinutes()
{
	return 10;
}

int Config::defaultAutomaticAlphaPreserve()
{
	return 1;
}

int Config::defaultBrushCursor()
{
	return int(view::Cursor::TriangleRight);
}

double Config::defaultBrushOutlineWidth()
{
	return 1.0;
}

bool Config::defaultBrushPresetsAttach()
{
	return true;
}

int Config::defaultBrushSlotCount()
{
	return 5;
}

bool Config::defaultCancelDeselects()
{
	return true;
}

bool Config::defaultCanvasScrollBars()
{
	return true;
}

QVariantMap Config::defaultCanvasShortcuts()
{
	return QVariantMap();
}

QColor Config::defaultCanvasViewBackgroundColor()
{
	return QColor(100, 100, 100);
}

#if defined(Q_OS_ANDROID)
bool Config::defaultCaptureVolumeRocker()
{
	return true;
}
#endif

QColor Config::defaultCheckerColor1()
{
	return QColor(100, 100, 100);
}

QColor Config::defaultCheckerColor2()
{
	return QColor(135, 135, 135);
}

int Config::defaultColorCircleGamutMaskAngle()
{
	return 0;
}

double Config::defaultColorCircleGamutMaskOpacity()
{
	return 0.75;
}

QString Config::defaultColorCircleGamutMaskPath()
{
	return QString();
}

int Config::defaultColorCircleHueAngle()
{
	return 0;
}

int Config::defaultColorCircleHueCount()
{
	return 16;
}

bool Config::defaultColorCircleHueLimit()
{
	return false;
}

int Config::defaultColorCircleSaturationCount()
{
	return 8;
}

bool Config::defaultColorCircleSaturationLimit()
{
	return false;
}

int Config::defaultColorCircleValueCount()
{
	return 10;
}

bool Config::defaultColorCircleValueLimit()
{
	return false;
}

int Config::defaultColorShadesBorderThickness()
{
	return 1;
}

int Config::defaultColorShadesColumnCount()
{
	return 11;
}

QVariantList Config::defaultColorShadesConfig()
{
	return QVariantList();
}

bool Config::defaultColorShadesEnabled()
{
	return false;
}

int Config::defaultColorShadesRowHeight()
{
	return 16;
}

int Config::defaultColorSlidersMode()
{
	return 0;
}

bool Config::defaultColorSlidersShowAll()
{
	return false;
}

bool Config::defaultColorSlidersShowInput()
{
	return true;
}

int Config::defaultColorSwatchFlags()
{
	return 0;
}

int Config::defaultColorWheelAlign()
{
	return int(Qt::AlignVCenter);
}

int Config::defaultColorWheelAngle()
{
	return 1 /* color_widgets::ColorWheel::AngleEnum::AngleRotating */;
}

bool Config::defaultColorWheelMirror()
{
	return true;
}

int Config::defaultColorWheelPreview()
{
	return 1;
}

int Config::defaultColorWheelShape()
{
	return 0 /* color_widgets::ColorWheel::ShapeEnum::ShapeTriangle */;
}

int Config::defaultColorWheelSpace()
{
	return 0 /* color_widgets::ColorWheel::ColorSpaceEnum::ColorHSV */;
}

bool Config::defaultCompactChat()
{
	return false;
}

bool Config::defaultConfirmLayerDelete()
{
	return false;
}

#if defined(Q_OS_ANDROID) && defined(DRAWPILE_USE_CONNECT_SERVICE)
bool Config::defaultConnectionNotification()
{
	return false;
}
#endif

QVector<QVariantMap> Config::defaultCurvesPresets()
{
	return QVector<QVariantMap>();
}

int Config::defaultDebounceDelayMs()
{
	return 250;
}

bool Config::defaultDonationLinksEnabled()
{
	return true;
}

bool Config::defaultDoubleTapAltToFocusCanvas()
{
	return true;
}

int Config::defaultEngineFrameRate()
{
	return 60;
}

int Config::defaultEngineSnapshotCount()
{
#if defined(Q_OS_ANDROID) || defined(__EMSCRIPTEN__)
	return 0;
#else
	return 5;
#endif
}

int Config::defaultEngineSnapshotInterval()
{
	return 10;
}

int Config::defaultEngineUndoDepth()
{
	return 60;
}

int Config::defaultEraseCursor()
{
	return int(view::Cursor::SameAsBrush);
}

bool Config::defaultFilterClosed()
{
	return false;
}

bool Config::defaultFilterDuplicates()
{
	return false;
}

bool Config::defaultFilterInactive()
{
	return true;
}

bool Config::defaultFilterLocked()
{
	return false;
}

bool Config::defaultFilterNsfm()
{
	return false;
}

bool Config::defaultFlipbookUpscaling()
{
	return true;
}

QRect Config::defaultFlipbookWindow()
{
	return QRect();
}

int Config::defaultFontSize()
{
	return -1;
}

int Config::defaultFourFingerTap()
{
	return int(view::TouchTapAction::HideDocks);
}

QString Config::defaultGlobalPressureCurve()
{
	return tools::ToolController::globalPressureCurveDefault;
}

QString Config::defaultGlobalPressureCurveEraser()
{
	return tools::ToolController::globalPressureCurveDefault;
}

int Config::defaultGlobalPressureCurveMode()
{
	return 0;
}

bool Config::defaultHostEnableAdvanced()
{
	return false;
}

bool Config::defaultIgnoreCarrierGradeNat()
{
	return false;
}

QVector<QVariantMap> Config::defaultInputPresets()
{
	return QVector<QVariantMap>();
}

bool Config::defaultInsecurePasswordStorage()
{
	return false;
}

int Config::defaultInterfaceMode()
{
#if defined(Q_OS_ANDROID) || defined(__EMSCRIPTEN__)
	return int(view::InterfaceMode::Dynamic);
#else
	return int(view::InterfaceMode::Desktop);
#endif
}

bool Config::defaultInterpolateInputs()
{
	return true;
}

bool Config::defaultInviteIncludePassword()
{
	return true;
}

int Config::defaultKineticScrollGesture()
{
#if defined(Q_OS_ANDROID) || defined(__EMSCRIPTEN__)
	return int(view::KineticScrollGesture::LeftClick);
#else
	return int(view::KineticScrollGesture::None);
#endif
}

bool Config::defaultKineticScrollHideBars()
{
	return false;
}

int Config::defaultKineticScrollThreshold()
{
	return 10;
}

QString Config::defaultLanguage()
{
	return QString();
}

bool Config::defaultLastAnnounce()
{
	return false;
}

QString Config::defaultLastAvatar()
{
	return QString();
}

int Config::defaultLastBrowseSortColumn()
{
	return -1;
}

int Config::defaultLastBrowseSortDirection()
{
	return 0;
}

QString Config::defaultLastFileOpenPath()
{
	return QString();
}

QVariantMap Config::defaultLastFileOpenPaths()
{
	return QVariantMap();
}

int Config::defaultLastHostServer()
{
	return -1;
}

int Config::defaultLastHostType()
{
	return 0;
}

QString Config::defaultLastIdAlias()
{
	return QString();
}

QString Config::defaultLastJoinAddress()
{
	return QString();
}

bool Config::defaultLastKeepChat()
{
	return false;
}

QStringList Config::defaultLastListingUrls()
{
	return QStringList();
}

bool Config::defaultLastNsfm()
{
	return false;
}

int Config::defaultLastPalette()
{
	return 0;
}

QByteArray Config::defaultLastSessionAuthList()
{
	return QByteArray();
}

bool Config::defaultLastSessionAutomatic()
{
	return true;
}

QByteArray Config::defaultLastSessionBanList()
{
	return QByteArray();
}

QString Config::defaultLastSessionOpPassword()
{
	return QString();
}

QString Config::defaultLastSessionPassword()
{
	return QString();
}

QVariantMap Config::defaultLastSessionPermissions()
{
	return QVariantMap();
}

QString Config::defaultLastSessionTitle()
{
	return QString();
}

int Config::defaultLastSessionUndoDepth()
{
	return 60;
}

QString Config::defaultLastStartDialogDateTime()
{
	return QString();
}

int Config::defaultLastStartDialogPage()
{
	return -1;
}

QSize Config::defaultLastStartDialogSize()
{
	return QSize();
}

int Config::defaultLastTool()
{
	return int(tools::Tool::Type::FREEHAND);
}

QColor Config::defaultLastToolBackgroundColor()
{
	return QColor(Qt::white);
}

QColor Config::defaultLastToolColor()
{
	return QColor(Qt::black);
}

QString Config::defaultLastUsername()
{
	return QString();
}

QMap<QString, bool> Config::defaultLastWindowActions()
{
	return QMap<QString, bool>();
}

QVariantMap Config::defaultLastWindowDocks()
{
	return QVariantMap();
}

bool Config::defaultLastWindowMaximized()
{
	return true;
}

QPoint Config::defaultLastWindowPosition()
{
	return QPoint();
}

QSize Config::defaultLastWindowSize()
{
	return QSize(800, 600);
}

QByteArray Config::defaultLastWindowState()
{
	return QByteArray();
}

QByteArray Config::defaultLastWindowViewState()
{
	return QByteArray();
}

int Config::defaultLayerSketchOpacityPercent()
{
	return 75;
}

QColor Config::defaultLayerSketchTint()
{
	return QColor(62, 140, 236);
}

QVector<QVariantMap> Config::defaultLayouts()
{
	return QVector<QVariantMap>();
}

int Config::defaultLayoutsVersion()
{
	return 0;
}

bool Config::defaultLeftyMode()
{
	return false;
}

QVector<QVariantMap> Config::defaultListServers()
{
	return QVector<QVariantMap>();
}

bool Config::defaultLongPressEnabled()
{
#if defined(Q_OS_ANDROID) || defined(__EMSCRIPTEN__)
	return true;
#else
	return false;
#endif
}

bool Config::defaultMentionEnabled()
{
	return true;
}

QString Config::defaultMentionTriggerList()
{
	return QString();
}

int Config::defaultMessageQueueDrainRate()
{
	return net::MessageQueue::DEFAULT_SMOOTH_DRAIN_RATE;
}

bool Config::defaultMouseSmoothing()
{
	return false;
}

#if defined(NATIVE_DIALOGS_SETTING_AVAILABLE)
bool Config::defaultNativeDialogs()
{
	return true;
}
#endif

bool Config::defaultNavigatorRealtime()
{
	return false;
}

bool Config::defaultNavigatorShowCursors()
{
	return true;
}

int Config::defaultNetworkProxyMode()
{
	return 0;
}

QColor Config::defaultNewCanvasBackColor()
{
	return QColor(Qt::white);
}

QSize Config::defaultNewCanvasSize()
{
	return QSize(2000, 2000);
}

bool Config::defaultNotifFlashChat()
{
	return true;
}

bool Config::defaultNotifFlashDisconnect()
{
	return true;
}

bool Config::defaultNotifFlashLock()
{
	return false;
}

bool Config::defaultNotifFlashLogin()
{
	return false;
}

bool Config::defaultNotifFlashLogout()
{
	return false;
}

bool Config::defaultNotifFlashPrivateChat()
{
	return true;
}

bool Config::defaultNotifFlashUnlock()
{
	return false;
}

bool Config::defaultNotifPopupChat()
{
	return false;
}

bool Config::defaultNotifPopupDisconnect()
{
	return true;
}

bool Config::defaultNotifPopupLock()
{
	return false;
}

bool Config::defaultNotifPopupLogin()
{
	return true;
}

bool Config::defaultNotifPopupLogout()
{
	return true;
}

bool Config::defaultNotifPopupPrivateChat()
{
	return false;
}

bool Config::defaultNotifPopupUnlock()
{
	return false;
}

bool Config::defaultNotifSoundChat()
{
	return true;
}

bool Config::defaultNotifSoundDisconnect()
{
	return true;
}

bool Config::defaultNotifSoundLock()
{
	return true;
}

bool Config::defaultNotifSoundLogin()
{
	return true;
}

bool Config::defaultNotifSoundLogout()
{
	return true;
}

bool Config::defaultNotifSoundPrivateChat()
{
	return true;
}

bool Config::defaultNotifSoundUnlock()
{
	return true;
}

int Config::defaultOneFingerTap()
{
	return int(view::TouchTapAction::Nothing);
}

int Config::defaultOneFingerTapAndHold()
{
	return int(view::TouchTapAndHoldAction::ColorPickMode);
}

int Config::defaultOneFingerTouch()
{
	return int(ONE_FINGER_TOUCH_DEFAULT);
}

int Config::defaultOnionSkinsFrameCount()
{
	return 8;
}

QMap<int, int> Config::defaultOnionSkinsFrames()
{
	return QMap<int, int>();
}

QColor Config::defaultOnionSkinsTintAbove()
{
	return QColor(51, 51, 255, 128);
}

QColor Config::defaultOnionSkinsTintBelow()
{
	return QColor(255, 51, 51, 128);
}

bool Config::defaultOnionSkinsWrap()
{
	return true;
}

bool Config::defaultOverrideFontSize()
{
#if defined(Q_OS_ANDROID) || defined(__EMSCRIPTEN__)
	return true;
#else
	return false;
#endif
}

bool Config::defaultParentalControlsAutoTag()
{
	return true;
}

bool Config::defaultParentalControlsForceCensor()
{
	return false;
}

bool Config::defaultParentalControlsHideLocked()
{
	return false;
}

int Config::defaultParentalControlsLevel()
{
	return int(parentalcontrols::Level::Unrestricted);
}

QByteArray Config::defaultParentalControlsLocked()
{
	return QByteArray();
}

QString Config::defaultParentalControlsTags()
{
	return parentalcontrols::defaultWordList();
}

QString Config::defaultPreferredExportFormat()
{
	return QString();
}

QString Config::defaultPreferredSaveFormat()
{
	return QString();
}

bool Config::defaultPromptLayerCreate()
{
	return false;
}

#if defined(Q_OS_MACOS)
bool Config::defaultQuitOnLastWindowClosed()
{
	return true;
}
#endif

QStringList Config::defaultRecentFiles()
{
	return QStringList();
}

QStringList Config::defaultRecentHosts()
{
	return QStringList();
}

QStringList Config::defaultRecentRemoteHosts()
{
	return QStringList();
}

int Config::defaultRenderCanvas()
{
	return int(view::CanvasImplementation::Default);
}

bool Config::defaultRenderSmooth()
{
	return true;
}

bool Config::defaultRenderUpdateFull()
{
	return false;
}

int Config::defaultSamplingRingVisibility()
{
	return int(view::SamplingRingVisibility::Always);
}

QColor Config::defaultSelectionColor()
{
	return QColor(0, 170, 255);
}

bool Config::defaultServerAutoReset()
{
	return true;
}

bool Config::defaultServerHideIp()
{
	return false;
}

int Config::defaultServerPort()
{
	return cmake_config::proto::port();
}

int Config::defaultServerTimeout()
{
	return 60;
}

bool Config::defaultShareBrushSlotColor()
{
	return false;
}

QVariantMap Config::defaultShortcuts()
{
	return QVariantMap();
}

bool Config::defaultShowInviteDialogOnHost()
{
	return true;
}

bool Config::defaultShowNsfmWarningOnJoin()
{
	return true;
}

bool Config::defaultShowTransformNotices()
{
	return true;
}

bool Config::defaultShowTrayIcon()
{
	return true;
}

bool Config::defaultShowViewModeNotices()
{
	return true;
}

int Config::defaultSmoothing()
{
	return tools::ToolController::DEFAULT_SMOOTHING;
}

int Config::defaultSoundVolume()
{
	return 60;
}

int Config::defaultTabletDriver()
{
	return int(tools::TabletInputMode::KisTabletWinink);
}

int Config::defaultTabletEraserAction()
{
	return int(tools::EraserAction::Default);
}

bool Config::defaultTabletEvents()
{
	return true;
}

int Config::defaultTabletPressTimerDelay()
{
	return 500;
}

bool Config::defaultTemporaryToolSwitch()
{
	return true;
}

int Config::defaultTemporaryToolSwitchMs()
{
	return 250;
}

QString Config::defaultThemePalette()
{
	return QStringLiteral("kritadark.colors");
}

QString Config::defaultThemeStyle()
{
	return QStringLiteral("Fusion");
}

int Config::defaultThreeFingerTap()
{
	return int(view::TouchTapAction::Redo);
}

QColor Config::defaultTimelapseBackdropColor()
{
	return QColor(Qt::transparent);
}

int Config::defaultTimelapseDurationSeconds()
{
	return 120;
}

int Config::defaultTimelapseExportFormat()
{
	return -1;
}

QColor Config::defaultTimelapseFlashColor()
{
	return QColor(Qt::white);
}

int Config::defaultTimelapseFlashSeconds()
{
	return 1;
}

double Config::defaultTimelapseFramerate()
{
	return 24.0;
}

int Config::defaultTimelapseInterpolation()
{
	return int(DP_IMAGE_SCALE_INTERPOLATION_GUESS);
}

int Config::defaultTimelapseLingerAfterSeconds()
{
	return 3;
}

int Config::defaultTimelapseLingerBeforeSeconds()
{
	return 1;
}

int Config::defaultTimelapseLogoLocation()
{
	return -1;
}

double Config::defaultTimelapseLogoOffset()
{
	return 0.05;
}

int Config::defaultTimelapseLogoOpacity()
{
	return 40;
}

double Config::defaultTimelapseLogoScale()
{
	return 0.204;
}

double Config::defaultTimelapseMaxDeltaSeconds()
{
	return 0.1;
}

int Config::defaultTimelapseMaxQueueEntries()
{
	return 8;
}

bool Config::defaultTimelapseShowAdvanced()
{
	return false;
}

bool Config::defaultTimelapseTimeOwnOnly()
{
	return false;
}

QVariantHash Config::defaultToolBarConfig()
{
	return QVariantHash();
}

bool Config::defaultToolToggle()
{
	return true;
}

QMap<QString, QVariantHash> Config::defaultToolset()
{
	return QMap<QString, QVariantHash>();
}

bool Config::defaultTouchDrawPressure()
{
	return false;
}

bool Config::defaultTouchGestures()
{
	return false;
}

int Config::defaultTouchSmoothing()
{
	return 75;
}

int Config::defaultTwoFingerPinch()
{
	return int(view::TwoFingerPinchAction::Zoom);
}

int Config::defaultTwoFingerTap()
{
	return int(view::TouchTapAction::Undo);
}

int Config::defaultTwoFingerTwist()
{
	return int(view::TwoFingerTwistAction::Rotate);
}

bool Config::defaultUpdateCheckEnabled()
{
#if DISABLE_UPDATE_CHECK_DEFAULT
	return false;
#else
	return true;
#endif
}

bool Config::defaultUseMipmaps()
{
	return false;
}

int Config::defaultUserMarkerPersistence()
{
	return 1000;
}

QString Config::defaultVideoExportCustomFfmpeg()
{
	return QString();
}

QString Config::defaultVideoExportFfmpegPath()
{
	return QString("ffmpeg");
}

int Config::defaultVideoExportFormat()
{
	return 0 /* VideoExporter::Format::IMAGE_SERIES */;
}

int Config::defaultVideoExportFrameHeight()
{
	return 720;
}

int Config::defaultVideoExportFrameRate()
{
	return 30;
}

int Config::defaultVideoExportFrameWidth()
{
	return 1280;
}

int Config::defaultVideoExportSizeChoice()
{
	return 0;
}

bool Config::defaultWelcomePageShown()
{
	return false;
}

bool Config::defaultWriteLogFile()
{
	return false;
}

}
