// SPDX-License-Identifier: GPL-3.0-or-later
// This file is auto-generated by configen.py, do not edit it manually.
#include "libclient/config/memoryconfig.h"

namespace config {

MemoryConfig::MemoryConfig(QObject *parent)
	: Config(parent)
{
}

QString MemoryConfig::path() const
{
	return QString(); // In-memory configuration is stored nowhere.
}

bool MemoryConfig::submit()
{
	return true; // Nothing to do for an in-memory configuration.
}

int MemoryConfig::getActionBar() const
{
	return m_actionBar;
}

void MemoryConfig::setActionBar(int value)
{
	if(value != m_actionBar) {
		m_actionBar = value;
		Q_EMIT changeActionBar(m_actionBar);
	}
}

int MemoryConfig::getActionBarLocation() const
{
	return m_actionBarLocation;
}

void MemoryConfig::setActionBarLocation(int value)
{
	if(value != m_actionBarLocation) {
		m_actionBarLocation = value;
		Q_EMIT changeActionBarLocation(m_actionBarLocation);
	}
}

int MemoryConfig::getAlphaLockCursor() const
{
	return m_alphaLockCursor;
}

void MemoryConfig::setAlphaLockCursor(int value)
{
	if(value != m_alphaLockCursor) {
		m_alphaLockCursor = value;
		Q_EMIT changeAlphaLockCursor(m_alphaLockCursor);
	}
}

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
bool MemoryConfig::getAndroidScalingAskOnStartup() const
{
	return m_androidScalingAskOnStartup;
}

void MemoryConfig::setAndroidScalingAskOnStartup(bool value)
{
	if(value != m_androidScalingAskOnStartup) {
		m_androidScalingAskOnStartup = value;
		Q_EMIT changeAndroidScalingAskOnStartup(m_androidScalingAskOnStartup);
	}
}
#endif

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
double MemoryConfig::getAndroidScalingLastInitialScale() const
{
	return m_androidScalingLastInitialScale;
}

void MemoryConfig::setAndroidScalingLastInitialScale(double value)
{
	if(value != m_androidScalingLastInitialScale) {
		m_androidScalingLastInitialScale = value;
		Q_EMIT changeAndroidScalingLastInitialScale(
			m_androidScalingLastInitialScale);
	}
}
#endif

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
double MemoryConfig::getAndroidScalingTargetScale() const
{
	return m_androidScalingTargetScale;
}

void MemoryConfig::setAndroidScalingTargetScale(double value)
{
	if(value != m_androidScalingTargetScale) {
		m_androidScalingTargetScale = value;
		Q_EMIT changeAndroidScalingTargetScale(m_androidScalingTargetScale);
	}
}
#endif

#if defined(KRITA_QATTRIBUTE_ANDROID_EMULATE_MOUSE_BUTTONS_FOR_PAGE_UP_DOWN)
bool MemoryConfig::getAndroidWorkaroundEmulateMouseButtonsForPageUpDown() const
{
	return m_androidWorkaroundEmulateMouseButtonsForPageUpDown;
}

void MemoryConfig::setAndroidWorkaroundEmulateMouseButtonsForPageUpDown(
	bool value)
{
	if(value != m_androidWorkaroundEmulateMouseButtonsForPageUpDown) {
		m_androidWorkaroundEmulateMouseButtonsForPageUpDown = value;
		Q_EMIT changeAndroidWorkaroundEmulateMouseButtonsForPageUpDown(
			m_androidWorkaroundEmulateMouseButtonsForPageUpDown);
	}
}
#endif

#if defined(KRITA_QATTRIBUTE_ANDROID_IGNORE_HISTORIC_TABLET_EVENTS)
bool MemoryConfig::getAndroidWorkaroundIgnoreHistoricTabletEvents() const
{
	return m_androidWorkaroundIgnoreHistoricTabletEvents;
}

void MemoryConfig::setAndroidWorkaroundIgnoreHistoricTabletEvents(bool value)
{
	if(value != m_androidWorkaroundIgnoreHistoricTabletEvents) {
		m_androidWorkaroundIgnoreHistoricTabletEvents = value;
		Q_EMIT changeAndroidWorkaroundIgnoreHistoricTabletEvents(
			m_androidWorkaroundIgnoreHistoricTabletEvents);
	}
}
#endif

int MemoryConfig::getAnimationExportFormat() const
{
	return m_animationExportFormat;
}

void MemoryConfig::setAnimationExportFormat(int value)
{
	if(value != m_animationExportFormat) {
		m_animationExportFormat = value;
		Q_EMIT changeAnimationExportFormat(m_animationExportFormat);
	}
}

bool MemoryConfig::getAutoRecordHost() const
{
	return m_autoRecordHost;
}

void MemoryConfig::setAutoRecordHost(bool value)
{
	if(value != m_autoRecordHost) {
		m_autoRecordHost = value;
		Q_EMIT changeAutoRecordHost(m_autoRecordHost);
	}
}

bool MemoryConfig::getAutoRecordJoin() const
{
	return m_autoRecordJoin;
}

void MemoryConfig::setAutoRecordJoin(bool value)
{
	if(value != m_autoRecordJoin) {
		m_autoRecordJoin = value;
		Q_EMIT changeAutoRecordJoin(m_autoRecordJoin);
	}
}

int MemoryConfig::getAutoRecordMetadataIntervalMinutes() const
{
	return m_autoRecordMetadataIntervalMinutes;
}

void MemoryConfig::setAutoRecordMetadataIntervalMinutes(int value)
{
	if(value != m_autoRecordMetadataIntervalMinutes) {
		m_autoRecordMetadataIntervalMinutes = value;
		Q_EMIT changeAutoRecordMetadataIntervalMinutes(
			m_autoRecordMetadataIntervalMinutes);
	}
}

int MemoryConfig::getAutoRecordSnapshotIntervalMinutes() const
{
	return m_autoRecordSnapshotIntervalMinutes;
}

void MemoryConfig::setAutoRecordSnapshotIntervalMinutes(int value)
{
	if(value != m_autoRecordSnapshotIntervalMinutes) {
		m_autoRecordSnapshotIntervalMinutes = value;
		Q_EMIT changeAutoRecordSnapshotIntervalMinutes(
			m_autoRecordSnapshotIntervalMinutes);
	}
}

int MemoryConfig::getAutomaticAlphaPreserve() const
{
	return m_automaticAlphaPreserve;
}

void MemoryConfig::setAutomaticAlphaPreserve(int value)
{
	if(value != m_automaticAlphaPreserve) {
		m_automaticAlphaPreserve = value;
		Q_EMIT changeAutomaticAlphaPreserve(m_automaticAlphaPreserve);
	}
}

int MemoryConfig::getBrushCursor() const
{
	return m_brushCursor;
}

void MemoryConfig::setBrushCursor(int value)
{
	if(value != m_brushCursor) {
		m_brushCursor = value;
		Q_EMIT changeBrushCursor(m_brushCursor);
	}
}

double MemoryConfig::getBrushOutlineWidth() const
{
	return m_brushOutlineWidth;
}

void MemoryConfig::setBrushOutlineWidth(double value)
{
	if(value != m_brushOutlineWidth) {
		m_brushOutlineWidth = value;
		Q_EMIT changeBrushOutlineWidth(m_brushOutlineWidth);
	}
}

bool MemoryConfig::getBrushPresetsAttach() const
{
	return m_brushPresetsAttach;
}

void MemoryConfig::setBrushPresetsAttach(bool value)
{
	if(value != m_brushPresetsAttach) {
		m_brushPresetsAttach = value;
		Q_EMIT changeBrushPresetsAttach(m_brushPresetsAttach);
	}
}

int MemoryConfig::getBrushSlotCount() const
{
	return m_brushSlotCount;
}

void MemoryConfig::setBrushSlotCount(int value)
{
	if(value != m_brushSlotCount) {
		m_brushSlotCount = value;
		Q_EMIT changeBrushSlotCount(m_brushSlotCount);
	}
}

bool MemoryConfig::getCancelDeselects() const
{
	return m_cancelDeselects;
}

void MemoryConfig::setCancelDeselects(bool value)
{
	if(value != m_cancelDeselects) {
		m_cancelDeselects = value;
		Q_EMIT changeCancelDeselects(m_cancelDeselects);
	}
}

bool MemoryConfig::getCanvasScrollBars() const
{
	return m_canvasScrollBars;
}

void MemoryConfig::setCanvasScrollBars(bool value)
{
	if(value != m_canvasScrollBars) {
		m_canvasScrollBars = value;
		Q_EMIT changeCanvasScrollBars(m_canvasScrollBars);
	}
}

QVariantMap MemoryConfig::getCanvasShortcuts() const
{
	return m_canvasShortcuts;
}

void MemoryConfig::setCanvasShortcuts(const QVariantMap &value)
{
	if(value != m_canvasShortcuts) {
		m_canvasShortcuts = value;
		Q_EMIT changeCanvasShortcuts(m_canvasShortcuts);
	}
}

QColor MemoryConfig::getCanvasViewBackgroundColor() const
{
	return m_canvasViewBackgroundColor;
}

void MemoryConfig::setCanvasViewBackgroundColor(const QColor &value)
{
	if(value != m_canvasViewBackgroundColor) {
		m_canvasViewBackgroundColor = value;
		Q_EMIT changeCanvasViewBackgroundColor(m_canvasViewBackgroundColor);
	}
}

#if defined(Q_OS_ANDROID)
bool MemoryConfig::getCaptureVolumeRocker() const
{
	return m_captureVolumeRocker;
}

void MemoryConfig::setCaptureVolumeRocker(bool value)
{
	if(value != m_captureVolumeRocker) {
		m_captureVolumeRocker = value;
		Q_EMIT changeCaptureVolumeRocker(m_captureVolumeRocker);
	}
}
#endif

QColor MemoryConfig::getCheckerColor1() const
{
	return m_checkerColor1;
}

void MemoryConfig::setCheckerColor1(const QColor &value)
{
	if(value != m_checkerColor1) {
		m_checkerColor1 = value;
		Q_EMIT changeCheckerColor1(m_checkerColor1);
	}
}

QColor MemoryConfig::getCheckerColor2() const
{
	return m_checkerColor2;
}

void MemoryConfig::setCheckerColor2(const QColor &value)
{
	if(value != m_checkerColor2) {
		m_checkerColor2 = value;
		Q_EMIT changeCheckerColor2(m_checkerColor2);
	}
}

int MemoryConfig::getColorCircleGamutMaskAngle() const
{
	return m_colorCircleGamutMaskAngle;
}

void MemoryConfig::setColorCircleGamutMaskAngle(int value)
{
	if(value != m_colorCircleGamutMaskAngle) {
		m_colorCircleGamutMaskAngle = value;
		Q_EMIT changeColorCircleGamutMaskAngle(m_colorCircleGamutMaskAngle);
	}
}

double MemoryConfig::getColorCircleGamutMaskOpacity() const
{
	return m_colorCircleGamutMaskOpacity;
}

void MemoryConfig::setColorCircleGamutMaskOpacity(double value)
{
	if(value != m_colorCircleGamutMaskOpacity) {
		m_colorCircleGamutMaskOpacity = value;
		Q_EMIT changeColorCircleGamutMaskOpacity(m_colorCircleGamutMaskOpacity);
	}
}

QString MemoryConfig::getColorCircleGamutMaskPath() const
{
	return m_colorCircleGamutMaskPath;
}

void MemoryConfig::setColorCircleGamutMaskPath(const QString &value)
{
	if(value != m_colorCircleGamutMaskPath) {
		m_colorCircleGamutMaskPath = value;
		Q_EMIT changeColorCircleGamutMaskPath(m_colorCircleGamutMaskPath);
	}
}

int MemoryConfig::getColorCircleHueAngle() const
{
	return m_colorCircleHueAngle;
}

void MemoryConfig::setColorCircleHueAngle(int value)
{
	if(value != m_colorCircleHueAngle) {
		m_colorCircleHueAngle = value;
		Q_EMIT changeColorCircleHueAngle(m_colorCircleHueAngle);
	}
}

int MemoryConfig::getColorCircleHueCount() const
{
	return m_colorCircleHueCount;
}

void MemoryConfig::setColorCircleHueCount(int value)
{
	if(value != m_colorCircleHueCount) {
		m_colorCircleHueCount = value;
		Q_EMIT changeColorCircleHueCount(m_colorCircleHueCount);
	}
}

bool MemoryConfig::getColorCircleHueLimit() const
{
	return m_colorCircleHueLimit;
}

void MemoryConfig::setColorCircleHueLimit(bool value)
{
	if(value != m_colorCircleHueLimit) {
		m_colorCircleHueLimit = value;
		Q_EMIT changeColorCircleHueLimit(m_colorCircleHueLimit);
	}
}

int MemoryConfig::getColorCircleSaturationCount() const
{
	return m_colorCircleSaturationCount;
}

void MemoryConfig::setColorCircleSaturationCount(int value)
{
	if(value != m_colorCircleSaturationCount) {
		m_colorCircleSaturationCount = value;
		Q_EMIT changeColorCircleSaturationCount(m_colorCircleSaturationCount);
	}
}

bool MemoryConfig::getColorCircleSaturationLimit() const
{
	return m_colorCircleSaturationLimit;
}

void MemoryConfig::setColorCircleSaturationLimit(bool value)
{
	if(value != m_colorCircleSaturationLimit) {
		m_colorCircleSaturationLimit = value;
		Q_EMIT changeColorCircleSaturationLimit(m_colorCircleSaturationLimit);
	}
}

int MemoryConfig::getColorCircleValueCount() const
{
	return m_colorCircleValueCount;
}

void MemoryConfig::setColorCircleValueCount(int value)
{
	if(value != m_colorCircleValueCount) {
		m_colorCircleValueCount = value;
		Q_EMIT changeColorCircleValueCount(m_colorCircleValueCount);
	}
}

bool MemoryConfig::getColorCircleValueLimit() const
{
	return m_colorCircleValueLimit;
}

void MemoryConfig::setColorCircleValueLimit(bool value)
{
	if(value != m_colorCircleValueLimit) {
		m_colorCircleValueLimit = value;
		Q_EMIT changeColorCircleValueLimit(m_colorCircleValueLimit);
	}
}

int MemoryConfig::getColorShadesBorderThickness() const
{
	return m_colorShadesBorderThickness;
}

void MemoryConfig::setColorShadesBorderThickness(int value)
{
	if(value != m_colorShadesBorderThickness) {
		m_colorShadesBorderThickness = value;
		Q_EMIT changeColorShadesBorderThickness(m_colorShadesBorderThickness);
	}
}

int MemoryConfig::getColorShadesColumnCount() const
{
	return m_colorShadesColumnCount;
}

void MemoryConfig::setColorShadesColumnCount(int value)
{
	if(value != m_colorShadesColumnCount) {
		m_colorShadesColumnCount = value;
		Q_EMIT changeColorShadesColumnCount(m_colorShadesColumnCount);
	}
}

QVariantList MemoryConfig::getColorShadesConfig() const
{
	return m_colorShadesConfig;
}

void MemoryConfig::setColorShadesConfig(const QVariantList &value)
{
	if(value != m_colorShadesConfig) {
		m_colorShadesConfig = value;
		Q_EMIT changeColorShadesConfig(m_colorShadesConfig);
	}
}

bool MemoryConfig::getColorShadesEnabled() const
{
	return m_colorShadesEnabled;
}

void MemoryConfig::setColorShadesEnabled(bool value)
{
	if(value != m_colorShadesEnabled) {
		m_colorShadesEnabled = value;
		Q_EMIT changeColorShadesEnabled(m_colorShadesEnabled);
	}
}

int MemoryConfig::getColorShadesRowHeight() const
{
	return m_colorShadesRowHeight;
}

void MemoryConfig::setColorShadesRowHeight(int value)
{
	if(value != m_colorShadesRowHeight) {
		m_colorShadesRowHeight = value;
		Q_EMIT changeColorShadesRowHeight(m_colorShadesRowHeight);
	}
}

int MemoryConfig::getColorSlidersMode() const
{
	return m_colorSlidersMode;
}

void MemoryConfig::setColorSlidersMode(int value)
{
	if(value != m_colorSlidersMode) {
		m_colorSlidersMode = value;
		Q_EMIT changeColorSlidersMode(m_colorSlidersMode);
	}
}

bool MemoryConfig::getColorSlidersShowAll() const
{
	return m_colorSlidersShowAll;
}

void MemoryConfig::setColorSlidersShowAll(bool value)
{
	if(value != m_colorSlidersShowAll) {
		m_colorSlidersShowAll = value;
		Q_EMIT changeColorSlidersShowAll(m_colorSlidersShowAll);
	}
}

bool MemoryConfig::getColorSlidersShowInput() const
{
	return m_colorSlidersShowInput;
}

void MemoryConfig::setColorSlidersShowInput(bool value)
{
	if(value != m_colorSlidersShowInput) {
		m_colorSlidersShowInput = value;
		Q_EMIT changeColorSlidersShowInput(m_colorSlidersShowInput);
	}
}

int MemoryConfig::getColorSwatchFlags() const
{
	return m_colorSwatchFlags;
}

void MemoryConfig::setColorSwatchFlags(int value)
{
	if(value != m_colorSwatchFlags) {
		m_colorSwatchFlags = value;
		Q_EMIT changeColorSwatchFlags(m_colorSwatchFlags);
	}
}

int MemoryConfig::getColorWheelAlign() const
{
	return m_colorWheelAlign;
}

void MemoryConfig::setColorWheelAlign(int value)
{
	if(value != m_colorWheelAlign) {
		m_colorWheelAlign = value;
		Q_EMIT changeColorWheelAlign(m_colorWheelAlign);
	}
}

int MemoryConfig::getColorWheelAngle() const
{
	return m_colorWheelAngle;
}

void MemoryConfig::setColorWheelAngle(int value)
{
	if(value != m_colorWheelAngle) {
		m_colorWheelAngle = value;
		Q_EMIT changeColorWheelAngle(m_colorWheelAngle);
	}
}

bool MemoryConfig::getColorWheelMirror() const
{
	return m_colorWheelMirror;
}

void MemoryConfig::setColorWheelMirror(bool value)
{
	if(value != m_colorWheelMirror) {
		m_colorWheelMirror = value;
		Q_EMIT changeColorWheelMirror(m_colorWheelMirror);
	}
}

int MemoryConfig::getColorWheelPreview() const
{
	return m_colorWheelPreview;
}

void MemoryConfig::setColorWheelPreview(int value)
{
	if(value != m_colorWheelPreview) {
		m_colorWheelPreview = value;
		Q_EMIT changeColorWheelPreview(m_colorWheelPreview);
	}
}

int MemoryConfig::getColorWheelShape() const
{
	return m_colorWheelShape;
}

void MemoryConfig::setColorWheelShape(int value)
{
	if(value != m_colorWheelShape) {
		m_colorWheelShape = value;
		Q_EMIT changeColorWheelShape(m_colorWheelShape);
	}
}

int MemoryConfig::getColorWheelSpace() const
{
	return m_colorWheelSpace;
}

void MemoryConfig::setColorWheelSpace(int value)
{
	if(value != m_colorWheelSpace) {
		m_colorWheelSpace = value;
		Q_EMIT changeColorWheelSpace(m_colorWheelSpace);
	}
}

bool MemoryConfig::getCompactChat() const
{
	return m_compactChat;
}

void MemoryConfig::setCompactChat(bool value)
{
	if(value != m_compactChat) {
		m_compactChat = value;
		Q_EMIT changeCompactChat(m_compactChat);
	}
}

bool MemoryConfig::getConfirmLayerDelete() const
{
	return m_confirmLayerDelete;
}

void MemoryConfig::setConfirmLayerDelete(bool value)
{
	if(value != m_confirmLayerDelete) {
		m_confirmLayerDelete = value;
		Q_EMIT changeConfirmLayerDelete(m_confirmLayerDelete);
	}
}

#if defined(Q_OS_ANDROID) && defined(DRAWPILE_USE_CONNECT_SERVICE)
bool MemoryConfig::getConnectionNotification() const
{
	return m_connectionNotification;
}

void MemoryConfig::setConnectionNotification(bool value)
{
	if(value != m_connectionNotification) {
		m_connectionNotification = value;
		Q_EMIT changeConnectionNotification(m_connectionNotification);
	}
}
#endif

QVector<QVariantMap> MemoryConfig::getCurvesPresets() const
{
	return m_curvesPresets;
}

void MemoryConfig::setCurvesPresets(const QVector<QVariantMap> &value)
{
	if(value != m_curvesPresets) {
		m_curvesPresets = value;
		Q_EMIT changeCurvesPresets(m_curvesPresets);
	}
}

int MemoryConfig::getDebounceDelayMs() const
{
	return m_debounceDelayMs;
}

void MemoryConfig::setDebounceDelayMs(int value)
{
	if(value != m_debounceDelayMs) {
		m_debounceDelayMs = value;
		Q_EMIT changeDebounceDelayMs(m_debounceDelayMs);
	}
}

bool MemoryConfig::getDonationLinksEnabled() const
{
	return m_donationLinksEnabled;
}

void MemoryConfig::setDonationLinksEnabled(bool value)
{
	if(value != m_donationLinksEnabled) {
		m_donationLinksEnabled = value;
		Q_EMIT changeDonationLinksEnabled(m_donationLinksEnabled);
	}
}

bool MemoryConfig::getDoubleTapAltToFocusCanvas() const
{
	return m_doubleTapAltToFocusCanvas;
}

void MemoryConfig::setDoubleTapAltToFocusCanvas(bool value)
{
	if(value != m_doubleTapAltToFocusCanvas) {
		m_doubleTapAltToFocusCanvas = value;
		Q_EMIT changeDoubleTapAltToFocusCanvas(m_doubleTapAltToFocusCanvas);
	}
}

int MemoryConfig::getEngineFrameRate() const
{
	return m_engineFrameRate;
}

void MemoryConfig::setEngineFrameRate(int value)
{
	if(value != m_engineFrameRate) {
		m_engineFrameRate = value;
		Q_EMIT changeEngineFrameRate(m_engineFrameRate);
	}
}

int MemoryConfig::getEngineSnapshotCount() const
{
	return m_engineSnapshotCount;
}

void MemoryConfig::setEngineSnapshotCount(int value)
{
	if(value != m_engineSnapshotCount) {
		m_engineSnapshotCount = value;
		Q_EMIT changeEngineSnapshotCount(m_engineSnapshotCount);
	}
}

int MemoryConfig::getEngineSnapshotInterval() const
{
	return m_engineSnapshotInterval;
}

void MemoryConfig::setEngineSnapshotInterval(int value)
{
	if(value != m_engineSnapshotInterval) {
		m_engineSnapshotInterval = value;
		Q_EMIT changeEngineSnapshotInterval(m_engineSnapshotInterval);
	}
}

int MemoryConfig::getEngineUndoDepth() const
{
	return m_engineUndoDepth;
}

void MemoryConfig::setEngineUndoDepth(int value)
{
	if(value != m_engineUndoDepth) {
		m_engineUndoDepth = value;
		Q_EMIT changeEngineUndoDepth(m_engineUndoDepth);
	}
}

int MemoryConfig::getEraseCursor() const
{
	return m_eraseCursor;
}

void MemoryConfig::setEraseCursor(int value)
{
	if(value != m_eraseCursor) {
		m_eraseCursor = value;
		Q_EMIT changeEraseCursor(m_eraseCursor);
	}
}

bool MemoryConfig::getFilterClosed() const
{
	return m_filterClosed;
}

void MemoryConfig::setFilterClosed(bool value)
{
	if(value != m_filterClosed) {
		m_filterClosed = value;
		Q_EMIT changeFilterClosed(m_filterClosed);
	}
}

bool MemoryConfig::getFilterDuplicates() const
{
	return m_filterDuplicates;
}

void MemoryConfig::setFilterDuplicates(bool value)
{
	if(value != m_filterDuplicates) {
		m_filterDuplicates = value;
		Q_EMIT changeFilterDuplicates(m_filterDuplicates);
	}
}

bool MemoryConfig::getFilterInactive() const
{
	return m_filterInactive;
}

void MemoryConfig::setFilterInactive(bool value)
{
	if(value != m_filterInactive) {
		m_filterInactive = value;
		Q_EMIT changeFilterInactive(m_filterInactive);
	}
}

bool MemoryConfig::getFilterLocked() const
{
	return m_filterLocked;
}

void MemoryConfig::setFilterLocked(bool value)
{
	if(value != m_filterLocked) {
		m_filterLocked = value;
		Q_EMIT changeFilterLocked(m_filterLocked);
	}
}

bool MemoryConfig::getFilterNsfm() const
{
	return m_filterNsfm;
}

void MemoryConfig::setFilterNsfm(bool value)
{
	if(value != m_filterNsfm) {
		m_filterNsfm = value;
		Q_EMIT changeFilterNsfm(m_filterNsfm);
	}
}

bool MemoryConfig::getFlipbookUpscaling() const
{
	return m_flipbookUpscaling;
}

void MemoryConfig::setFlipbookUpscaling(bool value)
{
	if(value != m_flipbookUpscaling) {
		m_flipbookUpscaling = value;
		Q_EMIT changeFlipbookUpscaling(m_flipbookUpscaling);
	}
}

QRect MemoryConfig::getFlipbookWindow() const
{
	return m_flipbookWindow;
}

void MemoryConfig::setFlipbookWindow(const QRect &value)
{
	if(value != m_flipbookWindow) {
		m_flipbookWindow = value;
		Q_EMIT changeFlipbookWindow(m_flipbookWindow);
	}
}

int MemoryConfig::getFontSize() const
{
	return m_fontSize;
}

void MemoryConfig::setFontSize(int value)
{
	if(value != m_fontSize) {
		m_fontSize = value;
		Q_EMIT changeFontSize(m_fontSize);
	}
}

int MemoryConfig::getFourFingerTap() const
{
	return m_fourFingerTap;
}

void MemoryConfig::setFourFingerTap(int value)
{
	if(value != m_fourFingerTap) {
		m_fourFingerTap = value;
		Q_EMIT changeFourFingerTap(m_fourFingerTap);
	}
}

QString MemoryConfig::getGlobalPressureCurve() const
{
	return m_globalPressureCurve;
}

void MemoryConfig::setGlobalPressureCurve(const QString &value)
{
	if(value != m_globalPressureCurve) {
		m_globalPressureCurve = value;
		Q_EMIT changeGlobalPressureCurve(m_globalPressureCurve);
	}
}

QString MemoryConfig::getGlobalPressureCurveEraser() const
{
	return m_globalPressureCurveEraser;
}

void MemoryConfig::setGlobalPressureCurveEraser(const QString &value)
{
	if(value != m_globalPressureCurveEraser) {
		m_globalPressureCurveEraser = value;
		Q_EMIT changeGlobalPressureCurveEraser(m_globalPressureCurveEraser);
	}
}

int MemoryConfig::getGlobalPressureCurveMode() const
{
	return m_globalPressureCurveMode;
}

void MemoryConfig::setGlobalPressureCurveMode(int value)
{
	if(value != m_globalPressureCurveMode) {
		m_globalPressureCurveMode = value;
		Q_EMIT changeGlobalPressureCurveMode(m_globalPressureCurveMode);
	}
}

bool MemoryConfig::getHostEnableAdvanced() const
{
	return m_hostEnableAdvanced;
}

void MemoryConfig::setHostEnableAdvanced(bool value)
{
	if(value != m_hostEnableAdvanced) {
		m_hostEnableAdvanced = value;
		Q_EMIT changeHostEnableAdvanced(m_hostEnableAdvanced);
	}
}

bool MemoryConfig::getIgnoreCarrierGradeNat() const
{
	return m_ignoreCarrierGradeNat;
}

void MemoryConfig::setIgnoreCarrierGradeNat(bool value)
{
	if(value != m_ignoreCarrierGradeNat) {
		m_ignoreCarrierGradeNat = value;
		Q_EMIT changeIgnoreCarrierGradeNat(m_ignoreCarrierGradeNat);
	}
}

QVector<QVariantMap> MemoryConfig::getInputPresets() const
{
	return m_inputPresets;
}

void MemoryConfig::setInputPresets(const QVector<QVariantMap> &value)
{
	if(value != m_inputPresets) {
		m_inputPresets = value;
		Q_EMIT changeInputPresets(m_inputPresets);
	}
}

bool MemoryConfig::getInsecurePasswordStorage() const
{
	return m_insecurePasswordStorage;
}

void MemoryConfig::setInsecurePasswordStorage(bool value)
{
	if(value != m_insecurePasswordStorage) {
		m_insecurePasswordStorage = value;
		Q_EMIT changeInsecurePasswordStorage(m_insecurePasswordStorage);
	}
}

int MemoryConfig::getInterfaceMode() const
{
	return m_interfaceMode;
}

void MemoryConfig::setInterfaceMode(int value)
{
	if(value != m_interfaceMode) {
		m_interfaceMode = value;
		Q_EMIT changeInterfaceMode(m_interfaceMode);
	}
}

bool MemoryConfig::getInterpolateInputs() const
{
	return m_interpolateInputs;
}

void MemoryConfig::setInterpolateInputs(bool value)
{
	if(value != m_interpolateInputs) {
		m_interpolateInputs = value;
		Q_EMIT changeInterpolateInputs(m_interpolateInputs);
	}
}

bool MemoryConfig::getInviteIncludePassword() const
{
	return m_inviteIncludePassword;
}

void MemoryConfig::setInviteIncludePassword(bool value)
{
	if(value != m_inviteIncludePassword) {
		m_inviteIncludePassword = value;
		Q_EMIT changeInviteIncludePassword(m_inviteIncludePassword);
	}
}

int MemoryConfig::getKineticScrollGesture() const
{
	return m_kineticScrollGesture;
}

void MemoryConfig::setKineticScrollGesture(int value)
{
	if(value != m_kineticScrollGesture) {
		m_kineticScrollGesture = value;
		Q_EMIT changeKineticScrollGesture(m_kineticScrollGesture);
	}
}

bool MemoryConfig::getKineticScrollHideBars() const
{
	return m_kineticScrollHideBars;
}

void MemoryConfig::setKineticScrollHideBars(bool value)
{
	if(value != m_kineticScrollHideBars) {
		m_kineticScrollHideBars = value;
		Q_EMIT changeKineticScrollHideBars(m_kineticScrollHideBars);
	}
}

int MemoryConfig::getKineticScrollThreshold() const
{
	return m_kineticScrollThreshold;
}

void MemoryConfig::setKineticScrollThreshold(int value)
{
	if(value != m_kineticScrollThreshold) {
		m_kineticScrollThreshold = value;
		Q_EMIT changeKineticScrollThreshold(m_kineticScrollThreshold);
	}
}

QString MemoryConfig::getLanguage() const
{
	return m_language;
}

void MemoryConfig::setLanguage(const QString &value)
{
	if(value != m_language) {
		m_language = value;
		Q_EMIT changeLanguage(m_language);
	}
}

bool MemoryConfig::getLastAnnounce() const
{
	return m_lastAnnounce;
}

void MemoryConfig::setLastAnnounce(bool value)
{
	if(value != m_lastAnnounce) {
		m_lastAnnounce = value;
		Q_EMIT changeLastAnnounce(m_lastAnnounce);
	}
}

QString MemoryConfig::getLastAvatar() const
{
	return m_lastAvatar;
}

void MemoryConfig::setLastAvatar(const QString &value)
{
	if(value != m_lastAvatar) {
		m_lastAvatar = value;
		Q_EMIT changeLastAvatar(m_lastAvatar);
	}
}

int MemoryConfig::getLastBrowseSortColumn() const
{
	return m_lastBrowseSortColumn;
}

void MemoryConfig::setLastBrowseSortColumn(int value)
{
	if(value != m_lastBrowseSortColumn) {
		m_lastBrowseSortColumn = value;
		Q_EMIT changeLastBrowseSortColumn(m_lastBrowseSortColumn);
	}
}

int MemoryConfig::getLastBrowseSortDirection() const
{
	return m_lastBrowseSortDirection;
}

void MemoryConfig::setLastBrowseSortDirection(int value)
{
	if(value != m_lastBrowseSortDirection) {
		m_lastBrowseSortDirection = value;
		Q_EMIT changeLastBrowseSortDirection(m_lastBrowseSortDirection);
	}
}

QString MemoryConfig::getLastFileOpenPath() const
{
	return m_lastFileOpenPath;
}

void MemoryConfig::setLastFileOpenPath(const QString &value)
{
	if(value != m_lastFileOpenPath) {
		m_lastFileOpenPath = value;
		Q_EMIT changeLastFileOpenPath(m_lastFileOpenPath);
	}
}

QVariantMap MemoryConfig::getLastFileOpenPaths() const
{
	return m_lastFileOpenPaths;
}

void MemoryConfig::setLastFileOpenPaths(const QVariantMap &value)
{
	if(value != m_lastFileOpenPaths) {
		m_lastFileOpenPaths = value;
		Q_EMIT changeLastFileOpenPaths(m_lastFileOpenPaths);
	}
}

int MemoryConfig::getLastHostServer() const
{
	return m_lastHostServer;
}

void MemoryConfig::setLastHostServer(int value)
{
	if(value != m_lastHostServer) {
		m_lastHostServer = value;
		Q_EMIT changeLastHostServer(m_lastHostServer);
	}
}

int MemoryConfig::getLastHostType() const
{
	return m_lastHostType;
}

void MemoryConfig::setLastHostType(int value)
{
	if(value != m_lastHostType) {
		m_lastHostType = value;
		Q_EMIT changeLastHostType(m_lastHostType);
	}
}

QString MemoryConfig::getLastIdAlias() const
{
	return m_lastIdAlias;
}

void MemoryConfig::setLastIdAlias(const QString &value)
{
	if(value != m_lastIdAlias) {
		m_lastIdAlias = value;
		Q_EMIT changeLastIdAlias(m_lastIdAlias);
	}
}

QString MemoryConfig::getLastJoinAddress() const
{
	return m_lastJoinAddress;
}

void MemoryConfig::setLastJoinAddress(const QString &value)
{
	if(value != m_lastJoinAddress) {
		m_lastJoinAddress = value;
		Q_EMIT changeLastJoinAddress(m_lastJoinAddress);
	}
}

bool MemoryConfig::getLastKeepChat() const
{
	return m_lastKeepChat;
}

void MemoryConfig::setLastKeepChat(bool value)
{
	if(value != m_lastKeepChat) {
		m_lastKeepChat = value;
		Q_EMIT changeLastKeepChat(m_lastKeepChat);
	}
}

QStringList MemoryConfig::getLastListingUrls() const
{
	return m_lastListingUrls;
}

void MemoryConfig::setLastListingUrls(const QStringList &value)
{
	if(value != m_lastListingUrls) {
		m_lastListingUrls = value;
		Q_EMIT changeLastListingUrls(m_lastListingUrls);
	}
}

bool MemoryConfig::getLastNsfm() const
{
	return m_lastNsfm;
}

void MemoryConfig::setLastNsfm(bool value)
{
	if(value != m_lastNsfm) {
		m_lastNsfm = value;
		Q_EMIT changeLastNsfm(m_lastNsfm);
	}
}

int MemoryConfig::getLastPalette() const
{
	return m_lastPalette;
}

void MemoryConfig::setLastPalette(int value)
{
	if(value != m_lastPalette) {
		m_lastPalette = value;
		Q_EMIT changeLastPalette(m_lastPalette);
	}
}

QByteArray MemoryConfig::getLastSessionAuthList() const
{
	return m_lastSessionAuthList;
}

void MemoryConfig::setLastSessionAuthList(const QByteArray &value)
{
	if(value != m_lastSessionAuthList) {
		m_lastSessionAuthList = value;
		Q_EMIT changeLastSessionAuthList(m_lastSessionAuthList);
	}
}

bool MemoryConfig::getLastSessionAutomatic() const
{
	return m_lastSessionAutomatic;
}

void MemoryConfig::setLastSessionAutomatic(bool value)
{
	if(value != m_lastSessionAutomatic) {
		m_lastSessionAutomatic = value;
		Q_EMIT changeLastSessionAutomatic(m_lastSessionAutomatic);
	}
}

QByteArray MemoryConfig::getLastSessionBanList() const
{
	return m_lastSessionBanList;
}

void MemoryConfig::setLastSessionBanList(const QByteArray &value)
{
	if(value != m_lastSessionBanList) {
		m_lastSessionBanList = value;
		Q_EMIT changeLastSessionBanList(m_lastSessionBanList);
	}
}

QString MemoryConfig::getLastSessionOpPassword() const
{
	return m_lastSessionOpPassword;
}

void MemoryConfig::setLastSessionOpPassword(const QString &value)
{
	if(value != m_lastSessionOpPassword) {
		m_lastSessionOpPassword = value;
		Q_EMIT changeLastSessionOpPassword(m_lastSessionOpPassword);
	}
}

QString MemoryConfig::getLastSessionPassword() const
{
	return m_lastSessionPassword;
}

void MemoryConfig::setLastSessionPassword(const QString &value)
{
	if(value != m_lastSessionPassword) {
		m_lastSessionPassword = value;
		Q_EMIT changeLastSessionPassword(m_lastSessionPassword);
	}
}

QVariantMap MemoryConfig::getLastSessionPermissions() const
{
	return m_lastSessionPermissions;
}

void MemoryConfig::setLastSessionPermissions(const QVariantMap &value)
{
	if(value != m_lastSessionPermissions) {
		m_lastSessionPermissions = value;
		Q_EMIT changeLastSessionPermissions(m_lastSessionPermissions);
	}
}

QString MemoryConfig::getLastSessionTitle() const
{
	return m_lastSessionTitle;
}

void MemoryConfig::setLastSessionTitle(const QString &value)
{
	if(value != m_lastSessionTitle) {
		m_lastSessionTitle = value;
		Q_EMIT changeLastSessionTitle(m_lastSessionTitle);
	}
}

int MemoryConfig::getLastSessionUndoDepth() const
{
	return m_lastSessionUndoDepth;
}

void MemoryConfig::setLastSessionUndoDepth(int value)
{
	if(value != m_lastSessionUndoDepth) {
		m_lastSessionUndoDepth = value;
		Q_EMIT changeLastSessionUndoDepth(m_lastSessionUndoDepth);
	}
}

QString MemoryConfig::getLastStartDialogDateTime() const
{
	return m_lastStartDialogDateTime;
}

void MemoryConfig::setLastStartDialogDateTime(const QString &value)
{
	if(value != m_lastStartDialogDateTime) {
		m_lastStartDialogDateTime = value;
		Q_EMIT changeLastStartDialogDateTime(m_lastStartDialogDateTime);
	}
}

int MemoryConfig::getLastStartDialogPage() const
{
	return m_lastStartDialogPage;
}

void MemoryConfig::setLastStartDialogPage(int value)
{
	if(value != m_lastStartDialogPage) {
		m_lastStartDialogPage = value;
		Q_EMIT changeLastStartDialogPage(m_lastStartDialogPage);
	}
}

QSize MemoryConfig::getLastStartDialogSize() const
{
	return m_lastStartDialogSize;
}

void MemoryConfig::setLastStartDialogSize(const QSize &value)
{
	if(value != m_lastStartDialogSize) {
		m_lastStartDialogSize = value;
		Q_EMIT changeLastStartDialogSize(m_lastStartDialogSize);
	}
}

int MemoryConfig::getLastTool() const
{
	return m_lastTool;
}

void MemoryConfig::setLastTool(int value)
{
	if(value != m_lastTool) {
		m_lastTool = value;
		Q_EMIT changeLastTool(m_lastTool);
	}
}

QColor MemoryConfig::getLastToolBackgroundColor() const
{
	return m_lastToolBackgroundColor;
}

void MemoryConfig::setLastToolBackgroundColor(const QColor &value)
{
	if(value != m_lastToolBackgroundColor) {
		m_lastToolBackgroundColor = value;
		Q_EMIT changeLastToolBackgroundColor(m_lastToolBackgroundColor);
	}
}

QColor MemoryConfig::getLastToolColor() const
{
	return m_lastToolColor;
}

void MemoryConfig::setLastToolColor(const QColor &value)
{
	if(value != m_lastToolColor) {
		m_lastToolColor = value;
		Q_EMIT changeLastToolColor(m_lastToolColor);
	}
}

QString MemoryConfig::getLastUsername() const
{
	return m_lastUsername;
}

void MemoryConfig::setLastUsername(const QString &value)
{
	if(value != m_lastUsername) {
		m_lastUsername = value;
		Q_EMIT changeLastUsername(m_lastUsername);
	}
}

QMap<QString, bool> MemoryConfig::getLastWindowActions() const
{
	return m_lastWindowActions;
}

void MemoryConfig::setLastWindowActions(const QMap<QString, bool> &value)
{
	if(value != m_lastWindowActions) {
		m_lastWindowActions = value;
		Q_EMIT changeLastWindowActions(m_lastWindowActions);
	}
}

QVariantMap MemoryConfig::getLastWindowDocks() const
{
	return m_lastWindowDocks;
}

void MemoryConfig::setLastWindowDocks(const QVariantMap &value)
{
	if(value != m_lastWindowDocks) {
		m_lastWindowDocks = value;
		Q_EMIT changeLastWindowDocks(m_lastWindowDocks);
	}
}

bool MemoryConfig::getLastWindowMaximized() const
{
	return m_lastWindowMaximized;
}

void MemoryConfig::setLastWindowMaximized(bool value)
{
	if(value != m_lastWindowMaximized) {
		m_lastWindowMaximized = value;
		Q_EMIT changeLastWindowMaximized(m_lastWindowMaximized);
	}
}

QPoint MemoryConfig::getLastWindowPosition() const
{
	return m_lastWindowPosition;
}

void MemoryConfig::setLastWindowPosition(const QPoint &value)
{
	if(value != m_lastWindowPosition) {
		m_lastWindowPosition = value;
		Q_EMIT changeLastWindowPosition(m_lastWindowPosition);
	}
}

QSize MemoryConfig::getLastWindowSize() const
{
	return m_lastWindowSize;
}

void MemoryConfig::setLastWindowSize(const QSize &value)
{
	if(value != m_lastWindowSize) {
		m_lastWindowSize = value;
		Q_EMIT changeLastWindowSize(m_lastWindowSize);
	}
}

QByteArray MemoryConfig::getLastWindowState() const
{
	return m_lastWindowState;
}

void MemoryConfig::setLastWindowState(const QByteArray &value)
{
	if(value != m_lastWindowState) {
		m_lastWindowState = value;
		Q_EMIT changeLastWindowState(m_lastWindowState);
	}
}

QByteArray MemoryConfig::getLastWindowViewState() const
{
	return m_lastWindowViewState;
}

void MemoryConfig::setLastWindowViewState(const QByteArray &value)
{
	if(value != m_lastWindowViewState) {
		m_lastWindowViewState = value;
		Q_EMIT changeLastWindowViewState(m_lastWindowViewState);
	}
}

int MemoryConfig::getLayerSketchOpacityPercent() const
{
	return m_layerSketchOpacityPercent;
}

void MemoryConfig::setLayerSketchOpacityPercent(int value)
{
	if(value != m_layerSketchOpacityPercent) {
		m_layerSketchOpacityPercent = value;
		Q_EMIT changeLayerSketchOpacityPercent(m_layerSketchOpacityPercent);
	}
}

QColor MemoryConfig::getLayerSketchTint() const
{
	return m_layerSketchTint;
}

void MemoryConfig::setLayerSketchTint(const QColor &value)
{
	if(value != m_layerSketchTint) {
		m_layerSketchTint = value;
		Q_EMIT changeLayerSketchTint(m_layerSketchTint);
	}
}

QVector<QVariantMap> MemoryConfig::getLayouts() const
{
	return m_layouts;
}

void MemoryConfig::setLayouts(const QVector<QVariantMap> &value)
{
	if(value != m_layouts) {
		m_layouts = value;
		Q_EMIT changeLayouts(m_layouts);
	}
}

int MemoryConfig::getLayoutsVersion() const
{
	return m_layoutsVersion;
}

void MemoryConfig::setLayoutsVersion(int value)
{
	if(value != m_layoutsVersion) {
		m_layoutsVersion = value;
		Q_EMIT changeLayoutsVersion(m_layoutsVersion);
	}
}

bool MemoryConfig::getLeftyMode() const
{
	return m_leftyMode;
}

void MemoryConfig::setLeftyMode(bool value)
{
	if(value != m_leftyMode) {
		m_leftyMode = value;
		Q_EMIT changeLeftyMode(m_leftyMode);
	}
}

QVector<QVariantMap> MemoryConfig::getListServers() const
{
	return m_listServers;
}

void MemoryConfig::setListServers(const QVector<QVariantMap> &value)
{
	if(value != m_listServers) {
		m_listServers = value;
		Q_EMIT changeListServers(m_listServers);
	}
}

bool MemoryConfig::getLongPressEnabled() const
{
	return m_longPressEnabled;
}

void MemoryConfig::setLongPressEnabled(bool value)
{
	if(value != m_longPressEnabled) {
		m_longPressEnabled = value;
		Q_EMIT changeLongPressEnabled(m_longPressEnabled);
	}
}

bool MemoryConfig::getMentionEnabled() const
{
	return m_mentionEnabled;
}

void MemoryConfig::setMentionEnabled(bool value)
{
	if(value != m_mentionEnabled) {
		m_mentionEnabled = value;
		Q_EMIT changeMentionEnabled(m_mentionEnabled);
	}
}

QString MemoryConfig::getMentionTriggerList() const
{
	return m_mentionTriggerList;
}

void MemoryConfig::setMentionTriggerList(const QString &value)
{
	if(value != m_mentionTriggerList) {
		m_mentionTriggerList = value;
		Q_EMIT changeMentionTriggerList(m_mentionTriggerList);
	}
}

int MemoryConfig::getMessageQueueDrainRate() const
{
	return m_messageQueueDrainRate;
}

void MemoryConfig::setMessageQueueDrainRate(int value)
{
	if(value != m_messageQueueDrainRate) {
		m_messageQueueDrainRate = value;
		Q_EMIT changeMessageQueueDrainRate(m_messageQueueDrainRate);
	}
}

bool MemoryConfig::getMouseSmoothing() const
{
	return m_mouseSmoothing;
}

void MemoryConfig::setMouseSmoothing(bool value)
{
	if(value != m_mouseSmoothing) {
		m_mouseSmoothing = value;
		Q_EMIT changeMouseSmoothing(m_mouseSmoothing);
	}
}

#if defined(NATIVE_DIALOGS_SETTING_AVAILABLE)
bool MemoryConfig::getNativeDialogs() const
{
	return m_nativeDialogs;
}

void MemoryConfig::setNativeDialogs(bool value)
{
	if(value != m_nativeDialogs) {
		m_nativeDialogs = value;
		Q_EMIT changeNativeDialogs(m_nativeDialogs);
	}
}
#endif

bool MemoryConfig::getNavigatorRealtime() const
{
	return m_navigatorRealtime;
}

void MemoryConfig::setNavigatorRealtime(bool value)
{
	if(value != m_navigatorRealtime) {
		m_navigatorRealtime = value;
		Q_EMIT changeNavigatorRealtime(m_navigatorRealtime);
	}
}

bool MemoryConfig::getNavigatorShowCursors() const
{
	return m_navigatorShowCursors;
}

void MemoryConfig::setNavigatorShowCursors(bool value)
{
	if(value != m_navigatorShowCursors) {
		m_navigatorShowCursors = value;
		Q_EMIT changeNavigatorShowCursors(m_navigatorShowCursors);
	}
}

int MemoryConfig::getNetworkProxyMode() const
{
	return m_networkProxyMode;
}

void MemoryConfig::setNetworkProxyMode(int value)
{
	if(value != m_networkProxyMode) {
		m_networkProxyMode = value;
		Q_EMIT changeNetworkProxyMode(m_networkProxyMode);
	}
}

QColor MemoryConfig::getNewCanvasBackColor() const
{
	return m_newCanvasBackColor;
}

void MemoryConfig::setNewCanvasBackColor(const QColor &value)
{
	if(value != m_newCanvasBackColor) {
		m_newCanvasBackColor = value;
		Q_EMIT changeNewCanvasBackColor(m_newCanvasBackColor);
	}
}

QSize MemoryConfig::getNewCanvasSize() const
{
	return m_newCanvasSize;
}

void MemoryConfig::setNewCanvasSize(const QSize &value)
{
	if(value != m_newCanvasSize) {
		m_newCanvasSize = value;
		Q_EMIT changeNewCanvasSize(m_newCanvasSize);
	}
}

bool MemoryConfig::getNotifFlashChat() const
{
	return m_notifFlashChat;
}

void MemoryConfig::setNotifFlashChat(bool value)
{
	if(value != m_notifFlashChat) {
		m_notifFlashChat = value;
		Q_EMIT changeNotifFlashChat(m_notifFlashChat);
	}
}

bool MemoryConfig::getNotifFlashDisconnect() const
{
	return m_notifFlashDisconnect;
}

void MemoryConfig::setNotifFlashDisconnect(bool value)
{
	if(value != m_notifFlashDisconnect) {
		m_notifFlashDisconnect = value;
		Q_EMIT changeNotifFlashDisconnect(m_notifFlashDisconnect);
	}
}

bool MemoryConfig::getNotifFlashLock() const
{
	return m_notifFlashLock;
}

void MemoryConfig::setNotifFlashLock(bool value)
{
	if(value != m_notifFlashLock) {
		m_notifFlashLock = value;
		Q_EMIT changeNotifFlashLock(m_notifFlashLock);
	}
}

bool MemoryConfig::getNotifFlashLogin() const
{
	return m_notifFlashLogin;
}

void MemoryConfig::setNotifFlashLogin(bool value)
{
	if(value != m_notifFlashLogin) {
		m_notifFlashLogin = value;
		Q_EMIT changeNotifFlashLogin(m_notifFlashLogin);
	}
}

bool MemoryConfig::getNotifFlashLogout() const
{
	return m_notifFlashLogout;
}

void MemoryConfig::setNotifFlashLogout(bool value)
{
	if(value != m_notifFlashLogout) {
		m_notifFlashLogout = value;
		Q_EMIT changeNotifFlashLogout(m_notifFlashLogout);
	}
}

bool MemoryConfig::getNotifFlashPrivateChat() const
{
	return m_notifFlashPrivateChat;
}

void MemoryConfig::setNotifFlashPrivateChat(bool value)
{
	if(value != m_notifFlashPrivateChat) {
		m_notifFlashPrivateChat = value;
		Q_EMIT changeNotifFlashPrivateChat(m_notifFlashPrivateChat);
	}
}

bool MemoryConfig::getNotifFlashUnlock() const
{
	return m_notifFlashUnlock;
}

void MemoryConfig::setNotifFlashUnlock(bool value)
{
	if(value != m_notifFlashUnlock) {
		m_notifFlashUnlock = value;
		Q_EMIT changeNotifFlashUnlock(m_notifFlashUnlock);
	}
}

bool MemoryConfig::getNotifPopupChat() const
{
	return m_notifPopupChat;
}

void MemoryConfig::setNotifPopupChat(bool value)
{
	if(value != m_notifPopupChat) {
		m_notifPopupChat = value;
		Q_EMIT changeNotifPopupChat(m_notifPopupChat);
	}
}

bool MemoryConfig::getNotifPopupDisconnect() const
{
	return m_notifPopupDisconnect;
}

void MemoryConfig::setNotifPopupDisconnect(bool value)
{
	if(value != m_notifPopupDisconnect) {
		m_notifPopupDisconnect = value;
		Q_EMIT changeNotifPopupDisconnect(m_notifPopupDisconnect);
	}
}

bool MemoryConfig::getNotifPopupLock() const
{
	return m_notifPopupLock;
}

void MemoryConfig::setNotifPopupLock(bool value)
{
	if(value != m_notifPopupLock) {
		m_notifPopupLock = value;
		Q_EMIT changeNotifPopupLock(m_notifPopupLock);
	}
}

bool MemoryConfig::getNotifPopupLogin() const
{
	return m_notifPopupLogin;
}

void MemoryConfig::setNotifPopupLogin(bool value)
{
	if(value != m_notifPopupLogin) {
		m_notifPopupLogin = value;
		Q_EMIT changeNotifPopupLogin(m_notifPopupLogin);
	}
}

bool MemoryConfig::getNotifPopupLogout() const
{
	return m_notifPopupLogout;
}

void MemoryConfig::setNotifPopupLogout(bool value)
{
	if(value != m_notifPopupLogout) {
		m_notifPopupLogout = value;
		Q_EMIT changeNotifPopupLogout(m_notifPopupLogout);
	}
}

bool MemoryConfig::getNotifPopupPrivateChat() const
{
	return m_notifPopupPrivateChat;
}

void MemoryConfig::setNotifPopupPrivateChat(bool value)
{
	if(value != m_notifPopupPrivateChat) {
		m_notifPopupPrivateChat = value;
		Q_EMIT changeNotifPopupPrivateChat(m_notifPopupPrivateChat);
	}
}

bool MemoryConfig::getNotifPopupUnlock() const
{
	return m_notifPopupUnlock;
}

void MemoryConfig::setNotifPopupUnlock(bool value)
{
	if(value != m_notifPopupUnlock) {
		m_notifPopupUnlock = value;
		Q_EMIT changeNotifPopupUnlock(m_notifPopupUnlock);
	}
}

bool MemoryConfig::getNotifSoundChat() const
{
	return m_notifSoundChat;
}

void MemoryConfig::setNotifSoundChat(bool value)
{
	if(value != m_notifSoundChat) {
		m_notifSoundChat = value;
		Q_EMIT changeNotifSoundChat(m_notifSoundChat);
	}
}

bool MemoryConfig::getNotifSoundDisconnect() const
{
	return m_notifSoundDisconnect;
}

void MemoryConfig::setNotifSoundDisconnect(bool value)
{
	if(value != m_notifSoundDisconnect) {
		m_notifSoundDisconnect = value;
		Q_EMIT changeNotifSoundDisconnect(m_notifSoundDisconnect);
	}
}

bool MemoryConfig::getNotifSoundLock() const
{
	return m_notifSoundLock;
}

void MemoryConfig::setNotifSoundLock(bool value)
{
	if(value != m_notifSoundLock) {
		m_notifSoundLock = value;
		Q_EMIT changeNotifSoundLock(m_notifSoundLock);
	}
}

bool MemoryConfig::getNotifSoundLogin() const
{
	return m_notifSoundLogin;
}

void MemoryConfig::setNotifSoundLogin(bool value)
{
	if(value != m_notifSoundLogin) {
		m_notifSoundLogin = value;
		Q_EMIT changeNotifSoundLogin(m_notifSoundLogin);
	}
}

bool MemoryConfig::getNotifSoundLogout() const
{
	return m_notifSoundLogout;
}

void MemoryConfig::setNotifSoundLogout(bool value)
{
	if(value != m_notifSoundLogout) {
		m_notifSoundLogout = value;
		Q_EMIT changeNotifSoundLogout(m_notifSoundLogout);
	}
}

bool MemoryConfig::getNotifSoundPrivateChat() const
{
	return m_notifSoundPrivateChat;
}

void MemoryConfig::setNotifSoundPrivateChat(bool value)
{
	if(value != m_notifSoundPrivateChat) {
		m_notifSoundPrivateChat = value;
		Q_EMIT changeNotifSoundPrivateChat(m_notifSoundPrivateChat);
	}
}

bool MemoryConfig::getNotifSoundUnlock() const
{
	return m_notifSoundUnlock;
}

void MemoryConfig::setNotifSoundUnlock(bool value)
{
	if(value != m_notifSoundUnlock) {
		m_notifSoundUnlock = value;
		Q_EMIT changeNotifSoundUnlock(m_notifSoundUnlock);
	}
}

int MemoryConfig::getOneFingerTap() const
{
	return m_oneFingerTap;
}

void MemoryConfig::setOneFingerTap(int value)
{
	if(value != m_oneFingerTap) {
		m_oneFingerTap = value;
		Q_EMIT changeOneFingerTap(m_oneFingerTap);
	}
}

int MemoryConfig::getOneFingerTapAndHold() const
{
	return m_oneFingerTapAndHold;
}

void MemoryConfig::setOneFingerTapAndHold(int value)
{
	if(value != m_oneFingerTapAndHold) {
		m_oneFingerTapAndHold = value;
		Q_EMIT changeOneFingerTapAndHold(m_oneFingerTapAndHold);
	}
}

int MemoryConfig::getOneFingerTouch() const
{
	return m_oneFingerTouch;
}

void MemoryConfig::setOneFingerTouch(int value)
{
	if(value != m_oneFingerTouch) {
		m_oneFingerTouch = value;
		Q_EMIT changeOneFingerTouch(m_oneFingerTouch);
	}
}

int MemoryConfig::getOnionSkinsFrameCount() const
{
	return m_onionSkinsFrameCount;
}

void MemoryConfig::setOnionSkinsFrameCount(int value)
{
	if(value != m_onionSkinsFrameCount) {
		m_onionSkinsFrameCount = value;
		Q_EMIT changeOnionSkinsFrameCount(m_onionSkinsFrameCount);
	}
}

QMap<int, int> MemoryConfig::getOnionSkinsFrames() const
{
	return m_onionSkinsFrames;
}

void MemoryConfig::setOnionSkinsFrames(const QMap<int, int> &value)
{
	if(value != m_onionSkinsFrames) {
		m_onionSkinsFrames = value;
		Q_EMIT changeOnionSkinsFrames(m_onionSkinsFrames);
	}
}

QColor MemoryConfig::getOnionSkinsTintAbove() const
{
	return m_onionSkinsTintAbove;
}

void MemoryConfig::setOnionSkinsTintAbove(const QColor &value)
{
	if(value != m_onionSkinsTintAbove) {
		m_onionSkinsTintAbove = value;
		Q_EMIT changeOnionSkinsTintAbove(m_onionSkinsTintAbove);
	}
}

QColor MemoryConfig::getOnionSkinsTintBelow() const
{
	return m_onionSkinsTintBelow;
}

void MemoryConfig::setOnionSkinsTintBelow(const QColor &value)
{
	if(value != m_onionSkinsTintBelow) {
		m_onionSkinsTintBelow = value;
		Q_EMIT changeOnionSkinsTintBelow(m_onionSkinsTintBelow);
	}
}

bool MemoryConfig::getOnionSkinsWrap() const
{
	return m_onionSkinsWrap;
}

void MemoryConfig::setOnionSkinsWrap(bool value)
{
	if(value != m_onionSkinsWrap) {
		m_onionSkinsWrap = value;
		Q_EMIT changeOnionSkinsWrap(m_onionSkinsWrap);
	}
}

bool MemoryConfig::getOverrideFontSize() const
{
	return m_overrideFontSize;
}

void MemoryConfig::setOverrideFontSize(bool value)
{
	if(value != m_overrideFontSize) {
		m_overrideFontSize = value;
		Q_EMIT changeOverrideFontSize(m_overrideFontSize);
	}
}

bool MemoryConfig::getParentalControlsAutoTag() const
{
	return m_parentalControlsAutoTag;
}

void MemoryConfig::setParentalControlsAutoTag(bool value)
{
	if(value != m_parentalControlsAutoTag) {
		m_parentalControlsAutoTag = value;
		Q_EMIT changeParentalControlsAutoTag(m_parentalControlsAutoTag);
	}
}

bool MemoryConfig::getParentalControlsForceCensor() const
{
	return m_parentalControlsForceCensor;
}

void MemoryConfig::setParentalControlsForceCensor(bool value)
{
	if(value != m_parentalControlsForceCensor) {
		m_parentalControlsForceCensor = value;
		Q_EMIT changeParentalControlsForceCensor(m_parentalControlsForceCensor);
	}
}

bool MemoryConfig::getParentalControlsHideLocked() const
{
	return m_parentalControlsHideLocked;
}

void MemoryConfig::setParentalControlsHideLocked(bool value)
{
	if(value != m_parentalControlsHideLocked) {
		m_parentalControlsHideLocked = value;
		Q_EMIT changeParentalControlsHideLocked(m_parentalControlsHideLocked);
	}
}

int MemoryConfig::getParentalControlsLevel() const
{
	return m_parentalControlsLevel;
}

void MemoryConfig::setParentalControlsLevel(int value)
{
	if(value != m_parentalControlsLevel) {
		m_parentalControlsLevel = value;
		Q_EMIT changeParentalControlsLevel(m_parentalControlsLevel);
	}
}

QByteArray MemoryConfig::getParentalControlsLocked() const
{
	return m_parentalControlsLocked;
}

void MemoryConfig::setParentalControlsLocked(const QByteArray &value)
{
	if(value != m_parentalControlsLocked) {
		m_parentalControlsLocked = value;
		Q_EMIT changeParentalControlsLocked(m_parentalControlsLocked);
	}
}

QString MemoryConfig::getParentalControlsTags() const
{
	return m_parentalControlsTags;
}

void MemoryConfig::setParentalControlsTags(const QString &value)
{
	if(value != m_parentalControlsTags) {
		m_parentalControlsTags = value;
		Q_EMIT changeParentalControlsTags(m_parentalControlsTags);
	}
}

QString MemoryConfig::getPreferredExportFormat() const
{
	return m_preferredExportFormat;
}

void MemoryConfig::setPreferredExportFormat(const QString &value)
{
	if(value != m_preferredExportFormat) {
		m_preferredExportFormat = value;
		Q_EMIT changePreferredExportFormat(m_preferredExportFormat);
	}
}

QString MemoryConfig::getPreferredSaveFormat() const
{
	return m_preferredSaveFormat;
}

void MemoryConfig::setPreferredSaveFormat(const QString &value)
{
	if(value != m_preferredSaveFormat) {
		m_preferredSaveFormat = value;
		Q_EMIT changePreferredSaveFormat(m_preferredSaveFormat);
	}
}

bool MemoryConfig::getPromptLayerCreate() const
{
	return m_promptLayerCreate;
}

void MemoryConfig::setPromptLayerCreate(bool value)
{
	if(value != m_promptLayerCreate) {
		m_promptLayerCreate = value;
		Q_EMIT changePromptLayerCreate(m_promptLayerCreate);
	}
}

#if defined(Q_OS_MACOS)
bool MemoryConfig::getQuitOnLastWindowClosed() const
{
	return m_quitOnLastWindowClosed;
}

void MemoryConfig::setQuitOnLastWindowClosed(bool value)
{
	if(value != m_quitOnLastWindowClosed) {
		m_quitOnLastWindowClosed = value;
		Q_EMIT changeQuitOnLastWindowClosed(m_quitOnLastWindowClosed);
	}
}
#endif

QStringList MemoryConfig::getRecentFiles() const
{
	return m_recentFiles;
}

void MemoryConfig::setRecentFiles(const QStringList &value)
{
	if(value != m_recentFiles) {
		m_recentFiles = value;
		Q_EMIT changeRecentFiles(m_recentFiles);
	}
}

QStringList MemoryConfig::getRecentHosts() const
{
	return m_recentHosts;
}

void MemoryConfig::setRecentHosts(const QStringList &value)
{
	if(value != m_recentHosts) {
		m_recentHosts = value;
		Q_EMIT changeRecentHosts(m_recentHosts);
	}
}

QStringList MemoryConfig::getRecentRemoteHosts() const
{
	return m_recentRemoteHosts;
}

void MemoryConfig::setRecentRemoteHosts(const QStringList &value)
{
	if(value != m_recentRemoteHosts) {
		m_recentRemoteHosts = value;
		Q_EMIT changeRecentRemoteHosts(m_recentRemoteHosts);
	}
}

int MemoryConfig::getRenderCanvas() const
{
	return m_renderCanvas;
}

void MemoryConfig::setRenderCanvas(int value)
{
	if(value != m_renderCanvas) {
		m_renderCanvas = value;
		Q_EMIT changeRenderCanvas(m_renderCanvas);
	}
}

bool MemoryConfig::getRenderSmooth() const
{
	return m_renderSmooth;
}

void MemoryConfig::setRenderSmooth(bool value)
{
	if(value != m_renderSmooth) {
		m_renderSmooth = value;
		Q_EMIT changeRenderSmooth(m_renderSmooth);
	}
}

bool MemoryConfig::getRenderUpdateFull() const
{
	return m_renderUpdateFull;
}

void MemoryConfig::setRenderUpdateFull(bool value)
{
	if(value != m_renderUpdateFull) {
		m_renderUpdateFull = value;
		Q_EMIT changeRenderUpdateFull(m_renderUpdateFull);
	}
}

int MemoryConfig::getSamplingRingVisibility() const
{
	return m_samplingRingVisibility;
}

void MemoryConfig::setSamplingRingVisibility(int value)
{
	if(value != m_samplingRingVisibility) {
		m_samplingRingVisibility = value;
		Q_EMIT changeSamplingRingVisibility(m_samplingRingVisibility);
	}
}

QColor MemoryConfig::getSelectionColor() const
{
	return m_selectionColor;
}

void MemoryConfig::setSelectionColor(const QColor &value)
{
	if(value != m_selectionColor) {
		m_selectionColor = value;
		Q_EMIT changeSelectionColor(m_selectionColor);
	}
}

bool MemoryConfig::getServerAutoReset() const
{
	return m_serverAutoReset;
}

void MemoryConfig::setServerAutoReset(bool value)
{
	if(value != m_serverAutoReset) {
		m_serverAutoReset = value;
		Q_EMIT changeServerAutoReset(m_serverAutoReset);
	}
}

bool MemoryConfig::getServerHideIp() const
{
	return m_serverHideIp;
}

void MemoryConfig::setServerHideIp(bool value)
{
	if(value != m_serverHideIp) {
		m_serverHideIp = value;
		Q_EMIT changeServerHideIp(m_serverHideIp);
	}
}

int MemoryConfig::getServerPort() const
{
	return m_serverPort;
}

void MemoryConfig::setServerPort(int value)
{
	if(value != m_serverPort) {
		m_serverPort = value;
		Q_EMIT changeServerPort(m_serverPort);
	}
}

int MemoryConfig::getServerTimeout() const
{
	return m_serverTimeout;
}

void MemoryConfig::setServerTimeout(int value)
{
	if(value != m_serverTimeout) {
		m_serverTimeout = value;
		Q_EMIT changeServerTimeout(m_serverTimeout);
	}
}

bool MemoryConfig::getShareBrushSlotColor() const
{
	return m_shareBrushSlotColor;
}

void MemoryConfig::setShareBrushSlotColor(bool value)
{
	if(value != m_shareBrushSlotColor) {
		m_shareBrushSlotColor = value;
		Q_EMIT changeShareBrushSlotColor(m_shareBrushSlotColor);
	}
}

QVariantMap MemoryConfig::getShortcuts() const
{
	return m_shortcuts;
}

void MemoryConfig::setShortcuts(const QVariantMap &value)
{
	if(value != m_shortcuts) {
		m_shortcuts = value;
		Q_EMIT changeShortcuts(m_shortcuts);
	}
}

bool MemoryConfig::getShowInviteDialogOnHost() const
{
	return m_showInviteDialogOnHost;
}

void MemoryConfig::setShowInviteDialogOnHost(bool value)
{
	if(value != m_showInviteDialogOnHost) {
		m_showInviteDialogOnHost = value;
		Q_EMIT changeShowInviteDialogOnHost(m_showInviteDialogOnHost);
	}
}

bool MemoryConfig::getShowNsfmWarningOnJoin() const
{
	return m_showNsfmWarningOnJoin;
}

void MemoryConfig::setShowNsfmWarningOnJoin(bool value)
{
	if(value != m_showNsfmWarningOnJoin) {
		m_showNsfmWarningOnJoin = value;
		Q_EMIT changeShowNsfmWarningOnJoin(m_showNsfmWarningOnJoin);
	}
}

bool MemoryConfig::getShowTransformNotices() const
{
	return m_showTransformNotices;
}

void MemoryConfig::setShowTransformNotices(bool value)
{
	if(value != m_showTransformNotices) {
		m_showTransformNotices = value;
		Q_EMIT changeShowTransformNotices(m_showTransformNotices);
	}
}

bool MemoryConfig::getShowTrayIcon() const
{
	return m_showTrayIcon;
}

void MemoryConfig::setShowTrayIcon(bool value)
{
	if(value != m_showTrayIcon) {
		m_showTrayIcon = value;
		Q_EMIT changeShowTrayIcon(m_showTrayIcon);
	}
}

bool MemoryConfig::getShowViewModeNotices() const
{
	return m_showViewModeNotices;
}

void MemoryConfig::setShowViewModeNotices(bool value)
{
	if(value != m_showViewModeNotices) {
		m_showViewModeNotices = value;
		Q_EMIT changeShowViewModeNotices(m_showViewModeNotices);
	}
}

int MemoryConfig::getSmoothing() const
{
	return m_smoothing;
}

void MemoryConfig::setSmoothing(int value)
{
	if(value != m_smoothing) {
		m_smoothing = value;
		Q_EMIT changeSmoothing(m_smoothing);
	}
}

int MemoryConfig::getSoundVolume() const
{
	return m_soundVolume;
}

void MemoryConfig::setSoundVolume(int value)
{
	if(value != m_soundVolume) {
		m_soundVolume = value;
		Q_EMIT changeSoundVolume(m_soundVolume);
	}
}

int MemoryConfig::getTabletDriver() const
{
	return m_tabletDriver;
}

void MemoryConfig::setTabletDriver(int value)
{
	if(value != m_tabletDriver) {
		m_tabletDriver = value;
		Q_EMIT changeTabletDriver(m_tabletDriver);
	}
}

int MemoryConfig::getTabletEraserAction() const
{
	return m_tabletEraserAction;
}

void MemoryConfig::setTabletEraserAction(int value)
{
	if(value != m_tabletEraserAction) {
		m_tabletEraserAction = value;
		Q_EMIT changeTabletEraserAction(m_tabletEraserAction);
	}
}

bool MemoryConfig::getTabletEvents() const
{
	return m_tabletEvents;
}

void MemoryConfig::setTabletEvents(bool value)
{
	if(value != m_tabletEvents) {
		m_tabletEvents = value;
		Q_EMIT changeTabletEvents(m_tabletEvents);
	}
}

int MemoryConfig::getTabletPressTimerDelay() const
{
	return m_tabletPressTimerDelay;
}

void MemoryConfig::setTabletPressTimerDelay(int value)
{
	if(value != m_tabletPressTimerDelay) {
		m_tabletPressTimerDelay = value;
		Q_EMIT changeTabletPressTimerDelay(m_tabletPressTimerDelay);
	}
}

bool MemoryConfig::getTemporaryToolSwitch() const
{
	return m_temporaryToolSwitch;
}

void MemoryConfig::setTemporaryToolSwitch(bool value)
{
	if(value != m_temporaryToolSwitch) {
		m_temporaryToolSwitch = value;
		Q_EMIT changeTemporaryToolSwitch(m_temporaryToolSwitch);
	}
}

int MemoryConfig::getTemporaryToolSwitchMs() const
{
	return m_temporaryToolSwitchMs;
}

void MemoryConfig::setTemporaryToolSwitchMs(int value)
{
	if(value != m_temporaryToolSwitchMs) {
		m_temporaryToolSwitchMs = value;
		Q_EMIT changeTemporaryToolSwitchMs(m_temporaryToolSwitchMs);
	}
}

QString MemoryConfig::getThemePalette() const
{
	return m_themePalette;
}

void MemoryConfig::setThemePalette(const QString &value)
{
	if(value != m_themePalette) {
		m_themePalette = value;
		Q_EMIT changeThemePalette(m_themePalette);
	}
}

QString MemoryConfig::getThemeStyle() const
{
	return m_themeStyle;
}

void MemoryConfig::setThemeStyle(const QString &value)
{
	if(value != m_themeStyle) {
		m_themeStyle = value;
		Q_EMIT changeThemeStyle(m_themeStyle);
	}
}

int MemoryConfig::getThreeFingerTap() const
{
	return m_threeFingerTap;
}

void MemoryConfig::setThreeFingerTap(int value)
{
	if(value != m_threeFingerTap) {
		m_threeFingerTap = value;
		Q_EMIT changeThreeFingerTap(m_threeFingerTap);
	}
}

QColor MemoryConfig::getTimelapseBackdropColor() const
{
	return m_timelapseBackdropColor;
}

void MemoryConfig::setTimelapseBackdropColor(const QColor &value)
{
	if(value != m_timelapseBackdropColor) {
		m_timelapseBackdropColor = value;
		Q_EMIT changeTimelapseBackdropColor(m_timelapseBackdropColor);
	}
}

int MemoryConfig::getTimelapseDurationSeconds() const
{
	return m_timelapseDurationSeconds;
}

void MemoryConfig::setTimelapseDurationSeconds(int value)
{
	if(value != m_timelapseDurationSeconds) {
		m_timelapseDurationSeconds = value;
		Q_EMIT changeTimelapseDurationSeconds(m_timelapseDurationSeconds);
	}
}

int MemoryConfig::getTimelapseExportFormat() const
{
	return m_timelapseExportFormat;
}

void MemoryConfig::setTimelapseExportFormat(int value)
{
	if(value != m_timelapseExportFormat) {
		m_timelapseExportFormat = value;
		Q_EMIT changeTimelapseExportFormat(m_timelapseExportFormat);
	}
}

QColor MemoryConfig::getTimelapseFlashColor() const
{
	return m_timelapseFlashColor;
}

void MemoryConfig::setTimelapseFlashColor(const QColor &value)
{
	if(value != m_timelapseFlashColor) {
		m_timelapseFlashColor = value;
		Q_EMIT changeTimelapseFlashColor(m_timelapseFlashColor);
	}
}

int MemoryConfig::getTimelapseFlashSeconds() const
{
	return m_timelapseFlashSeconds;
}

void MemoryConfig::setTimelapseFlashSeconds(int value)
{
	if(value != m_timelapseFlashSeconds) {
		m_timelapseFlashSeconds = value;
		Q_EMIT changeTimelapseFlashSeconds(m_timelapseFlashSeconds);
	}
}

double MemoryConfig::getTimelapseFramerate() const
{
	return m_timelapseFramerate;
}

void MemoryConfig::setTimelapseFramerate(double value)
{
	if(value != m_timelapseFramerate) {
		m_timelapseFramerate = value;
		Q_EMIT changeTimelapseFramerate(m_timelapseFramerate);
	}
}

int MemoryConfig::getTimelapseInterpolation() const
{
	return m_timelapseInterpolation;
}

void MemoryConfig::setTimelapseInterpolation(int value)
{
	if(value != m_timelapseInterpolation) {
		m_timelapseInterpolation = value;
		Q_EMIT changeTimelapseInterpolation(m_timelapseInterpolation);
	}
}

int MemoryConfig::getTimelapseLingerAfterLoops() const
{
	return m_timelapseLingerAfterLoops;
}

void MemoryConfig::setTimelapseLingerAfterLoops(int value)
{
	if(value != m_timelapseLingerAfterLoops) {
		m_timelapseLingerAfterLoops = value;
		Q_EMIT changeTimelapseLingerAfterLoops(m_timelapseLingerAfterLoops);
	}
}

int MemoryConfig::getTimelapseLingerAfterSeconds() const
{
	return m_timelapseLingerAfterSeconds;
}

void MemoryConfig::setTimelapseLingerAfterSeconds(int value)
{
	if(value != m_timelapseLingerAfterSeconds) {
		m_timelapseLingerAfterSeconds = value;
		Q_EMIT changeTimelapseLingerAfterSeconds(m_timelapseLingerAfterSeconds);
	}
}

int MemoryConfig::getTimelapseLingerBeforeLoops() const
{
	return m_timelapseLingerBeforeLoops;
}

void MemoryConfig::setTimelapseLingerBeforeLoops(int value)
{
	if(value != m_timelapseLingerBeforeLoops) {
		m_timelapseLingerBeforeLoops = value;
		Q_EMIT changeTimelapseLingerBeforeLoops(m_timelapseLingerBeforeLoops);
	}
}

int MemoryConfig::getTimelapseLingerBeforeSeconds() const
{
	return m_timelapseLingerBeforeSeconds;
}

void MemoryConfig::setTimelapseLingerBeforeSeconds(int value)
{
	if(value != m_timelapseLingerBeforeSeconds) {
		m_timelapseLingerBeforeSeconds = value;
		Q_EMIT changeTimelapseLingerBeforeSeconds(
			m_timelapseLingerBeforeSeconds);
	}
}

int MemoryConfig::getTimelapseLogoLocation() const
{
	return m_timelapseLogoLocation;
}

void MemoryConfig::setTimelapseLogoLocation(int value)
{
	if(value != m_timelapseLogoLocation) {
		m_timelapseLogoLocation = value;
		Q_EMIT changeTimelapseLogoLocation(m_timelapseLogoLocation);
	}
}

double MemoryConfig::getTimelapseLogoOffset() const
{
	return m_timelapseLogoOffset;
}

void MemoryConfig::setTimelapseLogoOffset(double value)
{
	if(value != m_timelapseLogoOffset) {
		m_timelapseLogoOffset = value;
		Q_EMIT changeTimelapseLogoOffset(m_timelapseLogoOffset);
	}
}

int MemoryConfig::getTimelapseLogoOpacity() const
{
	return m_timelapseLogoOpacity;
}

void MemoryConfig::setTimelapseLogoOpacity(int value)
{
	if(value != m_timelapseLogoOpacity) {
		m_timelapseLogoOpacity = value;
		Q_EMIT changeTimelapseLogoOpacity(m_timelapseLogoOpacity);
	}
}

double MemoryConfig::getTimelapseLogoScale() const
{
	return m_timelapseLogoScale;
}

void MemoryConfig::setTimelapseLogoScale(double value)
{
	if(value != m_timelapseLogoScale) {
		m_timelapseLogoScale = value;
		Q_EMIT changeTimelapseLogoScale(m_timelapseLogoScale);
	}
}

double MemoryConfig::getTimelapseMaxDeltaSeconds() const
{
	return m_timelapseMaxDeltaSeconds;
}

void MemoryConfig::setTimelapseMaxDeltaSeconds(double value)
{
	if(value != m_timelapseMaxDeltaSeconds) {
		m_timelapseMaxDeltaSeconds = value;
		Q_EMIT changeTimelapseMaxDeltaSeconds(m_timelapseMaxDeltaSeconds);
	}
}

int MemoryConfig::getTimelapseMaxQueueEntries() const
{
	return m_timelapseMaxQueueEntries;
}

void MemoryConfig::setTimelapseMaxQueueEntries(int value)
{
	if(value != m_timelapseMaxQueueEntries) {
		m_timelapseMaxQueueEntries = value;
		Q_EMIT changeTimelapseMaxQueueEntries(m_timelapseMaxQueueEntries);
	}
}

bool MemoryConfig::getTimelapseShowAdvanced() const
{
	return m_timelapseShowAdvanced;
}

void MemoryConfig::setTimelapseShowAdvanced(bool value)
{
	if(value != m_timelapseShowAdvanced) {
		m_timelapseShowAdvanced = value;
		Q_EMIT changeTimelapseShowAdvanced(m_timelapseShowAdvanced);
	}
}

bool MemoryConfig::getTimelapseTimeOwnOnly() const
{
	return m_timelapseTimeOwnOnly;
}

void MemoryConfig::setTimelapseTimeOwnOnly(bool value)
{
	if(value != m_timelapseTimeOwnOnly) {
		m_timelapseTimeOwnOnly = value;
		Q_EMIT changeTimelapseTimeOwnOnly(m_timelapseTimeOwnOnly);
	}
}

QVariantHash MemoryConfig::getToolBarConfig() const
{
	return m_toolBarConfig;
}

void MemoryConfig::setToolBarConfig(const QVariantHash &value)
{
	if(value != m_toolBarConfig) {
		m_toolBarConfig = value;
		Q_EMIT changeToolBarConfig(m_toolBarConfig);
	}
}

bool MemoryConfig::getToolToggle() const
{
	return m_toolToggle;
}

void MemoryConfig::setToolToggle(bool value)
{
	if(value != m_toolToggle) {
		m_toolToggle = value;
		Q_EMIT changeToolToggle(m_toolToggle);
	}
}

QMap<QString, QVariantHash> MemoryConfig::getToolset() const
{
	return m_toolset;
}

void MemoryConfig::setToolset(const QMap<QString, QVariantHash> &value)
{
	if(value != m_toolset) {
		m_toolset = value;
		Q_EMIT changeToolset(m_toolset);
	}
}

bool MemoryConfig::getTouchDrawPressure() const
{
	return m_touchDrawPressure;
}

void MemoryConfig::setTouchDrawPressure(bool value)
{
	if(value != m_touchDrawPressure) {
		m_touchDrawPressure = value;
		Q_EMIT changeTouchDrawPressure(m_touchDrawPressure);
	}
}

bool MemoryConfig::getTouchGestures() const
{
	return m_touchGestures;
}

void MemoryConfig::setTouchGestures(bool value)
{
	if(value != m_touchGestures) {
		m_touchGestures = value;
		Q_EMIT changeTouchGestures(m_touchGestures);
	}
}

int MemoryConfig::getTouchSmoothing() const
{
	return m_touchSmoothing;
}

void MemoryConfig::setTouchSmoothing(int value)
{
	if(value != m_touchSmoothing) {
		m_touchSmoothing = value;
		Q_EMIT changeTouchSmoothing(m_touchSmoothing);
	}
}

int MemoryConfig::getTwoFingerPinch() const
{
	return m_twoFingerPinch;
}

void MemoryConfig::setTwoFingerPinch(int value)
{
	if(value != m_twoFingerPinch) {
		m_twoFingerPinch = value;
		Q_EMIT changeTwoFingerPinch(m_twoFingerPinch);
	}
}

int MemoryConfig::getTwoFingerTap() const
{
	return m_twoFingerTap;
}

void MemoryConfig::setTwoFingerTap(int value)
{
	if(value != m_twoFingerTap) {
		m_twoFingerTap = value;
		Q_EMIT changeTwoFingerTap(m_twoFingerTap);
	}
}

int MemoryConfig::getTwoFingerTwist() const
{
	return m_twoFingerTwist;
}

void MemoryConfig::setTwoFingerTwist(int value)
{
	if(value != m_twoFingerTwist) {
		m_twoFingerTwist = value;
		Q_EMIT changeTwoFingerTwist(m_twoFingerTwist);
	}
}

bool MemoryConfig::getUpdateCheckEnabled() const
{
	return m_updateCheckEnabled;
}

void MemoryConfig::setUpdateCheckEnabled(bool value)
{
	if(value != m_updateCheckEnabled) {
		m_updateCheckEnabled = value;
		Q_EMIT changeUpdateCheckEnabled(m_updateCheckEnabled);
	}
}

bool MemoryConfig::getUseMipmaps() const
{
	return m_useMipmaps;
}

void MemoryConfig::setUseMipmaps(bool value)
{
	if(value != m_useMipmaps) {
		m_useMipmaps = value;
		Q_EMIT changeUseMipmaps(m_useMipmaps);
	}
}

int MemoryConfig::getUserMarkerPersistence() const
{
	return m_userMarkerPersistence;
}

void MemoryConfig::setUserMarkerPersistence(int value)
{
	if(value != m_userMarkerPersistence) {
		m_userMarkerPersistence = value;
		Q_EMIT changeUserMarkerPersistence(m_userMarkerPersistence);
	}
}

QString MemoryConfig::getVideoExportCustomFfmpeg() const
{
	return m_videoExportCustomFfmpeg;
}

void MemoryConfig::setVideoExportCustomFfmpeg(const QString &value)
{
	if(value != m_videoExportCustomFfmpeg) {
		m_videoExportCustomFfmpeg = value;
		Q_EMIT changeVideoExportCustomFfmpeg(m_videoExportCustomFfmpeg);
	}
}

QString MemoryConfig::getVideoExportFfmpegPath() const
{
	return m_videoExportFfmpegPath;
}

void MemoryConfig::setVideoExportFfmpegPath(const QString &value)
{
	if(value != m_videoExportFfmpegPath) {
		m_videoExportFfmpegPath = value;
		Q_EMIT changeVideoExportFfmpegPath(m_videoExportFfmpegPath);
	}
}

int MemoryConfig::getVideoExportFormat() const
{
	return m_videoExportFormat;
}

void MemoryConfig::setVideoExportFormat(int value)
{
	if(value != m_videoExportFormat) {
		m_videoExportFormat = value;
		Q_EMIT changeVideoExportFormat(m_videoExportFormat);
	}
}

int MemoryConfig::getVideoExportFrameHeight() const
{
	return m_videoExportFrameHeight;
}

void MemoryConfig::setVideoExportFrameHeight(int value)
{
	if(value != m_videoExportFrameHeight) {
		m_videoExportFrameHeight = value;
		Q_EMIT changeVideoExportFrameHeight(m_videoExportFrameHeight);
	}
}

int MemoryConfig::getVideoExportFrameRate() const
{
	return m_videoExportFrameRate;
}

void MemoryConfig::setVideoExportFrameRate(int value)
{
	if(value != m_videoExportFrameRate) {
		m_videoExportFrameRate = value;
		Q_EMIT changeVideoExportFrameRate(m_videoExportFrameRate);
	}
}

int MemoryConfig::getVideoExportFrameWidth() const
{
	return m_videoExportFrameWidth;
}

void MemoryConfig::setVideoExportFrameWidth(int value)
{
	if(value != m_videoExportFrameWidth) {
		m_videoExportFrameWidth = value;
		Q_EMIT changeVideoExportFrameWidth(m_videoExportFrameWidth);
	}
}

int MemoryConfig::getVideoExportSizeChoice() const
{
	return m_videoExportSizeChoice;
}

void MemoryConfig::setVideoExportSizeChoice(int value)
{
	if(value != m_videoExportSizeChoice) {
		m_videoExportSizeChoice = value;
		Q_EMIT changeVideoExportSizeChoice(m_videoExportSizeChoice);
	}
}

bool MemoryConfig::getWelcomePageShown() const
{
	return m_welcomePageShown;
}

void MemoryConfig::setWelcomePageShown(bool value)
{
	if(value != m_welcomePageShown) {
		m_welcomePageShown = value;
		Q_EMIT changeWelcomePageShown(m_welcomePageShown);
	}
}

bool MemoryConfig::getWriteLogFile() const
{
	return m_writeLogFile;
}

void MemoryConfig::setWriteLogFile(bool value)
{
	if(value != m_writeLogFile) {
		m_writeLogFile = value;
		Q_EMIT changeWriteLogFile(m_writeLogFile);
	}
}

}
