if(ADDRESS_SANITIZER)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(drawpile_asan_options -fno-omit-frame-pointer -fsanitize=address)
        message(STATUS "Using address sanitizer for gcc/clang "
                       "via options '${drawpile_asan_options}'")
    else()
        message(STATUS "Don't know how to enable address "
                       "sanitizer on ${CMAKE_CXX_COMPILER_ID}")
    endif()
else()
    message(STATUS "Not using address sanitizer, as requested")
endif()

function(add_address_sanitizer target)
    if(drawpile_asan_options)
        message(STATUS "Enabling address sanitizer on ${target}")
        target_compile_definitions("${target}" PRIVATE "DRAWPILE_ADDRESS_SANITIZER")
        target_compile_options("${target}" PRIVATE ${drawpile_asan_options})
        target_link_options("${target}" PRIVATE ${drawpile_asan_options})
    endif()
endfunction()
