#ifndef DRAWPILE_CONFIG_H
#define DRAWPILE_CONFIG_H

#define WEBSITE "${DRAWPILE_HOMEPAGE_URL}"
#cmakedefine BUILD_LABEL "${BUILD_LABEL}"
#define DRAWPILE_VERSION "${DRAWPILE_VERSION}"
#define DRAWPILE_PROTO_SERVER_VERSION ${DRAWPILE_PROTO_SERVER_VERSION}
#define DRAWPILE_PROTO_MAJOR_VERSION ${DRAWPILE_PROTO_MAJOR_VERSION}
#define DRAWPILE_PROTO_MINOR_VERSION ${DRAWPILE_PROTO_MINOR_VERSION}
#define DRAWPILE_PROTO_DEFAULT_PORT ${DRAWPILE_PROTO_DEFAULT_PORT}

#endif
