# Try to find QtColorPicker (Qt5 version) (https://github.com/mbasaglia/Qt-Color-Picker)
# 
# This will define
# LIBQTCOLORPICKER_FOUND
# LIBQTCOLORPICKER_INCLUDE_DIRS
# LIBQTCOLORPICKER_LIBRARIES

find_path(LIBQTCOLORPICKER_INCLUDE_DIR colorpicker_global.hpp
	PATH_SUFFIXES QtColorPicker)
find_library(LIBQTCOLORPICKER_LIBRARY NAMES ColorPicker-qt5)

set(LIBQTCOLORPICKER_INCLUDE_DIRS ${LIBQTCOLORPICKER_INCLUDE_DIR})
set(LIBQTCOLORPICKER_LIBRARIES ${LIBQTCOLORPICKER_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(QtColorPicker DEFAULT_MSG LIBQTCOLORPICKER_LIBRARY LIBQTCOLORPICKER_INCLUDE_DIR)

mark_as_advanced(LIBQTCOLORPICKER_INCLUDE_DIR LIBQTCOLORPICKER_LIBRARY)

