# Optimize.cmake

if (DEBUG)
	message ( STATUS "Optimization: None; Debug" )
	if (GENERIC)
		set ( CMAKE_CXX_FLAGS_DEBUG "-march=pentium2 -g -Wall -O0 -pipe" )
	else ()
		set ( CMAKE_CXX_FLAGS_DEBUG "-g -Wall -O0 -pipe" )
	endif ()
else ()
	if (GENERIC)
		message ( STATUS "Optimization: Generic" )
		set ( CMAKE_CXX_FLAGS_RELEASE "-march=pentium2 -O2 -pipe -fno-rtti -Wall -DNDEBUG" )
	else ()
		message ( STATUS "Optimization: Native" )
		if (NOT "$ENV{CXXFLAGS}" STREQUAL "")
			set ( CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -DNDEBUG" )
		else ()
			set ( CMAKE_CXX_FLAGS_RELEASE "-O2 -pipe -fno-rtti -Wall -DNDEBUG" )
		endif ()
	endif ()
endif ()
