// SPDX-License-Identifier: GPL-3.0-or-later
// This file is auto-generated by configen.py, do not edit it manually.
#include "libclient/settings_table_macros.h"

SETTING(
	_parentalControlsLevelDummy, _ParentalControlsLevelDummy,
	"_parentalcontrolsleveldummy", parentalcontrols::Level::Unrestricted)
#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
SETTING(
	androidScalingAskOnStartup, AndroidScalingAskOnStartup,
	"settings/androidscaling/askonstartup",
	config::Config::defaultAndroidScalingAskOnStartup())
#endif
#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
SETTING(
	androidScalingLastInitialScale, AndroidScalingLastInitialScale,
	"settings/androidscaling/lastinitialscale",
	config::Config::defaultAndroidScalingLastInitialScale())
#endif
#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
SETTING(
	androidScalingTargetScale, AndroidScalingTargetScale,
	"settings/androidscaling/targetscale",
	config::Config::defaultAndroidScalingTargetScale())
#endif
#if defined(KRITA_QATTRIBUTE_ANDROID_EMULATE_MOUSE_BUTTONS_FOR_PAGE_UP_DOWN)
SETTING(
	androidWorkaroundEmulateMouseButtonsForPageUpDown,
	AndroidWorkaroundEmulateMouseButtonsForPageUpDown,
	"settings/androidworkaround/emulatemousebuttonsforpageupdown",
	config::Config::defaultAndroidWorkaroundEmulateMouseButtonsForPageUpDown())
#endif
#if defined(KRITA_QATTRIBUTE_ANDROID_IGNORE_HISTORIC_TABLET_EVENTS)
SETTING(
	androidWorkaroundIgnoreHistoricTabletEvents,
	AndroidWorkaroundIgnoreHistoricTabletEvents,
	"settings/androidworkaround/ignorehistorictabletevents",
	config::Config::defaultAndroidWorkaroundIgnoreHistoricTabletEvents())
#endif
SETTING(
	autoRecordHost, AutoRecordHost, "settings/autorecord/host",
	config::Config::defaultAutoRecordHost())
SETTING(
	autoRecordJoin, AutoRecordJoin, "settings/autorecord/join",
	config::Config::defaultAutoRecordJoin())
SETTING(
	autoRecordMetadataIntervalMinutes, AutoRecordMetadataIntervalMinutes,
	"settings/autorecord/metadatainterval",
	config::Config::defaultAutoRecordMetadataIntervalMinutes())
SETTING(
	autoRecordSnapshotIntervalMinutes, AutoRecordSnapshotIntervalMinutes,
	"settings/autorecord/snapshotinterval",
	config::Config::defaultAutoRecordSnapshotIntervalMinutes())
SETTING(
	cancelDeselects, CancelDeselects, "settings/canceldeselects",
	config::Config::defaultCancelDeselects())
SETTING(
	checkerColor1, CheckerColor1, "settings/checkercolor1",
	config::Config::defaultCheckerColor1())
SETTING(
	checkerColor2, CheckerColor2, "settings/checkercolor2",
	config::Config::defaultCheckerColor2())
SETTING(
	engineFrameRate, EngineFrameRate, "settings/paintengine/fps",
	config::Config::defaultEngineFrameRate())
SETTING(
	engineSnapshotCount, EngineSnapshotCount,
	"settings/paintengine/snapshotcount",
	config::Config::defaultEngineSnapshotCount())
SETTING(
	engineSnapshotInterval, EngineSnapshotInterval,
	"settings/paintengine/snapshotinterval",
	config::Config::defaultEngineSnapshotInterval())
SETTING(
	engineUndoDepth, EngineUndoDepth, "settings/paintengine/undodepthlimit",
	config::Config::defaultEngineUndoDepth())
SETTING(
	interpolateInputs, InterpolateInputs, "settings/input/interpolate",
	config::Config::defaultInterpolateInputs())
SETTING(
	listServers, ListServers, "listservers",
	config::Config::defaultListServers())
SETTING(
	messageQueueDrainRate, MessageQueueDrainRate,
	"settings/messagequeuedrainrate",
	config::Config::defaultMessageQueueDrainRate())
SETTING(
	mouseSmoothing, MouseSmoothing, "settings/input/mousesmoothing",
	config::Config::defaultMouseSmoothing())
SETTING(
	networkProxyMode, NetworkProxyMode, "settings/networkproxymode",
	config::Config::defaultNetworkProxyMode())
SETTING(
	parentalControlsAutoTag, ParentalControlsAutoTag, "pc/autotag",
	config::Config::defaultParentalControlsAutoTag())
SETTING(
	parentalControlsForceCensor, ParentalControlsForceCensor,
	"pc/noUncensoring", config::Config::defaultParentalControlsForceCensor())
SETTING_GETSET_V(
	V1, parentalControlsLevel, ParentalControlsLevel, "pc/level",
	config::Config::defaultParentalControlsLevel(), &parentalcontrolslevel::get,
	&any::set)
SETTING(
	parentalControlsLocked, ParentalControlsLocked, "pc/locked",
	config::Config::defaultParentalControlsLocked())
SETTING(
	parentalControlsTags, ParentalControlsTags, "pc/tagwords",
	config::Config::defaultParentalControlsTags())
SETTING(
	selectionColor, SelectionColor, "settings/selectioncolor",
	config::Config::defaultSelectionColor())
SETTING(
	serverAutoReset, ServerAutoReset, "settings/server/autoreset",
	config::Config::defaultServerAutoReset())
SETTING(
	serverPort, ServerPort, "settings/server/port",
	config::Config::defaultServerPort())
SETTING(
	serverTimeout, ServerTimeout, "settings/server/timeout",
	config::Config::defaultServerTimeout())
SETTING(
	smoothing, Smoothing, "settings/input/smooth",
	config::Config::defaultSmoothing())

#include "libclient/settings_table_macros.h"
