#!/bin/sh
# Copyright (c) 2022 askmeaboutloom
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
set -e

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 BUILDDIR" 1>&2
    exit 2
fi

builddir="$1"
outdir="$builddir/tap"
rm -rf "$outdir"
mkdir "$outdir"

# Write one test script per test method so that they can be run in separate
# processes. The scripts are in Perl, since that's what prove uses by default.
find "$builddir" -type f -name 'dp*_*_test' | while read -r executable; do
    "$executable" list | while read -r test_name; do
        script_path="$outdir/$(basename "$executable")_$test_name.t"
        echo "exec '$executable', '--include=$test_name';" >"$script_path"
        echo 'die "exec: $!";' >>"$script_path"
    done
done

echo
echo "Test scripts written to $outdir."
echo
echo 'You can run these through prove using:'
echo "    prove $outdir"
echo
