#!/bin/sh
# Copyright (c) 2022 askmeaboutloom
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
set -e
cd "$(dirname "$0")/.."

status() {
    echo 1>&2
    echo "=> $@" 1>&2
    echo 1>&2
}

basedir="$(pwd)/generators/protogen"
envdir="$basedir/env"
envactivate="$envdir/bin/activate"
reqpath="$basedir/requirements.txt"
protopath="$basedir/protocol.yaml"

if [ -e "$envdir" ]; then
    status "Activating existing Python virtual environment at $envdir"
    . "$envactivate"
else
    status "Setting up Python virtual environment at $envdir"
    python3 -m venv "$envdir"

    status "Activating new Python virtual environment at $envdir"
    . "$envactivate"

    status "Installing Python dependencies from $reqpath"
    pip install -r "$reqpath"
fi

PYTHONPATH="$basedir"
export PYTHONPATH

status "Generating code from $protopath"
generators/protogen/protogen_drawdance.py libmsg/dpmsg "$protopath"

status "Formatting generated code"
clang-format -i libmsg/dpmsg/messages.c libmsg/dpmsg/messages.h
