// SPDX-License-Identifier: GPL-3.0-or-later
// This file is auto-generated by configen.py, do not edit it manually.
#ifndef LIBCLIENT_CONFIG_SETTINGSCONFIG_H
#define LIBCLIENT_CONFIG_SETTINGSCONFIG_H
#include "libclient/config/config.h"

namespace desktop {
namespace settings {
class Settings;
}
}

namespace config {

class SettingsConfig : public Config {
	Q_OBJECT
public:
	explicit SettingsConfig(
		desktop::settings::Settings *settings, QObject *parent = nullptr);

	QString path() const override;

	bool submit() override;

	int getActionBar() const override;
	void setActionBar(int value) override;

	int getActionBarLocation() const override;
	void setActionBarLocation(int value) override;

	int getAlphaLockCursor() const override;
	void setAlphaLockCursor(int value) override;

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	bool getAndroidScalingAskOnStartup() const override;
	void setAndroidScalingAskOnStartup(bool value) override;
#endif

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	double getAndroidScalingLastInitialScale() const override;
	void setAndroidScalingLastInitialScale(double value) override;
#endif

#if defined(Q_OS_ANDROID) && defined(KRITA_QT_SCREEN_DENSITY_ADJUSTMENT)
	double getAndroidScalingTargetScale() const override;
	void setAndroidScalingTargetScale(double value) override;
#endif

#if defined(KRITA_QATTRIBUTE_ANDROID_EMULATE_MOUSE_BUTTONS_FOR_PAGE_UP_DOWN)
	bool getAndroidWorkaroundEmulateMouseButtonsForPageUpDown() const override;
	void
	setAndroidWorkaroundEmulateMouseButtonsForPageUpDown(bool value) override;
#endif

#if defined(KRITA_QATTRIBUTE_ANDROID_IGNORE_HISTORIC_TABLET_EVENTS)
	bool getAndroidWorkaroundIgnoreHistoricTabletEvents() const override;
	void setAndroidWorkaroundIgnoreHistoricTabletEvents(bool value) override;
#endif

	int getAnimationExportFormat() const override;
	void setAnimationExportFormat(int value) override;

	bool getAutoRecordHost() const override;
	void setAutoRecordHost(bool value) override;

	bool getAutoRecordJoin() const override;
	void setAutoRecordJoin(bool value) override;

	int getAutoRecordMetadataIntervalMinutes() const override;
	void setAutoRecordMetadataIntervalMinutes(int value) override;

	int getAutoRecordSnapshotIntervalMinutes() const override;
	void setAutoRecordSnapshotIntervalMinutes(int value) override;

	int getAutomaticAlphaPreserve() const override;
	void setAutomaticAlphaPreserve(int value) override;

	int getBrushCursor() const override;
	void setBrushCursor(int value) override;

	double getBrushOutlineWidth() const override;
	void setBrushOutlineWidth(double value) override;

	bool getBrushPresetsAttach() const override;
	void setBrushPresetsAttach(bool value) override;

	int getBrushSlotCount() const override;
	void setBrushSlotCount(int value) override;

	bool getCancelDeselects() const override;
	void setCancelDeselects(bool value) override;

	bool getCanvasScrollBars() const override;
	void setCanvasScrollBars(bool value) override;

	QVariantMap getCanvasShortcuts() const override;
	void setCanvasShortcuts(const QVariantMap &value) override;

	QColor getCanvasViewBackgroundColor() const override;
	void setCanvasViewBackgroundColor(const QColor &value) override;

#if defined(Q_OS_ANDROID)
	bool getCaptureVolumeRocker() const override;
	void setCaptureVolumeRocker(bool value) override;
#endif

	QColor getCheckerColor1() const override;
	void setCheckerColor1(const QColor &value) override;

	QColor getCheckerColor2() const override;
	void setCheckerColor2(const QColor &value) override;

	int getColorCircleGamutMaskAngle() const override;
	void setColorCircleGamutMaskAngle(int value) override;

	double getColorCircleGamutMaskOpacity() const override;
	void setColorCircleGamutMaskOpacity(double value) override;

	QString getColorCircleGamutMaskPath() const override;
	void setColorCircleGamutMaskPath(const QString &value) override;

	int getColorCircleHueAngle() const override;
	void setColorCircleHueAngle(int value) override;

	int getColorCircleHueCount() const override;
	void setColorCircleHueCount(int value) override;

	bool getColorCircleHueLimit() const override;
	void setColorCircleHueLimit(bool value) override;

	int getColorCircleSaturationCount() const override;
	void setColorCircleSaturationCount(int value) override;

	bool getColorCircleSaturationLimit() const override;
	void setColorCircleSaturationLimit(bool value) override;

	int getColorCircleValueCount() const override;
	void setColorCircleValueCount(int value) override;

	bool getColorCircleValueLimit() const override;
	void setColorCircleValueLimit(bool value) override;

	int getColorShadesBorderThickness() const override;
	void setColorShadesBorderThickness(int value) override;

	int getColorShadesColumnCount() const override;
	void setColorShadesColumnCount(int value) override;

	QVariantList getColorShadesConfig() const override;
	void setColorShadesConfig(const QVariantList &value) override;

	bool getColorShadesEnabled() const override;
	void setColorShadesEnabled(bool value) override;

	int getColorShadesRowHeight() const override;
	void setColorShadesRowHeight(int value) override;

	int getColorSlidersMode() const override;
	void setColorSlidersMode(int value) override;

	bool getColorSlidersShowAll() const override;
	void setColorSlidersShowAll(bool value) override;

	bool getColorSlidersShowInput() const override;
	void setColorSlidersShowInput(bool value) override;

	int getColorSwatchFlags() const override;
	void setColorSwatchFlags(int value) override;

	int getColorWheelAlign() const override;
	void setColorWheelAlign(int value) override;

	int getColorWheelAngle() const override;
	void setColorWheelAngle(int value) override;

	bool getColorWheelMirror() const override;
	void setColorWheelMirror(bool value) override;

	int getColorWheelPreview() const override;
	void setColorWheelPreview(int value) override;

	int getColorWheelShape() const override;
	void setColorWheelShape(int value) override;

	int getColorWheelSpace() const override;
	void setColorWheelSpace(int value) override;

	bool getCompactChat() const override;
	void setCompactChat(bool value) override;

	bool getConfirmLayerDelete() const override;
	void setConfirmLayerDelete(bool value) override;

#if defined(Q_OS_ANDROID) && defined(DRAWPILE_USE_CONNECT_SERVICE)
	bool getConnectionNotification() const override;
	void setConnectionNotification(bool value) override;
#endif

	QVector<QVariantMap> getCurvesPresets() const override;
	void setCurvesPresets(const QVector<QVariantMap> &value) override;

	int getDebounceDelayMs() const override;
	void setDebounceDelayMs(int value) override;

	bool getDonationLinksEnabled() const override;
	void setDonationLinksEnabled(bool value) override;

	bool getDoubleTapAltToFocusCanvas() const override;
	void setDoubleTapAltToFocusCanvas(bool value) override;

	int getEngineFrameRate() const override;
	void setEngineFrameRate(int value) override;

	int getEngineSnapshotCount() const override;
	void setEngineSnapshotCount(int value) override;

	int getEngineSnapshotInterval() const override;
	void setEngineSnapshotInterval(int value) override;

	int getEngineUndoDepth() const override;
	void setEngineUndoDepth(int value) override;

	int getEraseCursor() const override;
	void setEraseCursor(int value) override;

	bool getFilterClosed() const override;
	void setFilterClosed(bool value) override;

	bool getFilterDuplicates() const override;
	void setFilterDuplicates(bool value) override;

	bool getFilterInactive() const override;
	void setFilterInactive(bool value) override;

	bool getFilterLocked() const override;
	void setFilterLocked(bool value) override;

	bool getFilterNsfm() const override;
	void setFilterNsfm(bool value) override;

	bool getFlipbookUpscaling() const override;
	void setFlipbookUpscaling(bool value) override;

	QRect getFlipbookWindow() const override;
	void setFlipbookWindow(const QRect &value) override;

	int getFontSize() const override;
	void setFontSize(int value) override;

	int getFourFingerTap() const override;
	void setFourFingerTap(int value) override;

	QString getGlobalPressureCurve() const override;
	void setGlobalPressureCurve(const QString &value) override;

	QString getGlobalPressureCurveEraser() const override;
	void setGlobalPressureCurveEraser(const QString &value) override;

	int getGlobalPressureCurveMode() const override;
	void setGlobalPressureCurveMode(int value) override;

	bool getHostEnableAdvanced() const override;
	void setHostEnableAdvanced(bool value) override;

	bool getIgnoreCarrierGradeNat() const override;
	void setIgnoreCarrierGradeNat(bool value) override;

	QVector<QVariantMap> getInputPresets() const override;
	void setInputPresets(const QVector<QVariantMap> &value) override;

	bool getInsecurePasswordStorage() const override;
	void setInsecurePasswordStorage(bool value) override;

	int getInterfaceMode() const override;
	void setInterfaceMode(int value) override;

	bool getInterpolateInputs() const override;
	void setInterpolateInputs(bool value) override;

	bool getInviteIncludePassword() const override;
	void setInviteIncludePassword(bool value) override;

	int getKineticScrollGesture() const override;
	void setKineticScrollGesture(int value) override;

	bool getKineticScrollHideBars() const override;
	void setKineticScrollHideBars(bool value) override;

	int getKineticScrollThreshold() const override;
	void setKineticScrollThreshold(int value) override;

	QString getLanguage() const override;
	void setLanguage(const QString &value) override;

	bool getLastAnnounce() const override;
	void setLastAnnounce(bool value) override;

	QString getLastAvatar() const override;
	void setLastAvatar(const QString &value) override;

	int getLastBrowseSortColumn() const override;
	void setLastBrowseSortColumn(int value) override;

	int getLastBrowseSortDirection() const override;
	void setLastBrowseSortDirection(int value) override;

	QString getLastFileOpenPath() const override;
	void setLastFileOpenPath(const QString &value) override;

	QVariantMap getLastFileOpenPaths() const override;
	void setLastFileOpenPaths(const QVariantMap &value) override;

	int getLastHostServer() const override;
	void setLastHostServer(int value) override;

	int getLastHostType() const override;
	void setLastHostType(int value) override;

	QString getLastIdAlias() const override;
	void setLastIdAlias(const QString &value) override;

	QString getLastJoinAddress() const override;
	void setLastJoinAddress(const QString &value) override;

	bool getLastKeepChat() const override;
	void setLastKeepChat(bool value) override;

	QStringList getLastListingUrls() const override;
	void setLastListingUrls(const QStringList &value) override;

	bool getLastNsfm() const override;
	void setLastNsfm(bool value) override;

	int getLastPalette() const override;
	void setLastPalette(int value) override;

	QByteArray getLastSessionAuthList() const override;
	void setLastSessionAuthList(const QByteArray &value) override;

	bool getLastSessionAutomatic() const override;
	void setLastSessionAutomatic(bool value) override;

	QByteArray getLastSessionBanList() const override;
	void setLastSessionBanList(const QByteArray &value) override;

	QString getLastSessionOpPassword() const override;
	void setLastSessionOpPassword(const QString &value) override;

	QString getLastSessionPassword() const override;
	void setLastSessionPassword(const QString &value) override;

	QVariantMap getLastSessionPermissions() const override;
	void setLastSessionPermissions(const QVariantMap &value) override;

	QString getLastSessionTitle() const override;
	void setLastSessionTitle(const QString &value) override;

	int getLastSessionUndoDepth() const override;
	void setLastSessionUndoDepth(int value) override;

	QString getLastStartDialogDateTime() const override;
	void setLastStartDialogDateTime(const QString &value) override;

	int getLastStartDialogPage() const override;
	void setLastStartDialogPage(int value) override;

	QSize getLastStartDialogSize() const override;
	void setLastStartDialogSize(const QSize &value) override;

	int getLastTool() const override;
	void setLastTool(int value) override;

	QColor getLastToolBackgroundColor() const override;
	void setLastToolBackgroundColor(const QColor &value) override;

	QColor getLastToolColor() const override;
	void setLastToolColor(const QColor &value) override;

	QString getLastUsername() const override;
	void setLastUsername(const QString &value) override;

	QMap<QString, bool> getLastWindowActions() const override;
	void setLastWindowActions(const QMap<QString, bool> &value) override;

	QVariantMap getLastWindowDocks() const override;
	void setLastWindowDocks(const QVariantMap &value) override;

	bool getLastWindowMaximized() const override;
	void setLastWindowMaximized(bool value) override;

	QPoint getLastWindowPosition() const override;
	void setLastWindowPosition(const QPoint &value) override;

	QSize getLastWindowSize() const override;
	void setLastWindowSize(const QSize &value) override;

	QByteArray getLastWindowState() const override;
	void setLastWindowState(const QByteArray &value) override;

	QByteArray getLastWindowViewState() const override;
	void setLastWindowViewState(const QByteArray &value) override;

	int getLayerSketchOpacityPercent() const override;
	void setLayerSketchOpacityPercent(int value) override;

	QColor getLayerSketchTint() const override;
	void setLayerSketchTint(const QColor &value) override;

	QVector<QVariantMap> getLayouts() const override;
	void setLayouts(const QVector<QVariantMap> &value) override;

	int getLayoutsVersion() const override;
	void setLayoutsVersion(int value) override;

	bool getLeftyMode() const override;
	void setLeftyMode(bool value) override;

	QVector<QVariantMap> getListServers() const override;
	void setListServers(const QVector<QVariantMap> &value) override;

	bool getLongPressEnabled() const override;
	void setLongPressEnabled(bool value) override;

	bool getMentionEnabled() const override;
	void setMentionEnabled(bool value) override;

	QString getMentionTriggerList() const override;
	void setMentionTriggerList(const QString &value) override;

	int getMessageQueueDrainRate() const override;
	void setMessageQueueDrainRate(int value) override;

	bool getMouseSmoothing() const override;
	void setMouseSmoothing(bool value) override;

#if defined(NATIVE_DIALOGS_SETTING_AVAILABLE)
	bool getNativeDialogs() const override;
	void setNativeDialogs(bool value) override;
#endif

	bool getNavigatorRealtime() const override;
	void setNavigatorRealtime(bool value) override;

	bool getNavigatorShowCursors() const override;
	void setNavigatorShowCursors(bool value) override;

	int getNetworkProxyMode() const override;
	void setNetworkProxyMode(int value) override;

	QColor getNewCanvasBackColor() const override;
	void setNewCanvasBackColor(const QColor &value) override;

	QSize getNewCanvasSize() const override;
	void setNewCanvasSize(const QSize &value) override;

	bool getNotifFlashChat() const override;
	void setNotifFlashChat(bool value) override;

	bool getNotifFlashDisconnect() const override;
	void setNotifFlashDisconnect(bool value) override;

	bool getNotifFlashLock() const override;
	void setNotifFlashLock(bool value) override;

	bool getNotifFlashLogin() const override;
	void setNotifFlashLogin(bool value) override;

	bool getNotifFlashLogout() const override;
	void setNotifFlashLogout(bool value) override;

	bool getNotifFlashPrivateChat() const override;
	void setNotifFlashPrivateChat(bool value) override;

	bool getNotifFlashUnlock() const override;
	void setNotifFlashUnlock(bool value) override;

	bool getNotifPopupChat() const override;
	void setNotifPopupChat(bool value) override;

	bool getNotifPopupDisconnect() const override;
	void setNotifPopupDisconnect(bool value) override;

	bool getNotifPopupLock() const override;
	void setNotifPopupLock(bool value) override;

	bool getNotifPopupLogin() const override;
	void setNotifPopupLogin(bool value) override;

	bool getNotifPopupLogout() const override;
	void setNotifPopupLogout(bool value) override;

	bool getNotifPopupPrivateChat() const override;
	void setNotifPopupPrivateChat(bool value) override;

	bool getNotifPopupUnlock() const override;
	void setNotifPopupUnlock(bool value) override;

	bool getNotifSoundChat() const override;
	void setNotifSoundChat(bool value) override;

	bool getNotifSoundDisconnect() const override;
	void setNotifSoundDisconnect(bool value) override;

	bool getNotifSoundLock() const override;
	void setNotifSoundLock(bool value) override;

	bool getNotifSoundLogin() const override;
	void setNotifSoundLogin(bool value) override;

	bool getNotifSoundLogout() const override;
	void setNotifSoundLogout(bool value) override;

	bool getNotifSoundPrivateChat() const override;
	void setNotifSoundPrivateChat(bool value) override;

	bool getNotifSoundUnlock() const override;
	void setNotifSoundUnlock(bool value) override;

	int getOneFingerTap() const override;
	void setOneFingerTap(int value) override;

	int getOneFingerTapAndHold() const override;
	void setOneFingerTapAndHold(int value) override;

	int getOneFingerTouch() const override;
	void setOneFingerTouch(int value) override;

	int getOnionSkinsFrameCount() const override;
	void setOnionSkinsFrameCount(int value) override;

	QMap<int, int> getOnionSkinsFrames() const override;
	void setOnionSkinsFrames(const QMap<int, int> &value) override;

	QColor getOnionSkinsTintAbove() const override;
	void setOnionSkinsTintAbove(const QColor &value) override;

	QColor getOnionSkinsTintBelow() const override;
	void setOnionSkinsTintBelow(const QColor &value) override;

	bool getOnionSkinsWrap() const override;
	void setOnionSkinsWrap(bool value) override;

	bool getOverrideFontSize() const override;
	void setOverrideFontSize(bool value) override;

	bool getParentalControlsAutoTag() const override;
	void setParentalControlsAutoTag(bool value) override;

	bool getParentalControlsForceCensor() const override;
	void setParentalControlsForceCensor(bool value) override;

	bool getParentalControlsHideLocked() const override;
	void setParentalControlsHideLocked(bool value) override;

	int getParentalControlsLevel() const override;
	void setParentalControlsLevel(int value) override;

	QByteArray getParentalControlsLocked() const override;
	void setParentalControlsLocked(const QByteArray &value) override;

	QString getParentalControlsTags() const override;
	void setParentalControlsTags(const QString &value) override;

	QString getPreferredExportFormat() const override;
	void setPreferredExportFormat(const QString &value) override;

	QString getPreferredSaveFormat() const override;
	void setPreferredSaveFormat(const QString &value) override;

	bool getPromptLayerCreate() const override;
	void setPromptLayerCreate(bool value) override;

#if defined(Q_OS_MACOS)
	bool getQuitOnLastWindowClosed() const override;
	void setQuitOnLastWindowClosed(bool value) override;
#endif

	QStringList getRecentFiles() const override;
	void setRecentFiles(const QStringList &value) override;

	QStringList getRecentHosts() const override;
	void setRecentHosts(const QStringList &value) override;

	QStringList getRecentRemoteHosts() const override;
	void setRecentRemoteHosts(const QStringList &value) override;

	int getRenderCanvas() const override;
	void setRenderCanvas(int value) override;

	bool getRenderSmooth() const override;
	void setRenderSmooth(bool value) override;

	bool getRenderUpdateFull() const override;
	void setRenderUpdateFull(bool value) override;

	int getSamplingRingVisibility() const override;
	void setSamplingRingVisibility(int value) override;

	QColor getSelectionColor() const override;
	void setSelectionColor(const QColor &value) override;

	bool getServerAutoReset() const override;
	void setServerAutoReset(bool value) override;

	bool getServerHideIp() const override;
	void setServerHideIp(bool value) override;

	int getServerPort() const override;
	void setServerPort(int value) override;

	int getServerTimeout() const override;
	void setServerTimeout(int value) override;

	bool getShareBrushSlotColor() const override;
	void setShareBrushSlotColor(bool value) override;

	QVariantMap getShortcuts() const override;
	void setShortcuts(const QVariantMap &value) override;

	bool getShowInviteDialogOnHost() const override;
	void setShowInviteDialogOnHost(bool value) override;

	bool getShowNsfmWarningOnJoin() const override;
	void setShowNsfmWarningOnJoin(bool value) override;

	bool getShowTransformNotices() const override;
	void setShowTransformNotices(bool value) override;

	bool getShowTrayIcon() const override;
	void setShowTrayIcon(bool value) override;

	bool getShowViewModeNotices() const override;
	void setShowViewModeNotices(bool value) override;

	int getSmoothing() const override;
	void setSmoothing(int value) override;

	int getSoundVolume() const override;
	void setSoundVolume(int value) override;

	int getTabletDriver() const override;
	void setTabletDriver(int value) override;

	int getTabletEraserAction() const override;
	void setTabletEraserAction(int value) override;

	bool getTabletEvents() const override;
	void setTabletEvents(bool value) override;

	int getTabletPressTimerDelay() const override;
	void setTabletPressTimerDelay(int value) override;

	bool getTemporaryToolSwitch() const override;
	void setTemporaryToolSwitch(bool value) override;

	int getTemporaryToolSwitchMs() const override;
	void setTemporaryToolSwitchMs(int value) override;

	QString getThemePalette() const override;
	void setThemePalette(const QString &value) override;

	QString getThemeStyle() const override;
	void setThemeStyle(const QString &value) override;

	int getThreeFingerTap() const override;
	void setThreeFingerTap(int value) override;

	QColor getTimelapseBackdropColor() const override;
	void setTimelapseBackdropColor(const QColor &value) override;

	int getTimelapseDurationSeconds() const override;
	void setTimelapseDurationSeconds(int value) override;

	int getTimelapseExportFormat() const override;
	void setTimelapseExportFormat(int value) override;

	QColor getTimelapseFlashColor() const override;
	void setTimelapseFlashColor(const QColor &value) override;

	int getTimelapseFlashSeconds() const override;
	void setTimelapseFlashSeconds(int value) override;

	double getTimelapseFramerate() const override;
	void setTimelapseFramerate(double value) override;

	int getTimelapseInterpolation() const override;
	void setTimelapseInterpolation(int value) override;

	int getTimelapseLingerAfterLoops() const override;
	void setTimelapseLingerAfterLoops(int value) override;

	int getTimelapseLingerAfterSeconds() const override;
	void setTimelapseLingerAfterSeconds(int value) override;

	int getTimelapseLingerBeforeLoops() const override;
	void setTimelapseLingerBeforeLoops(int value) override;

	int getTimelapseLingerBeforeSeconds() const override;
	void setTimelapseLingerBeforeSeconds(int value) override;

	int getTimelapseLogoLocation() const override;
	void setTimelapseLogoLocation(int value) override;

	double getTimelapseLogoOffset() const override;
	void setTimelapseLogoOffset(double value) override;

	int getTimelapseLogoOpacity() const override;
	void setTimelapseLogoOpacity(int value) override;

	double getTimelapseLogoScale() const override;
	void setTimelapseLogoScale(double value) override;

	double getTimelapseMaxDeltaSeconds() const override;
	void setTimelapseMaxDeltaSeconds(double value) override;

	int getTimelapseMaxQueueEntries() const override;
	void setTimelapseMaxQueueEntries(int value) override;

	bool getTimelapseShowAdvanced() const override;
	void setTimelapseShowAdvanced(bool value) override;

	bool getTimelapseTimeOwnOnly() const override;
	void setTimelapseTimeOwnOnly(bool value) override;

	QVariantHash getToolBarConfig() const override;
	void setToolBarConfig(const QVariantHash &value) override;

	bool getToolToggle() const override;
	void setToolToggle(bool value) override;

	QMap<QString, QVariantHash> getToolset() const override;
	void setToolset(const QMap<QString, QVariantHash> &value) override;

	bool getTouchDrawPressure() const override;
	void setTouchDrawPressure(bool value) override;

	bool getTouchGestures() const override;
	void setTouchGestures(bool value) override;

	int getTouchSmoothing() const override;
	void setTouchSmoothing(int value) override;

	int getTwoFingerPinch() const override;
	void setTwoFingerPinch(int value) override;

	int getTwoFingerTap() const override;
	void setTwoFingerTap(int value) override;

	int getTwoFingerTwist() const override;
	void setTwoFingerTwist(int value) override;

	bool getUpdateCheckEnabled() const override;
	void setUpdateCheckEnabled(bool value) override;

	bool getUseMipmaps() const override;
	void setUseMipmaps(bool value) override;

	int getUserMarkerPersistence() const override;
	void setUserMarkerPersistence(int value) override;

	QString getVideoExportCustomFfmpeg() const override;
	void setVideoExportCustomFfmpeg(const QString &value) override;

	QString getVideoExportFfmpegPath() const override;
	void setVideoExportFfmpegPath(const QString &value) override;

	int getVideoExportFormat() const override;
	void setVideoExportFormat(int value) override;

	int getVideoExportFrameHeight() const override;
	void setVideoExportFrameHeight(int value) override;

	int getVideoExportFrameRate() const override;
	void setVideoExportFrameRate(int value) override;

	int getVideoExportFrameWidth() const override;
	void setVideoExportFrameWidth(int value) override;

	int getVideoExportSizeChoice() const override;
	void setVideoExportSizeChoice(int value) override;

	bool getWelcomePageShown() const override;
	void setWelcomePageShown(bool value) override;

	bool getWriteLogFile() const override;
	void setWriteLogFile(bool value) override;

private:
	desktop::settings::Settings *m_settings;
};

}

#endif
