// SPDX-License-Identifier: GPL-3.0-or-later
// This file is auto-generated by configen.py, do not edit it manually.
#include "desktop/config/settingsconfig.h"
#include "desktop/settings.h"

namespace config {

SettingsConfig::SettingsConfig(
	desktop::settings::Settings *settings, QObject *parent)
	: Config(parent)
	, m_settings(settings)
{
	connect(
		m_settings, &desktop::settings::Settings::actionBarChanged, this,
		&SettingsConfig::changeActionBar, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::actionBarLocationChanged,
		this, &SettingsConfig::changeActionBarLocation, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::alphaLockCursorChanged, this,
		&SettingsConfig::changeAlphaLockCursor, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::animationExportFormatChanged,
		this, &SettingsConfig::changeAnimationExportFormat,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::autoRecordHostChanged, this,
		&SettingsConfig::changeAutoRecordHost, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::autoRecordJoinChanged, this,
		&SettingsConfig::changeAutoRecordJoin, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::autoRecordMetadataIntervalMinutesChanged,
		this, &SettingsConfig::changeAutoRecordMetadataIntervalMinutes,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::autoRecordSnapshotIntervalMinutesChanged,
		this, &SettingsConfig::changeAutoRecordSnapshotIntervalMinutes,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::automaticAlphaPreserveChanged,
		this, &SettingsConfig::changeAutomaticAlphaPreserve,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::brushCursorChanged, this,
		&SettingsConfig::changeBrushCursor, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::brushOutlineWidthChanged,
		this, &SettingsConfig::changeBrushOutlineWidth, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::brushPresetsAttachChanged,
		this, &SettingsConfig::changeBrushPresetsAttach, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::brushSlotCountChanged, this,
		&SettingsConfig::changeBrushSlotCount, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::cancelDeselectsChanged, this,
		&SettingsConfig::changeCancelDeselects, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::canvasScrollBarsChanged, this,
		&SettingsConfig::changeCanvasScrollBars, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::canvasShortcutsChanged, this,
		&SettingsConfig::changeCanvasShortcuts, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::canvasViewBackgroundColorChanged, this,
		&SettingsConfig::changeCanvasViewBackgroundColor, Qt::DirectConnection);
#if defined(Q_OS_ANDROID)
	connect(
		m_settings, &desktop::settings::Settings::captureVolumeRockerChanged,
		this, &SettingsConfig::changeCaptureVolumeRocker, Qt::DirectConnection);
#endif
	connect(
		m_settings, &desktop::settings::Settings::checkerColor1Changed, this,
		&SettingsConfig::changeCheckerColor1, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::checkerColor2Changed, this,
		&SettingsConfig::changeCheckerColor2, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::colorCircleGamutMaskAngleChanged, this,
		&SettingsConfig::changeColorCircleGamutMaskAngle, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::colorCircleGamutMaskOpacityChanged, this,
		&SettingsConfig::changeColorCircleGamutMaskOpacity,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::colorCircleGamutMaskPathChanged, this,
		&SettingsConfig::changeColorCircleGamutMaskPath, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorCircleHueAngleChanged,
		this, &SettingsConfig::changeColorCircleHueAngle, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorCircleHueCountChanged,
		this, &SettingsConfig::changeColorCircleHueCount, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorCircleHueLimitChanged,
		this, &SettingsConfig::changeColorCircleHueLimit, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::colorCircleSaturationCountChanged, this,
		&SettingsConfig::changeColorCircleSaturationCount,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::colorCircleSaturationLimitChanged, this,
		&SettingsConfig::changeColorCircleSaturationLimit,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorCircleValueCountChanged,
		this, &SettingsConfig::changeColorCircleValueCount,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorCircleValueLimitChanged,
		this, &SettingsConfig::changeColorCircleValueLimit,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::colorShadesBorderThicknessChanged, this,
		&SettingsConfig::changeColorShadesBorderThickness,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorShadesColumnCountChanged,
		this, &SettingsConfig::changeColorShadesColumnCount,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorShadesConfigChanged,
		this, &SettingsConfig::changeColorShadesConfig, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorShadesEnabledChanged,
		this, &SettingsConfig::changeColorShadesEnabled, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorShadesRowHeightChanged,
		this, &SettingsConfig::changeColorShadesRowHeight,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorSlidersModeChanged, this,
		&SettingsConfig::changeColorSlidersMode, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorSlidersShowAllChanged,
		this, &SettingsConfig::changeColorSlidersShowAll, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorSlidersShowInputChanged,
		this, &SettingsConfig::changeColorSlidersShowInput,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorSwatchFlagsChanged, this,
		&SettingsConfig::changeColorSwatchFlags, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorWheelAlignChanged, this,
		&SettingsConfig::changeColorWheelAlign, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorWheelAngleChanged, this,
		&SettingsConfig::changeColorWheelAngle, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorWheelMirrorChanged, this,
		&SettingsConfig::changeColorWheelMirror, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorWheelPreviewChanged,
		this, &SettingsConfig::changeColorWheelPreview, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorWheelShapeChanged, this,
		&SettingsConfig::changeColorWheelShape, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::colorWheelSpaceChanged, this,
		&SettingsConfig::changeColorWheelSpace, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::compactChatChanged, this,
		&SettingsConfig::changeCompactChat, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::confirmLayerDeleteChanged,
		this, &SettingsConfig::changeConfirmLayerDelete, Qt::DirectConnection);
#if defined(Q_OS_ANDROID) && defined(DRAWPILE_USE_CONNECT_SERVICE)
	connect(
		m_settings, &desktop::settings::Settings::connectionNotificationChanged,
		this, &SettingsConfig::changeConnectionNotification,
		Qt::DirectConnection);
#endif
	connect(
		m_settings, &desktop::settings::Settings::curvesPresetsChanged, this,
		&SettingsConfig::changeCurvesPresets, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::debounceDelayMsChanged, this,
		&SettingsConfig::changeDebounceDelayMs, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::donationLinksEnabledChanged,
		this, &SettingsConfig::changeDonationLinksEnabled,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::doubleTapAltToFocusCanvasChanged, this,
		&SettingsConfig::changeDoubleTapAltToFocusCanvas, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::engineFrameRateChanged, this,
		&SettingsConfig::changeEngineFrameRate, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::engineSnapshotCountChanged,
		this, &SettingsConfig::changeEngineSnapshotCount, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::engineSnapshotIntervalChanged,
		this, &SettingsConfig::changeEngineSnapshotInterval,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::engineUndoDepthChanged, this,
		&SettingsConfig::changeEngineUndoDepth, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::eraseCursorChanged, this,
		&SettingsConfig::changeEraseCursor, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::filterClosedChanged, this,
		&SettingsConfig::changeFilterClosed, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::filterDuplicatesChanged, this,
		&SettingsConfig::changeFilterDuplicates, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::filterInactiveChanged, this,
		&SettingsConfig::changeFilterInactive, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::filterLockedChanged, this,
		&SettingsConfig::changeFilterLocked, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::filterNsfmChanged, this,
		&SettingsConfig::changeFilterNsfm, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::flipbookUpscalingChanged,
		this, &SettingsConfig::changeFlipbookUpscaling, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::flipbookWindowChanged, this,
		&SettingsConfig::changeFlipbookWindow, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::fontSizeChanged, this,
		&SettingsConfig::changeFontSize, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::fourFingerTapChanged, this,
		&SettingsConfig::changeFourFingerTap, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::globalPressureCurveChanged,
		this, &SettingsConfig::changeGlobalPressureCurve, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::globalPressureCurveEraserChanged, this,
		&SettingsConfig::changeGlobalPressureCurveEraser, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::globalPressureCurveModeChanged, this,
		&SettingsConfig::changeGlobalPressureCurveMode, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::hostEnableAdvancedChanged,
		this, &SettingsConfig::changeHostEnableAdvanced, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::ignoreCarrierGradeNatChanged,
		this, &SettingsConfig::changeIgnoreCarrierGradeNat,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::inputPresetsChanged, this,
		&SettingsConfig::changeInputPresets, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::insecurePasswordStorageChanged, this,
		&SettingsConfig::changeInsecurePasswordStorage, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::interfaceModeChanged, this,
		&SettingsConfig::changeInterfaceMode, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::interpolateInputsChanged,
		this, &SettingsConfig::changeInterpolateInputs, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::inviteIncludePasswordChanged,
		this, &SettingsConfig::changeInviteIncludePassword,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::kineticScrollGestureChanged,
		this, &SettingsConfig::changeKineticScrollGesture,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::kineticScrollHideBarsChanged,
		this, &SettingsConfig::changeKineticScrollHideBars,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::kineticScrollThresholdChanged,
		this, &SettingsConfig::changeKineticScrollThreshold,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::languageChanged, this,
		&SettingsConfig::changeLanguage, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastAnnounceChanged, this,
		&SettingsConfig::changeLastAnnounce, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastAvatarChanged, this,
		&SettingsConfig::changeLastAvatar, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastBrowseSortColumnChanged,
		this, &SettingsConfig::changeLastBrowseSortColumn,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::lastBrowseSortDirectionChanged, this,
		&SettingsConfig::changeLastBrowseSortDirection, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastFileOpenPathChanged, this,
		&SettingsConfig::changeLastFileOpenPath, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastFileOpenPathsChanged,
		this, &SettingsConfig::changeLastFileOpenPaths, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastHostServerChanged, this,
		&SettingsConfig::changeLastHostServer, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastHostTypeChanged, this,
		&SettingsConfig::changeLastHostType, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastIdAliasChanged, this,
		&SettingsConfig::changeLastIdAlias, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastJoinAddressChanged, this,
		&SettingsConfig::changeLastJoinAddress, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastKeepChatChanged, this,
		&SettingsConfig::changeLastKeepChat, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastListingUrlsChanged, this,
		&SettingsConfig::changeLastListingUrls, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastNsfmChanged, this,
		&SettingsConfig::changeLastNsfm, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastPaletteChanged, this,
		&SettingsConfig::changeLastPalette, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastSessionAuthListChanged,
		this, &SettingsConfig::changeLastSessionAuthList, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastSessionAutomaticChanged,
		this, &SettingsConfig::changeLastSessionAutomatic,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastSessionBanListChanged,
		this, &SettingsConfig::changeLastSessionBanList, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastSessionOpPasswordChanged,
		this, &SettingsConfig::changeLastSessionOpPassword,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastSessionPasswordChanged,
		this, &SettingsConfig::changeLastSessionPassword, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastSessionPermissionsChanged,
		this, &SettingsConfig::changeLastSessionPermissions,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastSessionTitleChanged, this,
		&SettingsConfig::changeLastSessionTitle, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastSessionUndoDepthChanged,
		this, &SettingsConfig::changeLastSessionUndoDepth,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::lastStartDialogDateTimeChanged, this,
		&SettingsConfig::changeLastStartDialogDateTime, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastStartDialogPageChanged,
		this, &SettingsConfig::changeLastStartDialogPage, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastStartDialogSizeChanged,
		this, &SettingsConfig::changeLastStartDialogSize, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastToolChanged, this,
		&SettingsConfig::changeLastTool, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::lastToolBackgroundColorChanged, this,
		&SettingsConfig::changeLastToolBackgroundColor, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastToolColorChanged, this,
		&SettingsConfig::changeLastToolColor, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastUsernameChanged, this,
		&SettingsConfig::changeLastUsername, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastWindowActionsChanged,
		this, &SettingsConfig::changeLastWindowActions, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastWindowDocksChanged, this,
		&SettingsConfig::changeLastWindowDocks, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastWindowMaximizedChanged,
		this, &SettingsConfig::changeLastWindowMaximized, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastWindowPositionChanged,
		this, &SettingsConfig::changeLastWindowPosition, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastWindowSizeChanged, this,
		&SettingsConfig::changeLastWindowSize, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastWindowStateChanged, this,
		&SettingsConfig::changeLastWindowState, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::lastWindowViewStateChanged,
		this, &SettingsConfig::changeLastWindowViewState, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::layerSketchOpacityPercentChanged, this,
		&SettingsConfig::changeLayerSketchOpacityPercent, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::layerSketchTintChanged, this,
		&SettingsConfig::changeLayerSketchTint, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::layoutsChanged, this,
		&SettingsConfig::changeLayouts, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::layoutsVersionChanged, this,
		&SettingsConfig::changeLayoutsVersion, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::leftyModeChanged, this,
		&SettingsConfig::changeLeftyMode, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::listServersChanged, this,
		&SettingsConfig::changeListServers, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::longPressEnabledChanged, this,
		&SettingsConfig::changeLongPressEnabled, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::mentionEnabledChanged, this,
		&SettingsConfig::changeMentionEnabled, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::mentionTriggerListChanged,
		this, &SettingsConfig::changeMentionTriggerList, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::messageQueueDrainRateChanged,
		this, &SettingsConfig::changeMessageQueueDrainRate,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::mouseSmoothingChanged, this,
		&SettingsConfig::changeMouseSmoothing, Qt::DirectConnection);
#if defined(NATIVE_DIALOGS_SETTING_AVAILABLE)
	connect(
		m_settings, &desktop::settings::Settings::nativeDialogsChanged, this,
		&SettingsConfig::changeNativeDialogs, Qt::DirectConnection);
#endif
	connect(
		m_settings, &desktop::settings::Settings::navigatorRealtimeChanged,
		this, &SettingsConfig::changeNavigatorRealtime, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::navigatorShowCursorsChanged,
		this, &SettingsConfig::changeNavigatorShowCursors,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::networkProxyModeChanged, this,
		&SettingsConfig::changeNetworkProxyMode, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::newCanvasBackColorChanged,
		this, &SettingsConfig::changeNewCanvasBackColor, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::newCanvasSizeChanged, this,
		&SettingsConfig::changeNewCanvasSize, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifFlashChatChanged, this,
		&SettingsConfig::changeNotifFlashChat, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifFlashDisconnectChanged,
		this, &SettingsConfig::changeNotifFlashDisconnect,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifFlashLockChanged, this,
		&SettingsConfig::changeNotifFlashLock, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifFlashLoginChanged, this,
		&SettingsConfig::changeNotifFlashLogin, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifFlashLogoutChanged, this,
		&SettingsConfig::changeNotifFlashLogout, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifFlashPrivateChatChanged,
		this, &SettingsConfig::changeNotifFlashPrivateChat,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifFlashUnlockChanged, this,
		&SettingsConfig::changeNotifFlashUnlock, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifPopupChatChanged, this,
		&SettingsConfig::changeNotifPopupChat, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifPopupDisconnectChanged,
		this, &SettingsConfig::changeNotifPopupDisconnect,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifPopupLockChanged, this,
		&SettingsConfig::changeNotifPopupLock, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifPopupLoginChanged, this,
		&SettingsConfig::changeNotifPopupLogin, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifPopupLogoutChanged, this,
		&SettingsConfig::changeNotifPopupLogout, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifPopupPrivateChatChanged,
		this, &SettingsConfig::changeNotifPopupPrivateChat,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifPopupUnlockChanged, this,
		&SettingsConfig::changeNotifPopupUnlock, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifSoundChatChanged, this,
		&SettingsConfig::changeNotifSoundChat, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifSoundDisconnectChanged,
		this, &SettingsConfig::changeNotifSoundDisconnect,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifSoundLockChanged, this,
		&SettingsConfig::changeNotifSoundLock, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifSoundLoginChanged, this,
		&SettingsConfig::changeNotifSoundLogin, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifSoundLogoutChanged, this,
		&SettingsConfig::changeNotifSoundLogout, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifSoundPrivateChatChanged,
		this, &SettingsConfig::changeNotifSoundPrivateChat,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::notifSoundUnlockChanged, this,
		&SettingsConfig::changeNotifSoundUnlock, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::oneFingerTapChanged, this,
		&SettingsConfig::changeOneFingerTap, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::oneFingerTapAndHoldChanged,
		this, &SettingsConfig::changeOneFingerTapAndHold, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::oneFingerTouchChanged, this,
		&SettingsConfig::changeOneFingerTouch, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::onionSkinsFrameCountChanged,
		this, &SettingsConfig::changeOnionSkinsFrameCount,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::onionSkinsFramesChanged, this,
		&SettingsConfig::changeOnionSkinsFrames, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::onionSkinsTintAboveChanged,
		this, &SettingsConfig::changeOnionSkinsTintAbove, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::onionSkinsTintBelowChanged,
		this, &SettingsConfig::changeOnionSkinsTintBelow, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::onionSkinsWrapChanged, this,
		&SettingsConfig::changeOnionSkinsWrap, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::overrideFontSizeChanged, this,
		&SettingsConfig::changeOverrideFontSize, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::parentalControlsAutoTagChanged, this,
		&SettingsConfig::changeParentalControlsAutoTag, Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::parentalControlsForceCensorChanged, this,
		&SettingsConfig::changeParentalControlsForceCensor,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::parentalControlsHideLockedChanged, this,
		&SettingsConfig::changeParentalControlsHideLocked,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::parentalControlsLevelChanged,
		this, &SettingsConfig::changeParentalControlsLevel,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::parentalControlsLockedChanged,
		this, &SettingsConfig::changeParentalControlsLocked,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::parentalControlsTagsChanged,
		this, &SettingsConfig::changeParentalControlsTags,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::preferredExportFormatChanged,
		this, &SettingsConfig::changePreferredExportFormat,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::preferredSaveFormatChanged,
		this, &SettingsConfig::changePreferredSaveFormat, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::promptLayerCreateChanged,
		this, &SettingsConfig::changePromptLayerCreate, Qt::DirectConnection);
#if defined(Q_OS_MACOS)
	connect(
		m_settings, &desktop::settings::Settings::quitOnLastWindowClosedChanged,
		this, &SettingsConfig::changeQuitOnLastWindowClosed,
		Qt::DirectConnection);
#endif
	connect(
		m_settings, &desktop::settings::Settings::recentFilesChanged, this,
		&SettingsConfig::changeRecentFiles, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::recentHostsChanged, this,
		&SettingsConfig::changeRecentHosts, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::recentRemoteHostsChanged,
		this, &SettingsConfig::changeRecentRemoteHosts, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::renderCanvasChanged, this,
		&SettingsConfig::changeRenderCanvas, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::renderSmoothChanged, this,
		&SettingsConfig::changeRenderSmooth, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::renderUpdateFullChanged, this,
		&SettingsConfig::changeRenderUpdateFull, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::samplingRingVisibilityChanged,
		this, &SettingsConfig::changeSamplingRingVisibility,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::selectionColorChanged, this,
		&SettingsConfig::changeSelectionColor, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::serverAutoResetChanged, this,
		&SettingsConfig::changeServerAutoReset, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::serverHideIpChanged, this,
		&SettingsConfig::changeServerHideIp, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::serverPortChanged, this,
		&SettingsConfig::changeServerPort, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::serverTimeoutChanged, this,
		&SettingsConfig::changeServerTimeout, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::shareBrushSlotColorChanged,
		this, &SettingsConfig::changeShareBrushSlotColor, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::shortcutsChanged, this,
		&SettingsConfig::changeShortcuts, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::showInviteDialogOnHostChanged,
		this, &SettingsConfig::changeShowInviteDialogOnHost,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::showNsfmWarningOnJoinChanged,
		this, &SettingsConfig::changeShowNsfmWarningOnJoin,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::showTransformNoticesChanged,
		this, &SettingsConfig::changeShowTransformNotices,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::showTrayIconChanged, this,
		&SettingsConfig::changeShowTrayIcon, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::showViewModeNoticesChanged,
		this, &SettingsConfig::changeShowViewModeNotices, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::smoothingChanged, this,
		&SettingsConfig::changeSmoothing, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::soundVolumeChanged, this,
		&SettingsConfig::changeSoundVolume, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::tabletDriverChanged, this,
		&SettingsConfig::changeTabletDriver, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::tabletEraserActionChanged,
		this, &SettingsConfig::changeTabletEraserAction, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::tabletEventsChanged, this,
		&SettingsConfig::changeTabletEvents, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::tabletPressTimerDelayChanged,
		this, &SettingsConfig::changeTabletPressTimerDelay,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::temporaryToolSwitchChanged,
		this, &SettingsConfig::changeTemporaryToolSwitch, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::temporaryToolSwitchMsChanged,
		this, &SettingsConfig::changeTemporaryToolSwitchMs,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::themePaletteChanged, this,
		&SettingsConfig::changeThemePalette, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::themeStyleChanged, this,
		&SettingsConfig::changeThemeStyle, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::threeFingerTapChanged, this,
		&SettingsConfig::changeThreeFingerTap, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::toolBarConfigChanged, this,
		&SettingsConfig::changeToolBarConfig, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::toolToggleChanged, this,
		&SettingsConfig::changeToolToggle, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::toolsetChanged, this,
		&SettingsConfig::changeToolset, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::touchDrawPressureChanged,
		this, &SettingsConfig::changeTouchDrawPressure, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::touchGesturesChanged, this,
		&SettingsConfig::changeTouchGestures, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::touchSmoothingChanged, this,
		&SettingsConfig::changeTouchSmoothing, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::twoFingerPinchChanged, this,
		&SettingsConfig::changeTwoFingerPinch, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::twoFingerTapChanged, this,
		&SettingsConfig::changeTwoFingerTap, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::twoFingerTwistChanged, this,
		&SettingsConfig::changeTwoFingerTwist, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::updateCheckEnabledChanged,
		this, &SettingsConfig::changeUpdateCheckEnabled, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::useMipmapsChanged, this,
		&SettingsConfig::changeUseMipmaps, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::userMarkerPersistenceChanged,
		this, &SettingsConfig::changeUserMarkerPersistence,
		Qt::DirectConnection);
	connect(
		m_settings,
		&desktop::settings::Settings::videoExportCustomFfmpegChanged, this,
		&SettingsConfig::changeVideoExportCustomFfmpeg, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::videoExportFfmpegPathChanged,
		this, &SettingsConfig::changeVideoExportFfmpegPath,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::videoExportFormatChanged,
		this, &SettingsConfig::changeVideoExportFormat, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::videoExportFrameHeightChanged,
		this, &SettingsConfig::changeVideoExportFrameHeight,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::videoExportFrameRateChanged,
		this, &SettingsConfig::changeVideoExportFrameRate,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::videoExportFrameWidthChanged,
		this, &SettingsConfig::changeVideoExportFrameWidth,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::videoExportSizeChoiceChanged,
		this, &SettingsConfig::changeVideoExportSizeChoice,
		Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::welcomePageShownChanged, this,
		&SettingsConfig::changeWelcomePageShown, Qt::DirectConnection);
	connect(
		m_settings, &desktop::settings::Settings::writeLogFileChanged, this,
		&SettingsConfig::changeWriteLogFile, Qt::DirectConnection);
}

QString SettingsConfig::path() const
{
	return m_settings->path();
}

bool SettingsConfig::submit()
{
	return m_settings->submit();
}

int SettingsConfig::getActionBar() const
{
	return m_settings->actionBar();
}

void SettingsConfig::setActionBar(int value)
{
	m_settings->setActionBar(value);
}

int SettingsConfig::getActionBarLocation() const
{
	return m_settings->actionBarLocation();
}

void SettingsConfig::setActionBarLocation(int value)
{
	m_settings->setActionBarLocation(value);
}

int SettingsConfig::getAlphaLockCursor() const
{
	return m_settings->alphaLockCursor();
}

void SettingsConfig::setAlphaLockCursor(int value)
{
	m_settings->setAlphaLockCursor(value);
}

int SettingsConfig::getAnimationExportFormat() const
{
	return m_settings->animationExportFormat();
}

void SettingsConfig::setAnimationExportFormat(int value)
{
	m_settings->setAnimationExportFormat(value);
}

bool SettingsConfig::getAutoRecordHost() const
{
	return m_settings->autoRecordHost();
}

void SettingsConfig::setAutoRecordHost(bool value)
{
	m_settings->setAutoRecordHost(value);
}

bool SettingsConfig::getAutoRecordJoin() const
{
	return m_settings->autoRecordJoin();
}

void SettingsConfig::setAutoRecordJoin(bool value)
{
	m_settings->setAutoRecordJoin(value);
}

int SettingsConfig::getAutoRecordMetadataIntervalMinutes() const
{
	return m_settings->autoRecordMetadataIntervalMinutes();
}

void SettingsConfig::setAutoRecordMetadataIntervalMinutes(int value)
{
	m_settings->setAutoRecordMetadataIntervalMinutes(value);
}

int SettingsConfig::getAutoRecordSnapshotIntervalMinutes() const
{
	return m_settings->autoRecordSnapshotIntervalMinutes();
}

void SettingsConfig::setAutoRecordSnapshotIntervalMinutes(int value)
{
	m_settings->setAutoRecordSnapshotIntervalMinutes(value);
}

int SettingsConfig::getAutomaticAlphaPreserve() const
{
	return m_settings->automaticAlphaPreserve();
}

void SettingsConfig::setAutomaticAlphaPreserve(int value)
{
	m_settings->setAutomaticAlphaPreserve(value);
}

int SettingsConfig::getBrushCursor() const
{
	return m_settings->brushCursor();
}

void SettingsConfig::setBrushCursor(int value)
{
	m_settings->setBrushCursor(value);
}

double SettingsConfig::getBrushOutlineWidth() const
{
	return m_settings->brushOutlineWidth();
}

void SettingsConfig::setBrushOutlineWidth(double value)
{
	m_settings->setBrushOutlineWidth(value);
}

bool SettingsConfig::getBrushPresetsAttach() const
{
	return m_settings->brushPresetsAttach();
}

void SettingsConfig::setBrushPresetsAttach(bool value)
{
	m_settings->setBrushPresetsAttach(value);
}

int SettingsConfig::getBrushSlotCount() const
{
	return m_settings->brushSlotCount();
}

void SettingsConfig::setBrushSlotCount(int value)
{
	m_settings->setBrushSlotCount(value);
}

bool SettingsConfig::getCancelDeselects() const
{
	return m_settings->cancelDeselects();
}

void SettingsConfig::setCancelDeselects(bool value)
{
	m_settings->setCancelDeselects(value);
}

bool SettingsConfig::getCanvasScrollBars() const
{
	return m_settings->canvasScrollBars();
}

void SettingsConfig::setCanvasScrollBars(bool value)
{
	m_settings->setCanvasScrollBars(value);
}

QVariantMap SettingsConfig::getCanvasShortcuts() const
{
	return m_settings->canvasShortcuts();
}

void SettingsConfig::setCanvasShortcuts(const QVariantMap &value)
{
	m_settings->setCanvasShortcuts(value);
}

QColor SettingsConfig::getCanvasViewBackgroundColor() const
{
	return m_settings->canvasViewBackgroundColor();
}

void SettingsConfig::setCanvasViewBackgroundColor(const QColor &value)
{
	m_settings->setCanvasViewBackgroundColor(value);
}

#if defined(Q_OS_ANDROID)
bool SettingsConfig::getCaptureVolumeRocker() const
{
	return m_settings->captureVolumeRocker();
}

void SettingsConfig::setCaptureVolumeRocker(bool value)
{
	m_settings->setCaptureVolumeRocker(value);
}
#endif

QColor SettingsConfig::getCheckerColor1() const
{
	return m_settings->checkerColor1();
}

void SettingsConfig::setCheckerColor1(const QColor &value)
{
	m_settings->setCheckerColor1(value);
}

QColor SettingsConfig::getCheckerColor2() const
{
	return m_settings->checkerColor2();
}

void SettingsConfig::setCheckerColor2(const QColor &value)
{
	m_settings->setCheckerColor2(value);
}

int SettingsConfig::getColorCircleGamutMaskAngle() const
{
	return m_settings->colorCircleGamutMaskAngle();
}

void SettingsConfig::setColorCircleGamutMaskAngle(int value)
{
	m_settings->setColorCircleGamutMaskAngle(value);
}

double SettingsConfig::getColorCircleGamutMaskOpacity() const
{
	return m_settings->colorCircleGamutMaskOpacity();
}

void SettingsConfig::setColorCircleGamutMaskOpacity(double value)
{
	m_settings->setColorCircleGamutMaskOpacity(value);
}

QString SettingsConfig::getColorCircleGamutMaskPath() const
{
	return m_settings->colorCircleGamutMaskPath();
}

void SettingsConfig::setColorCircleGamutMaskPath(const QString &value)
{
	m_settings->setColorCircleGamutMaskPath(value);
}

int SettingsConfig::getColorCircleHueAngle() const
{
	return m_settings->colorCircleHueAngle();
}

void SettingsConfig::setColorCircleHueAngle(int value)
{
	m_settings->setColorCircleHueAngle(value);
}

int SettingsConfig::getColorCircleHueCount() const
{
	return m_settings->colorCircleHueCount();
}

void SettingsConfig::setColorCircleHueCount(int value)
{
	m_settings->setColorCircleHueCount(value);
}

bool SettingsConfig::getColorCircleHueLimit() const
{
	return m_settings->colorCircleHueLimit();
}

void SettingsConfig::setColorCircleHueLimit(bool value)
{
	m_settings->setColorCircleHueLimit(value);
}

int SettingsConfig::getColorCircleSaturationCount() const
{
	return m_settings->colorCircleSaturationCount();
}

void SettingsConfig::setColorCircleSaturationCount(int value)
{
	m_settings->setColorCircleSaturationCount(value);
}

bool SettingsConfig::getColorCircleSaturationLimit() const
{
	return m_settings->colorCircleSaturationLimit();
}

void SettingsConfig::setColorCircleSaturationLimit(bool value)
{
	m_settings->setColorCircleSaturationLimit(value);
}

int SettingsConfig::getColorCircleValueCount() const
{
	return m_settings->colorCircleValueCount();
}

void SettingsConfig::setColorCircleValueCount(int value)
{
	m_settings->setColorCircleValueCount(value);
}

bool SettingsConfig::getColorCircleValueLimit() const
{
	return m_settings->colorCircleValueLimit();
}

void SettingsConfig::setColorCircleValueLimit(bool value)
{
	m_settings->setColorCircleValueLimit(value);
}

int SettingsConfig::getColorShadesBorderThickness() const
{
	return m_settings->colorShadesBorderThickness();
}

void SettingsConfig::setColorShadesBorderThickness(int value)
{
	m_settings->setColorShadesBorderThickness(value);
}

int SettingsConfig::getColorShadesColumnCount() const
{
	return m_settings->colorShadesColumnCount();
}

void SettingsConfig::setColorShadesColumnCount(int value)
{
	m_settings->setColorShadesColumnCount(value);
}

QVariantList SettingsConfig::getColorShadesConfig() const
{
	return m_settings->colorShadesConfig();
}

void SettingsConfig::setColorShadesConfig(const QVariantList &value)
{
	m_settings->setColorShadesConfig(value);
}

bool SettingsConfig::getColorShadesEnabled() const
{
	return m_settings->colorShadesEnabled();
}

void SettingsConfig::setColorShadesEnabled(bool value)
{
	m_settings->setColorShadesEnabled(value);
}

int SettingsConfig::getColorShadesRowHeight() const
{
	return m_settings->colorShadesRowHeight();
}

void SettingsConfig::setColorShadesRowHeight(int value)
{
	m_settings->setColorShadesRowHeight(value);
}

int SettingsConfig::getColorSlidersMode() const
{
	return m_settings->colorSlidersMode();
}

void SettingsConfig::setColorSlidersMode(int value)
{
	m_settings->setColorSlidersMode(value);
}

bool SettingsConfig::getColorSlidersShowAll() const
{
	return m_settings->colorSlidersShowAll();
}

void SettingsConfig::setColorSlidersShowAll(bool value)
{
	m_settings->setColorSlidersShowAll(value);
}

bool SettingsConfig::getColorSlidersShowInput() const
{
	return m_settings->colorSlidersShowInput();
}

void SettingsConfig::setColorSlidersShowInput(bool value)
{
	m_settings->setColorSlidersShowInput(value);
}

int SettingsConfig::getColorSwatchFlags() const
{
	return m_settings->colorSwatchFlags();
}

void SettingsConfig::setColorSwatchFlags(int value)
{
	m_settings->setColorSwatchFlags(value);
}

int SettingsConfig::getColorWheelAlign() const
{
	return m_settings->colorWheelAlign();
}

void SettingsConfig::setColorWheelAlign(int value)
{
	m_settings->setColorWheelAlign(value);
}

int SettingsConfig::getColorWheelAngle() const
{
	return m_settings->colorWheelAngle();
}

void SettingsConfig::setColorWheelAngle(int value)
{
	m_settings->setColorWheelAngle(value);
}

bool SettingsConfig::getColorWheelMirror() const
{
	return m_settings->colorWheelMirror();
}

void SettingsConfig::setColorWheelMirror(bool value)
{
	m_settings->setColorWheelMirror(value);
}

int SettingsConfig::getColorWheelPreview() const
{
	return m_settings->colorWheelPreview();
}

void SettingsConfig::setColorWheelPreview(int value)
{
	m_settings->setColorWheelPreview(value);
}

int SettingsConfig::getColorWheelShape() const
{
	return m_settings->colorWheelShape();
}

void SettingsConfig::setColorWheelShape(int value)
{
	m_settings->setColorWheelShape(value);
}

int SettingsConfig::getColorWheelSpace() const
{
	return m_settings->colorWheelSpace();
}

void SettingsConfig::setColorWheelSpace(int value)
{
	m_settings->setColorWheelSpace(value);
}

bool SettingsConfig::getCompactChat() const
{
	return m_settings->compactChat();
}

void SettingsConfig::setCompactChat(bool value)
{
	m_settings->setCompactChat(value);
}

bool SettingsConfig::getConfirmLayerDelete() const
{
	return m_settings->confirmLayerDelete();
}

void SettingsConfig::setConfirmLayerDelete(bool value)
{
	m_settings->setConfirmLayerDelete(value);
}

#if defined(Q_OS_ANDROID) && defined(DRAWPILE_USE_CONNECT_SERVICE)
bool SettingsConfig::getConnectionNotification() const
{
	return m_settings->connectionNotification();
}

void SettingsConfig::setConnectionNotification(bool value)
{
	m_settings->setConnectionNotification(value);
}
#endif

QVector<QVariantMap> SettingsConfig::getCurvesPresets() const
{
	return m_settings->curvesPresets();
}

void SettingsConfig::setCurvesPresets(const QVector<QVariantMap> &value)
{
	m_settings->setCurvesPresets(value);
}

int SettingsConfig::getDebounceDelayMs() const
{
	return m_settings->debounceDelayMs();
}

void SettingsConfig::setDebounceDelayMs(int value)
{
	m_settings->setDebounceDelayMs(value);
}

bool SettingsConfig::getDonationLinksEnabled() const
{
	return m_settings->donationLinksEnabled();
}

void SettingsConfig::setDonationLinksEnabled(bool value)
{
	m_settings->setDonationLinksEnabled(value);
}

bool SettingsConfig::getDoubleTapAltToFocusCanvas() const
{
	return m_settings->doubleTapAltToFocusCanvas();
}

void SettingsConfig::setDoubleTapAltToFocusCanvas(bool value)
{
	m_settings->setDoubleTapAltToFocusCanvas(value);
}

int SettingsConfig::getEngineFrameRate() const
{
	return m_settings->engineFrameRate();
}

void SettingsConfig::setEngineFrameRate(int value)
{
	m_settings->setEngineFrameRate(value);
}

int SettingsConfig::getEngineSnapshotCount() const
{
	return m_settings->engineSnapshotCount();
}

void SettingsConfig::setEngineSnapshotCount(int value)
{
	m_settings->setEngineSnapshotCount(value);
}

int SettingsConfig::getEngineSnapshotInterval() const
{
	return m_settings->engineSnapshotInterval();
}

void SettingsConfig::setEngineSnapshotInterval(int value)
{
	m_settings->setEngineSnapshotInterval(value);
}

int SettingsConfig::getEngineUndoDepth() const
{
	return m_settings->engineUndoDepth();
}

void SettingsConfig::setEngineUndoDepth(int value)
{
	m_settings->setEngineUndoDepth(value);
}

int SettingsConfig::getEraseCursor() const
{
	return m_settings->eraseCursor();
}

void SettingsConfig::setEraseCursor(int value)
{
	m_settings->setEraseCursor(value);
}

bool SettingsConfig::getFilterClosed() const
{
	return m_settings->filterClosed();
}

void SettingsConfig::setFilterClosed(bool value)
{
	m_settings->setFilterClosed(value);
}

bool SettingsConfig::getFilterDuplicates() const
{
	return m_settings->filterDuplicates();
}

void SettingsConfig::setFilterDuplicates(bool value)
{
	m_settings->setFilterDuplicates(value);
}

bool SettingsConfig::getFilterInactive() const
{
	return m_settings->filterInactive();
}

void SettingsConfig::setFilterInactive(bool value)
{
	m_settings->setFilterInactive(value);
}

bool SettingsConfig::getFilterLocked() const
{
	return m_settings->filterLocked();
}

void SettingsConfig::setFilterLocked(bool value)
{
	m_settings->setFilterLocked(value);
}

bool SettingsConfig::getFilterNsfm() const
{
	return m_settings->filterNsfm();
}

void SettingsConfig::setFilterNsfm(bool value)
{
	m_settings->setFilterNsfm(value);
}

bool SettingsConfig::getFlipbookUpscaling() const
{
	return m_settings->flipbookUpscaling();
}

void SettingsConfig::setFlipbookUpscaling(bool value)
{
	m_settings->setFlipbookUpscaling(value);
}

QRect SettingsConfig::getFlipbookWindow() const
{
	return m_settings->flipbookWindow();
}

void SettingsConfig::setFlipbookWindow(const QRect &value)
{
	m_settings->setFlipbookWindow(value);
}

int SettingsConfig::getFontSize() const
{
	return m_settings->fontSize();
}

void SettingsConfig::setFontSize(int value)
{
	m_settings->setFontSize(value);
}

int SettingsConfig::getFourFingerTap() const
{
	return m_settings->fourFingerTap();
}

void SettingsConfig::setFourFingerTap(int value)
{
	m_settings->setFourFingerTap(value);
}

QString SettingsConfig::getGlobalPressureCurve() const
{
	return m_settings->globalPressureCurve();
}

void SettingsConfig::setGlobalPressureCurve(const QString &value)
{
	m_settings->setGlobalPressureCurve(value);
}

QString SettingsConfig::getGlobalPressureCurveEraser() const
{
	return m_settings->globalPressureCurveEraser();
}

void SettingsConfig::setGlobalPressureCurveEraser(const QString &value)
{
	m_settings->setGlobalPressureCurveEraser(value);
}

int SettingsConfig::getGlobalPressureCurveMode() const
{
	return m_settings->globalPressureCurveMode();
}

void SettingsConfig::setGlobalPressureCurveMode(int value)
{
	m_settings->setGlobalPressureCurveMode(value);
}

bool SettingsConfig::getHostEnableAdvanced() const
{
	return m_settings->hostEnableAdvanced();
}

void SettingsConfig::setHostEnableAdvanced(bool value)
{
	m_settings->setHostEnableAdvanced(value);
}

bool SettingsConfig::getIgnoreCarrierGradeNat() const
{
	return m_settings->ignoreCarrierGradeNat();
}

void SettingsConfig::setIgnoreCarrierGradeNat(bool value)
{
	m_settings->setIgnoreCarrierGradeNat(value);
}

QVector<QVariantMap> SettingsConfig::getInputPresets() const
{
	return m_settings->inputPresets();
}

void SettingsConfig::setInputPresets(const QVector<QVariantMap> &value)
{
	m_settings->setInputPresets(value);
}

bool SettingsConfig::getInsecurePasswordStorage() const
{
	return m_settings->insecurePasswordStorage();
}

void SettingsConfig::setInsecurePasswordStorage(bool value)
{
	m_settings->setInsecurePasswordStorage(value);
}

int SettingsConfig::getInterfaceMode() const
{
	return m_settings->interfaceMode();
}

void SettingsConfig::setInterfaceMode(int value)
{
	m_settings->setInterfaceMode(value);
}

bool SettingsConfig::getInterpolateInputs() const
{
	return m_settings->interpolateInputs();
}

void SettingsConfig::setInterpolateInputs(bool value)
{
	m_settings->setInterpolateInputs(value);
}

bool SettingsConfig::getInviteIncludePassword() const
{
	return m_settings->inviteIncludePassword();
}

void SettingsConfig::setInviteIncludePassword(bool value)
{
	m_settings->setInviteIncludePassword(value);
}

int SettingsConfig::getKineticScrollGesture() const
{
	return m_settings->kineticScrollGesture();
}

void SettingsConfig::setKineticScrollGesture(int value)
{
	m_settings->setKineticScrollGesture(value);
}

bool SettingsConfig::getKineticScrollHideBars() const
{
	return m_settings->kineticScrollHideBars();
}

void SettingsConfig::setKineticScrollHideBars(bool value)
{
	m_settings->setKineticScrollHideBars(value);
}

int SettingsConfig::getKineticScrollThreshold() const
{
	return m_settings->kineticScrollThreshold();
}

void SettingsConfig::setKineticScrollThreshold(int value)
{
	m_settings->setKineticScrollThreshold(value);
}

QString SettingsConfig::getLanguage() const
{
	return m_settings->language();
}

void SettingsConfig::setLanguage(const QString &value)
{
	m_settings->setLanguage(value);
}

bool SettingsConfig::getLastAnnounce() const
{
	return m_settings->lastAnnounce();
}

void SettingsConfig::setLastAnnounce(bool value)
{
	m_settings->setLastAnnounce(value);
}

QString SettingsConfig::getLastAvatar() const
{
	return m_settings->lastAvatar();
}

void SettingsConfig::setLastAvatar(const QString &value)
{
	m_settings->setLastAvatar(value);
}

int SettingsConfig::getLastBrowseSortColumn() const
{
	return m_settings->lastBrowseSortColumn();
}

void SettingsConfig::setLastBrowseSortColumn(int value)
{
	m_settings->setLastBrowseSortColumn(value);
}

int SettingsConfig::getLastBrowseSortDirection() const
{
	return m_settings->lastBrowseSortDirection();
}

void SettingsConfig::setLastBrowseSortDirection(int value)
{
	m_settings->setLastBrowseSortDirection(value);
}

QString SettingsConfig::getLastFileOpenPath() const
{
	return m_settings->lastFileOpenPath();
}

void SettingsConfig::setLastFileOpenPath(const QString &value)
{
	m_settings->setLastFileOpenPath(value);
}

QVariantMap SettingsConfig::getLastFileOpenPaths() const
{
	return m_settings->lastFileOpenPaths();
}

void SettingsConfig::setLastFileOpenPaths(const QVariantMap &value)
{
	m_settings->setLastFileOpenPaths(value);
}

int SettingsConfig::getLastHostServer() const
{
	return m_settings->lastHostServer();
}

void SettingsConfig::setLastHostServer(int value)
{
	m_settings->setLastHostServer(value);
}

int SettingsConfig::getLastHostType() const
{
	return m_settings->lastHostType();
}

void SettingsConfig::setLastHostType(int value)
{
	m_settings->setLastHostType(value);
}

QString SettingsConfig::getLastIdAlias() const
{
	return m_settings->lastIdAlias();
}

void SettingsConfig::setLastIdAlias(const QString &value)
{
	m_settings->setLastIdAlias(value);
}

QString SettingsConfig::getLastJoinAddress() const
{
	return m_settings->lastJoinAddress();
}

void SettingsConfig::setLastJoinAddress(const QString &value)
{
	m_settings->setLastJoinAddress(value);
}

bool SettingsConfig::getLastKeepChat() const
{
	return m_settings->lastKeepChat();
}

void SettingsConfig::setLastKeepChat(bool value)
{
	m_settings->setLastKeepChat(value);
}

QStringList SettingsConfig::getLastListingUrls() const
{
	return m_settings->lastListingUrls();
}

void SettingsConfig::setLastListingUrls(const QStringList &value)
{
	m_settings->setLastListingUrls(value);
}

bool SettingsConfig::getLastNsfm() const
{
	return m_settings->lastNsfm();
}

void SettingsConfig::setLastNsfm(bool value)
{
	m_settings->setLastNsfm(value);
}

int SettingsConfig::getLastPalette() const
{
	return m_settings->lastPalette();
}

void SettingsConfig::setLastPalette(int value)
{
	m_settings->setLastPalette(value);
}

QByteArray SettingsConfig::getLastSessionAuthList() const
{
	return m_settings->lastSessionAuthList();
}

void SettingsConfig::setLastSessionAuthList(const QByteArray &value)
{
	m_settings->setLastSessionAuthList(value);
}

bool SettingsConfig::getLastSessionAutomatic() const
{
	return m_settings->lastSessionAutomatic();
}

void SettingsConfig::setLastSessionAutomatic(bool value)
{
	m_settings->setLastSessionAutomatic(value);
}

QByteArray SettingsConfig::getLastSessionBanList() const
{
	return m_settings->lastSessionBanList();
}

void SettingsConfig::setLastSessionBanList(const QByteArray &value)
{
	m_settings->setLastSessionBanList(value);
}

QString SettingsConfig::getLastSessionOpPassword() const
{
	return m_settings->lastSessionOpPassword();
}

void SettingsConfig::setLastSessionOpPassword(const QString &value)
{
	m_settings->setLastSessionOpPassword(value);
}

QString SettingsConfig::getLastSessionPassword() const
{
	return m_settings->lastSessionPassword();
}

void SettingsConfig::setLastSessionPassword(const QString &value)
{
	m_settings->setLastSessionPassword(value);
}

QVariantMap SettingsConfig::getLastSessionPermissions() const
{
	return m_settings->lastSessionPermissions();
}

void SettingsConfig::setLastSessionPermissions(const QVariantMap &value)
{
	m_settings->setLastSessionPermissions(value);
}

QString SettingsConfig::getLastSessionTitle() const
{
	return m_settings->lastSessionTitle();
}

void SettingsConfig::setLastSessionTitle(const QString &value)
{
	m_settings->setLastSessionTitle(value);
}

int SettingsConfig::getLastSessionUndoDepth() const
{
	return m_settings->lastSessionUndoDepth();
}

void SettingsConfig::setLastSessionUndoDepth(int value)
{
	m_settings->setLastSessionUndoDepth(value);
}

QString SettingsConfig::getLastStartDialogDateTime() const
{
	return m_settings->lastStartDialogDateTime();
}

void SettingsConfig::setLastStartDialogDateTime(const QString &value)
{
	m_settings->setLastStartDialogDateTime(value);
}

int SettingsConfig::getLastStartDialogPage() const
{
	return m_settings->lastStartDialogPage();
}

void SettingsConfig::setLastStartDialogPage(int value)
{
	m_settings->setLastStartDialogPage(value);
}

QSize SettingsConfig::getLastStartDialogSize() const
{
	return m_settings->lastStartDialogSize();
}

void SettingsConfig::setLastStartDialogSize(const QSize &value)
{
	m_settings->setLastStartDialogSize(value);
}

int SettingsConfig::getLastTool() const
{
	return m_settings->lastTool();
}

void SettingsConfig::setLastTool(int value)
{
	m_settings->setLastTool(value);
}

QColor SettingsConfig::getLastToolBackgroundColor() const
{
	return m_settings->lastToolBackgroundColor();
}

void SettingsConfig::setLastToolBackgroundColor(const QColor &value)
{
	m_settings->setLastToolBackgroundColor(value);
}

QColor SettingsConfig::getLastToolColor() const
{
	return m_settings->lastToolColor();
}

void SettingsConfig::setLastToolColor(const QColor &value)
{
	m_settings->setLastToolColor(value);
}

QString SettingsConfig::getLastUsername() const
{
	return m_settings->lastUsername();
}

void SettingsConfig::setLastUsername(const QString &value)
{
	m_settings->setLastUsername(value);
}

QMap<QString, bool> SettingsConfig::getLastWindowActions() const
{
	return m_settings->lastWindowActions();
}

void SettingsConfig::setLastWindowActions(const QMap<QString, bool> &value)
{
	m_settings->setLastWindowActions(value);
}

QVariantMap SettingsConfig::getLastWindowDocks() const
{
	return m_settings->lastWindowDocks();
}

void SettingsConfig::setLastWindowDocks(const QVariantMap &value)
{
	m_settings->setLastWindowDocks(value);
}

bool SettingsConfig::getLastWindowMaximized() const
{
	return m_settings->lastWindowMaximized();
}

void SettingsConfig::setLastWindowMaximized(bool value)
{
	m_settings->setLastWindowMaximized(value);
}

QPoint SettingsConfig::getLastWindowPosition() const
{
	return m_settings->lastWindowPosition();
}

void SettingsConfig::setLastWindowPosition(const QPoint &value)
{
	m_settings->setLastWindowPosition(value);
}

QSize SettingsConfig::getLastWindowSize() const
{
	return m_settings->lastWindowSize();
}

void SettingsConfig::setLastWindowSize(const QSize &value)
{
	m_settings->setLastWindowSize(value);
}

QByteArray SettingsConfig::getLastWindowState() const
{
	return m_settings->lastWindowState();
}

void SettingsConfig::setLastWindowState(const QByteArray &value)
{
	m_settings->setLastWindowState(value);
}

QByteArray SettingsConfig::getLastWindowViewState() const
{
	return m_settings->lastWindowViewState();
}

void SettingsConfig::setLastWindowViewState(const QByteArray &value)
{
	m_settings->setLastWindowViewState(value);
}

int SettingsConfig::getLayerSketchOpacityPercent() const
{
	return m_settings->layerSketchOpacityPercent();
}

void SettingsConfig::setLayerSketchOpacityPercent(int value)
{
	m_settings->setLayerSketchOpacityPercent(value);
}

QColor SettingsConfig::getLayerSketchTint() const
{
	return m_settings->layerSketchTint();
}

void SettingsConfig::setLayerSketchTint(const QColor &value)
{
	m_settings->setLayerSketchTint(value);
}

QVector<QVariantMap> SettingsConfig::getLayouts() const
{
	return m_settings->layouts();
}

void SettingsConfig::setLayouts(const QVector<QVariantMap> &value)
{
	m_settings->setLayouts(value);
}

int SettingsConfig::getLayoutsVersion() const
{
	return m_settings->layoutsVersion();
}

void SettingsConfig::setLayoutsVersion(int value)
{
	m_settings->setLayoutsVersion(value);
}

bool SettingsConfig::getLeftyMode() const
{
	return m_settings->leftyMode();
}

void SettingsConfig::setLeftyMode(bool value)
{
	m_settings->setLeftyMode(value);
}

QVector<QVariantMap> SettingsConfig::getListServers() const
{
	return m_settings->listServers();
}

void SettingsConfig::setListServers(const QVector<QVariantMap> &value)
{
	m_settings->setListServers(value);
}

bool SettingsConfig::getLongPressEnabled() const
{
	return m_settings->longPressEnabled();
}

void SettingsConfig::setLongPressEnabled(bool value)
{
	m_settings->setLongPressEnabled(value);
}

bool SettingsConfig::getMentionEnabled() const
{
	return m_settings->mentionEnabled();
}

void SettingsConfig::setMentionEnabled(bool value)
{
	m_settings->setMentionEnabled(value);
}

QString SettingsConfig::getMentionTriggerList() const
{
	return m_settings->mentionTriggerList();
}

void SettingsConfig::setMentionTriggerList(const QString &value)
{
	m_settings->setMentionTriggerList(value);
}

int SettingsConfig::getMessageQueueDrainRate() const
{
	return m_settings->messageQueueDrainRate();
}

void SettingsConfig::setMessageQueueDrainRate(int value)
{
	m_settings->setMessageQueueDrainRate(value);
}

bool SettingsConfig::getMouseSmoothing() const
{
	return m_settings->mouseSmoothing();
}

void SettingsConfig::setMouseSmoothing(bool value)
{
	m_settings->setMouseSmoothing(value);
}

#if defined(NATIVE_DIALOGS_SETTING_AVAILABLE)
bool SettingsConfig::getNativeDialogs() const
{
	return m_settings->nativeDialogs();
}

void SettingsConfig::setNativeDialogs(bool value)
{
	m_settings->setNativeDialogs(value);
}
#endif

bool SettingsConfig::getNavigatorRealtime() const
{
	return m_settings->navigatorRealtime();
}

void SettingsConfig::setNavigatorRealtime(bool value)
{
	m_settings->setNavigatorRealtime(value);
}

bool SettingsConfig::getNavigatorShowCursors() const
{
	return m_settings->navigatorShowCursors();
}

void SettingsConfig::setNavigatorShowCursors(bool value)
{
	m_settings->setNavigatorShowCursors(value);
}

int SettingsConfig::getNetworkProxyMode() const
{
	return m_settings->networkProxyMode();
}

void SettingsConfig::setNetworkProxyMode(int value)
{
	m_settings->setNetworkProxyMode(value);
}

QColor SettingsConfig::getNewCanvasBackColor() const
{
	return m_settings->newCanvasBackColor();
}

void SettingsConfig::setNewCanvasBackColor(const QColor &value)
{
	m_settings->setNewCanvasBackColor(value);
}

QSize SettingsConfig::getNewCanvasSize() const
{
	return m_settings->newCanvasSize();
}

void SettingsConfig::setNewCanvasSize(const QSize &value)
{
	m_settings->setNewCanvasSize(value);
}

bool SettingsConfig::getNotifFlashChat() const
{
	return m_settings->notifFlashChat();
}

void SettingsConfig::setNotifFlashChat(bool value)
{
	m_settings->setNotifFlashChat(value);
}

bool SettingsConfig::getNotifFlashDisconnect() const
{
	return m_settings->notifFlashDisconnect();
}

void SettingsConfig::setNotifFlashDisconnect(bool value)
{
	m_settings->setNotifFlashDisconnect(value);
}

bool SettingsConfig::getNotifFlashLock() const
{
	return m_settings->notifFlashLock();
}

void SettingsConfig::setNotifFlashLock(bool value)
{
	m_settings->setNotifFlashLock(value);
}

bool SettingsConfig::getNotifFlashLogin() const
{
	return m_settings->notifFlashLogin();
}

void SettingsConfig::setNotifFlashLogin(bool value)
{
	m_settings->setNotifFlashLogin(value);
}

bool SettingsConfig::getNotifFlashLogout() const
{
	return m_settings->notifFlashLogout();
}

void SettingsConfig::setNotifFlashLogout(bool value)
{
	m_settings->setNotifFlashLogout(value);
}

bool SettingsConfig::getNotifFlashPrivateChat() const
{
	return m_settings->notifFlashPrivateChat();
}

void SettingsConfig::setNotifFlashPrivateChat(bool value)
{
	m_settings->setNotifFlashPrivateChat(value);
}

bool SettingsConfig::getNotifFlashUnlock() const
{
	return m_settings->notifFlashUnlock();
}

void SettingsConfig::setNotifFlashUnlock(bool value)
{
	m_settings->setNotifFlashUnlock(value);
}

bool SettingsConfig::getNotifPopupChat() const
{
	return m_settings->notifPopupChat();
}

void SettingsConfig::setNotifPopupChat(bool value)
{
	m_settings->setNotifPopupChat(value);
}

bool SettingsConfig::getNotifPopupDisconnect() const
{
	return m_settings->notifPopupDisconnect();
}

void SettingsConfig::setNotifPopupDisconnect(bool value)
{
	m_settings->setNotifPopupDisconnect(value);
}

bool SettingsConfig::getNotifPopupLock() const
{
	return m_settings->notifPopupLock();
}

void SettingsConfig::setNotifPopupLock(bool value)
{
	m_settings->setNotifPopupLock(value);
}

bool SettingsConfig::getNotifPopupLogin() const
{
	return m_settings->notifPopupLogin();
}

void SettingsConfig::setNotifPopupLogin(bool value)
{
	m_settings->setNotifPopupLogin(value);
}

bool SettingsConfig::getNotifPopupLogout() const
{
	return m_settings->notifPopupLogout();
}

void SettingsConfig::setNotifPopupLogout(bool value)
{
	m_settings->setNotifPopupLogout(value);
}

bool SettingsConfig::getNotifPopupPrivateChat() const
{
	return m_settings->notifPopupPrivateChat();
}

void SettingsConfig::setNotifPopupPrivateChat(bool value)
{
	m_settings->setNotifPopupPrivateChat(value);
}

bool SettingsConfig::getNotifPopupUnlock() const
{
	return m_settings->notifPopupUnlock();
}

void SettingsConfig::setNotifPopupUnlock(bool value)
{
	m_settings->setNotifPopupUnlock(value);
}

bool SettingsConfig::getNotifSoundChat() const
{
	return m_settings->notifSoundChat();
}

void SettingsConfig::setNotifSoundChat(bool value)
{
	m_settings->setNotifSoundChat(value);
}

bool SettingsConfig::getNotifSoundDisconnect() const
{
	return m_settings->notifSoundDisconnect();
}

void SettingsConfig::setNotifSoundDisconnect(bool value)
{
	m_settings->setNotifSoundDisconnect(value);
}

bool SettingsConfig::getNotifSoundLock() const
{
	return m_settings->notifSoundLock();
}

void SettingsConfig::setNotifSoundLock(bool value)
{
	m_settings->setNotifSoundLock(value);
}

bool SettingsConfig::getNotifSoundLogin() const
{
	return m_settings->notifSoundLogin();
}

void SettingsConfig::setNotifSoundLogin(bool value)
{
	m_settings->setNotifSoundLogin(value);
}

bool SettingsConfig::getNotifSoundLogout() const
{
	return m_settings->notifSoundLogout();
}

void SettingsConfig::setNotifSoundLogout(bool value)
{
	m_settings->setNotifSoundLogout(value);
}

bool SettingsConfig::getNotifSoundPrivateChat() const
{
	return m_settings->notifSoundPrivateChat();
}

void SettingsConfig::setNotifSoundPrivateChat(bool value)
{
	m_settings->setNotifSoundPrivateChat(value);
}

bool SettingsConfig::getNotifSoundUnlock() const
{
	return m_settings->notifSoundUnlock();
}

void SettingsConfig::setNotifSoundUnlock(bool value)
{
	m_settings->setNotifSoundUnlock(value);
}

int SettingsConfig::getOneFingerTap() const
{
	return m_settings->oneFingerTap();
}

void SettingsConfig::setOneFingerTap(int value)
{
	m_settings->setOneFingerTap(value);
}

int SettingsConfig::getOneFingerTapAndHold() const
{
	return m_settings->oneFingerTapAndHold();
}

void SettingsConfig::setOneFingerTapAndHold(int value)
{
	m_settings->setOneFingerTapAndHold(value);
}

int SettingsConfig::getOneFingerTouch() const
{
	return m_settings->oneFingerTouch();
}

void SettingsConfig::setOneFingerTouch(int value)
{
	m_settings->setOneFingerTouch(value);
}

int SettingsConfig::getOnionSkinsFrameCount() const
{
	return m_settings->onionSkinsFrameCount();
}

void SettingsConfig::setOnionSkinsFrameCount(int value)
{
	m_settings->setOnionSkinsFrameCount(value);
}

QMap<int, int> SettingsConfig::getOnionSkinsFrames() const
{
	return m_settings->onionSkinsFrames();
}

void SettingsConfig::setOnionSkinsFrames(const QMap<int, int> &value)
{
	m_settings->setOnionSkinsFrames(value);
}

QColor SettingsConfig::getOnionSkinsTintAbove() const
{
	return m_settings->onionSkinsTintAbove();
}

void SettingsConfig::setOnionSkinsTintAbove(const QColor &value)
{
	m_settings->setOnionSkinsTintAbove(value);
}

QColor SettingsConfig::getOnionSkinsTintBelow() const
{
	return m_settings->onionSkinsTintBelow();
}

void SettingsConfig::setOnionSkinsTintBelow(const QColor &value)
{
	m_settings->setOnionSkinsTintBelow(value);
}

bool SettingsConfig::getOnionSkinsWrap() const
{
	return m_settings->onionSkinsWrap();
}

void SettingsConfig::setOnionSkinsWrap(bool value)
{
	m_settings->setOnionSkinsWrap(value);
}

bool SettingsConfig::getOverrideFontSize() const
{
	return m_settings->overrideFontSize();
}

void SettingsConfig::setOverrideFontSize(bool value)
{
	m_settings->setOverrideFontSize(value);
}

bool SettingsConfig::getParentalControlsAutoTag() const
{
	return m_settings->parentalControlsAutoTag();
}

void SettingsConfig::setParentalControlsAutoTag(bool value)
{
	m_settings->setParentalControlsAutoTag(value);
}

bool SettingsConfig::getParentalControlsForceCensor() const
{
	return m_settings->parentalControlsForceCensor();
}

void SettingsConfig::setParentalControlsForceCensor(bool value)
{
	m_settings->setParentalControlsForceCensor(value);
}

bool SettingsConfig::getParentalControlsHideLocked() const
{
	return m_settings->parentalControlsHideLocked();
}

void SettingsConfig::setParentalControlsHideLocked(bool value)
{
	m_settings->setParentalControlsHideLocked(value);
}

int SettingsConfig::getParentalControlsLevel() const
{
	return m_settings->parentalControlsLevel();
}

void SettingsConfig::setParentalControlsLevel(int value)
{
	m_settings->setParentalControlsLevel(value);
}

QByteArray SettingsConfig::getParentalControlsLocked() const
{
	return m_settings->parentalControlsLocked();
}

void SettingsConfig::setParentalControlsLocked(const QByteArray &value)
{
	m_settings->setParentalControlsLocked(value);
}

QString SettingsConfig::getParentalControlsTags() const
{
	return m_settings->parentalControlsTags();
}

void SettingsConfig::setParentalControlsTags(const QString &value)
{
	m_settings->setParentalControlsTags(value);
}

QString SettingsConfig::getPreferredExportFormat() const
{
	return m_settings->preferredExportFormat();
}

void SettingsConfig::setPreferredExportFormat(const QString &value)
{
	m_settings->setPreferredExportFormat(value);
}

QString SettingsConfig::getPreferredSaveFormat() const
{
	return m_settings->preferredSaveFormat();
}

void SettingsConfig::setPreferredSaveFormat(const QString &value)
{
	m_settings->setPreferredSaveFormat(value);
}

bool SettingsConfig::getPromptLayerCreate() const
{
	return m_settings->promptLayerCreate();
}

void SettingsConfig::setPromptLayerCreate(bool value)
{
	m_settings->setPromptLayerCreate(value);
}

#if defined(Q_OS_MACOS)
bool SettingsConfig::getQuitOnLastWindowClosed() const
{
	return m_settings->quitOnLastWindowClosed();
}

void SettingsConfig::setQuitOnLastWindowClosed(bool value)
{
	m_settings->setQuitOnLastWindowClosed(value);
}
#endif

QStringList SettingsConfig::getRecentFiles() const
{
	return m_settings->recentFiles();
}

void SettingsConfig::setRecentFiles(const QStringList &value)
{
	m_settings->setRecentFiles(value);
}

QStringList SettingsConfig::getRecentHosts() const
{
	return m_settings->recentHosts();
}

void SettingsConfig::setRecentHosts(const QStringList &value)
{
	m_settings->setRecentHosts(value);
}

QStringList SettingsConfig::getRecentRemoteHosts() const
{
	return m_settings->recentRemoteHosts();
}

void SettingsConfig::setRecentRemoteHosts(const QStringList &value)
{
	m_settings->setRecentRemoteHosts(value);
}

int SettingsConfig::getRenderCanvas() const
{
	return m_settings->renderCanvas();
}

void SettingsConfig::setRenderCanvas(int value)
{
	m_settings->setRenderCanvas(value);
}

bool SettingsConfig::getRenderSmooth() const
{
	return m_settings->renderSmooth();
}

void SettingsConfig::setRenderSmooth(bool value)
{
	m_settings->setRenderSmooth(value);
}

bool SettingsConfig::getRenderUpdateFull() const
{
	return m_settings->renderUpdateFull();
}

void SettingsConfig::setRenderUpdateFull(bool value)
{
	m_settings->setRenderUpdateFull(value);
}

int SettingsConfig::getSamplingRingVisibility() const
{
	return m_settings->samplingRingVisibility();
}

void SettingsConfig::setSamplingRingVisibility(int value)
{
	m_settings->setSamplingRingVisibility(value);
}

QColor SettingsConfig::getSelectionColor() const
{
	return m_settings->selectionColor();
}

void SettingsConfig::setSelectionColor(const QColor &value)
{
	m_settings->setSelectionColor(value);
}

bool SettingsConfig::getServerAutoReset() const
{
	return m_settings->serverAutoReset();
}

void SettingsConfig::setServerAutoReset(bool value)
{
	m_settings->setServerAutoReset(value);
}

bool SettingsConfig::getServerHideIp() const
{
	return m_settings->serverHideIp();
}

void SettingsConfig::setServerHideIp(bool value)
{
	m_settings->setServerHideIp(value);
}

int SettingsConfig::getServerPort() const
{
	return m_settings->serverPort();
}

void SettingsConfig::setServerPort(int value)
{
	m_settings->setServerPort(value);
}

int SettingsConfig::getServerTimeout() const
{
	return m_settings->serverTimeout();
}

void SettingsConfig::setServerTimeout(int value)
{
	m_settings->setServerTimeout(value);
}

bool SettingsConfig::getShareBrushSlotColor() const
{
	return m_settings->shareBrushSlotColor();
}

void SettingsConfig::setShareBrushSlotColor(bool value)
{
	m_settings->setShareBrushSlotColor(value);
}

QVariantMap SettingsConfig::getShortcuts() const
{
	return m_settings->shortcuts();
}

void SettingsConfig::setShortcuts(const QVariantMap &value)
{
	m_settings->setShortcuts(value);
}

bool SettingsConfig::getShowInviteDialogOnHost() const
{
	return m_settings->showInviteDialogOnHost();
}

void SettingsConfig::setShowInviteDialogOnHost(bool value)
{
	m_settings->setShowInviteDialogOnHost(value);
}

bool SettingsConfig::getShowNsfmWarningOnJoin() const
{
	return m_settings->showNsfmWarningOnJoin();
}

void SettingsConfig::setShowNsfmWarningOnJoin(bool value)
{
	m_settings->setShowNsfmWarningOnJoin(value);
}

bool SettingsConfig::getShowTransformNotices() const
{
	return m_settings->showTransformNotices();
}

void SettingsConfig::setShowTransformNotices(bool value)
{
	m_settings->setShowTransformNotices(value);
}

bool SettingsConfig::getShowTrayIcon() const
{
	return m_settings->showTrayIcon();
}

void SettingsConfig::setShowTrayIcon(bool value)
{
	m_settings->setShowTrayIcon(value);
}

bool SettingsConfig::getShowViewModeNotices() const
{
	return m_settings->showViewModeNotices();
}

void SettingsConfig::setShowViewModeNotices(bool value)
{
	m_settings->setShowViewModeNotices(value);
}

int SettingsConfig::getSmoothing() const
{
	return m_settings->smoothing();
}

void SettingsConfig::setSmoothing(int value)
{
	m_settings->setSmoothing(value);
}

int SettingsConfig::getSoundVolume() const
{
	return m_settings->soundVolume();
}

void SettingsConfig::setSoundVolume(int value)
{
	m_settings->setSoundVolume(value);
}

int SettingsConfig::getTabletDriver() const
{
	return m_settings->tabletDriver();
}

void SettingsConfig::setTabletDriver(int value)
{
	m_settings->setTabletDriver(value);
}

int SettingsConfig::getTabletEraserAction() const
{
	return m_settings->tabletEraserAction();
}

void SettingsConfig::setTabletEraserAction(int value)
{
	m_settings->setTabletEraserAction(value);
}

bool SettingsConfig::getTabletEvents() const
{
	return m_settings->tabletEvents();
}

void SettingsConfig::setTabletEvents(bool value)
{
	m_settings->setTabletEvents(value);
}

int SettingsConfig::getTabletPressTimerDelay() const
{
	return m_settings->tabletPressTimerDelay();
}

void SettingsConfig::setTabletPressTimerDelay(int value)
{
	m_settings->setTabletPressTimerDelay(value);
}

bool SettingsConfig::getTemporaryToolSwitch() const
{
	return m_settings->temporaryToolSwitch();
}

void SettingsConfig::setTemporaryToolSwitch(bool value)
{
	m_settings->setTemporaryToolSwitch(value);
}

int SettingsConfig::getTemporaryToolSwitchMs() const
{
	return m_settings->temporaryToolSwitchMs();
}

void SettingsConfig::setTemporaryToolSwitchMs(int value)
{
	m_settings->setTemporaryToolSwitchMs(value);
}

QString SettingsConfig::getThemePalette() const
{
	return m_settings->themePalette();
}

void SettingsConfig::setThemePalette(const QString &value)
{
	m_settings->setThemePalette(value);
}

QString SettingsConfig::getThemeStyle() const
{
	return m_settings->themeStyle();
}

void SettingsConfig::setThemeStyle(const QString &value)
{
	m_settings->setThemeStyle(value);
}

int SettingsConfig::getThreeFingerTap() const
{
	return m_settings->threeFingerTap();
}

void SettingsConfig::setThreeFingerTap(int value)
{
	m_settings->setThreeFingerTap(value);
}

QVariantHash SettingsConfig::getToolBarConfig() const
{
	return m_settings->toolBarConfig();
}

void SettingsConfig::setToolBarConfig(const QVariantHash &value)
{
	m_settings->setToolBarConfig(value);
}

bool SettingsConfig::getToolToggle() const
{
	return m_settings->toolToggle();
}

void SettingsConfig::setToolToggle(bool value)
{
	m_settings->setToolToggle(value);
}

QMap<QString, QVariantHash> SettingsConfig::getToolset() const
{
	return m_settings->toolset();
}

void SettingsConfig::setToolset(const QMap<QString, QVariantHash> &value)
{
	m_settings->setToolset(value);
}

bool SettingsConfig::getTouchDrawPressure() const
{
	return m_settings->touchDrawPressure();
}

void SettingsConfig::setTouchDrawPressure(bool value)
{
	m_settings->setTouchDrawPressure(value);
}

bool SettingsConfig::getTouchGestures() const
{
	return m_settings->touchGestures();
}

void SettingsConfig::setTouchGestures(bool value)
{
	m_settings->setTouchGestures(value);
}

int SettingsConfig::getTouchSmoothing() const
{
	return m_settings->touchSmoothing();
}

void SettingsConfig::setTouchSmoothing(int value)
{
	m_settings->setTouchSmoothing(value);
}

int SettingsConfig::getTwoFingerPinch() const
{
	return m_settings->twoFingerPinch();
}

void SettingsConfig::setTwoFingerPinch(int value)
{
	m_settings->setTwoFingerPinch(value);
}

int SettingsConfig::getTwoFingerTap() const
{
	return m_settings->twoFingerTap();
}

void SettingsConfig::setTwoFingerTap(int value)
{
	m_settings->setTwoFingerTap(value);
}

int SettingsConfig::getTwoFingerTwist() const
{
	return m_settings->twoFingerTwist();
}

void SettingsConfig::setTwoFingerTwist(int value)
{
	m_settings->setTwoFingerTwist(value);
}

bool SettingsConfig::getUpdateCheckEnabled() const
{
	return m_settings->updateCheckEnabled();
}

void SettingsConfig::setUpdateCheckEnabled(bool value)
{
	m_settings->setUpdateCheckEnabled(value);
}

bool SettingsConfig::getUseMipmaps() const
{
	return m_settings->useMipmaps();
}

void SettingsConfig::setUseMipmaps(bool value)
{
	m_settings->setUseMipmaps(value);
}

int SettingsConfig::getUserMarkerPersistence() const
{
	return m_settings->userMarkerPersistence();
}

void SettingsConfig::setUserMarkerPersistence(int value)
{
	m_settings->setUserMarkerPersistence(value);
}

QString SettingsConfig::getVideoExportCustomFfmpeg() const
{
	return m_settings->videoExportCustomFfmpeg();
}

void SettingsConfig::setVideoExportCustomFfmpeg(const QString &value)
{
	m_settings->setVideoExportCustomFfmpeg(value);
}

QString SettingsConfig::getVideoExportFfmpegPath() const
{
	return m_settings->videoExportFfmpegPath();
}

void SettingsConfig::setVideoExportFfmpegPath(const QString &value)
{
	m_settings->setVideoExportFfmpegPath(value);
}

int SettingsConfig::getVideoExportFormat() const
{
	return m_settings->videoExportFormat();
}

void SettingsConfig::setVideoExportFormat(int value)
{
	m_settings->setVideoExportFormat(value);
}

int SettingsConfig::getVideoExportFrameHeight() const
{
	return m_settings->videoExportFrameHeight();
}

void SettingsConfig::setVideoExportFrameHeight(int value)
{
	m_settings->setVideoExportFrameHeight(value);
}

int SettingsConfig::getVideoExportFrameRate() const
{
	return m_settings->videoExportFrameRate();
}

void SettingsConfig::setVideoExportFrameRate(int value)
{
	m_settings->setVideoExportFrameRate(value);
}

int SettingsConfig::getVideoExportFrameWidth() const
{
	return m_settings->videoExportFrameWidth();
}

void SettingsConfig::setVideoExportFrameWidth(int value)
{
	m_settings->setVideoExportFrameWidth(value);
}

int SettingsConfig::getVideoExportSizeChoice() const
{
	return m_settings->videoExportSizeChoice();
}

void SettingsConfig::setVideoExportSizeChoice(int value)
{
	m_settings->setVideoExportSizeChoice(value);
}

bool SettingsConfig::getWelcomePageShown() const
{
	return m_settings->welcomePageShown();
}

void SettingsConfig::setWelcomePageShown(bool value)
{
	m_settings->setWelcomePageShown(value);
}

bool SettingsConfig::getWriteLogFile() const
{
	return m_settings->writeLogFile();
}

void SettingsConfig::setWriteLogFile(bool value)
{
	m_settings->setWriteLogFile(value);
}

}
