#!/usr/bin/env perl
use strict;
use warnings;
use Encode;

my $result = 0;

sub replace_env {
    my ($key) = @_;
    my $value = $ENV{$key};
    if (defined $value) {
        return $value;
    } else {
        warn "Missing environment variable '$key'\n";
        $result = 1;
        return '';
    }
}

while (<STDIN>) {
    my $line = decode('UTF-8', $_);
    $line =~ s/\{\{\s*(\w+)\s*\}\}/replace_env($1)/ge;
    print encode('UTF-8', $line);
}

exit $result;
