#!/bin/bash
set -e
cd "$(dirname "$0")"


error=0


PKGDIR="$(pwd)"

export PKGDIR


BUILDDIR="$(pwd)/build"

export BUILDDIR


if [[ -z $BUILD_TYPE ]]; then
    BUILD_TYPE=Release
fi


if [[ -z $BUILD_TYPE_ARM64 ]]; then
    BUILD_TYPE_ARM64="$BUILD_TYPE"
fi

export BUILD_TYPE_ARM64

QT_BUILD_TYPE_ARM64="${BUILD_TYPE_ARM64,,}"
export QT_BUILD_TYPE_ARM64


if [[ -z $BUILD_TYPE_X86_64 ]]; then
    BUILD_TYPE_X86_64="$BUILD_TYPE"
fi

export BUILD_TYPE_X86_64

QT_BUILD_TYPE_X86_64="${BUILD_TYPE_X86_64,,}"
export QT_BUILD_TYPE_X86_64


if [[ -z $DRAWPILE_PATH ]]; then
    DRAWPILE_PATH="$(realpath ../..)"
fi

export DRAWPILE_PATH

if [[ ! -e "$DRAWPILE_PATH/CMakeLists.txt" ]]; then
    echo "Error: Drawpile does not seem to be at DRAWPILE_PATH '$DRAWPILE_PATH'" 1>&2
    error=1
fi


if [[ -z $DRAWDANCE_PATH ]]; then
    DRAWDANCE_PATH="$(realpath ../../../Drawdance)"
fi

export DRAWDANCE_PATH

if [[ ! -e "$DRAWDANCE_PATH/CMakeLists.txt" ]]; then
    echo "Error: Drawdance does not seem to be at DRAWDANCE_PATH '$DRAWDANCE_PATH'" 1>&2
    error=1
fi


if [[ -z $SDK_PATH ]]; then
    SDK_PATH="$(realpath ~/Android/Sdk)"
fi

export SDK_PATH

if [[ ! -e "$SDK_PATH/platform-tools" ]]; then
    echo "Error: Android SDK does not seem to be at '$SDK_PATH'" 1>&2
    error=1
fi


if [[ -z $NDK_PATH ]]; then
    NDK_PATH="$(realpath "$SDK_PATH/ndk/20.1.5948944")"
fi

export NDK_PATH

if [[ ! -e "$NDK_PATH" ]]; then
    echo "Error: Android NDK does not seem to be at '$NDK_PATH'" 1>&2
    error=1
fi


NDK_VERSION="$(basename "$NDK_PATH")"

export NDK_VERSION


BUILD_TOOLS_VERSION="$(ls -1 "$SDK_PATH/build-tools" | sort -V | tail -1)"

export BUILD_TOOLS_VERSION

if [[ -z $BUILD_TOOLS_VERSION ]]; then
    echo "Error: can't figure out latest build tools at '$SDK_PATH/build-tools'" 1>&2
    error=1
fi


if [[ $error -ne 0 ]]; then
    exit 1
fi

mkdir -p build
./envreplace <Makefile.template >build/Makefile
echo
echo 'Generated build/Makefile'
echo
