#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long;
use File::Basename qw(basename dirname);
use File::Copy qw(cp);
use File::Find qw(find);
use File::Path qw(make_path);


my ($appdir, $plugin_type, $plugin_api_version);
GetOptions(
    'appdir=s' => \$appdir,
    'plugin_type' => \$plugin_type,
    'plugin-api-version' => \$plugin_api_version,
) or die "Error in command-line arguments\n";

if ($plugin_type) {
    print "input\n";
    exit;
}

if ($plugin_api_version) {
    print "0\n";
    exit;
}

if (!$appdir) {
    die "--appdir parameter is required\n";
}

my $dstdir = "$appdir/usr/lib";
if (!-d $dstdir) {
    make_path($dstdir);
    if (!-d $dstdir) {
        die "Failed to create '$dstdir'\n";
    }
}

my @files_to_deploy;
find(sub {
    if (!-d && /\Alib(secret-1\b|gio-2\.0\b|gobject-2\.0\b|glib-2\.0\b).*\.so\b/) {
        push @files_to_deploy, [$File::Find::name, "$dstdir/$_"];
    }
}, '/usr/lib/x86_64-linux-gnu');

for (@files_to_deploy) {
    my ($src, $dst) = @$_;
    my $code = system 'cp', '-va', $src, $dst;
    if ($? != 0) {
        die "Failed to copy '$src' to '$dst': $!\n";
    }

    my $base = basename($dst);
    if ($base =~ /\Alib/) {
        my $dir = dirname($dst);
        my $link = $base;
        $link =~ s/\Alib//;
        system 'ln', '-vs', $base, "$dir/$link";
        if ($? != 0) {
            die "Failed to link '$dir/$link' to '$base': $!\n";
        }
    }
}

print STDERR "Done deploying libsecret\n";
